/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.AQFT.HaagKastler.Net
import Physicslib4.Spacetime.MinkowskiDirected

/-!
# Towards the intertwiner on the generated subalgebra

This file begins assembling the densely-defined intertwiner used to lift the
fiberwise covariance action to the quasilocal algebra (`QuasilocalLift`). Two
ingredients are established here:

* `IsAlexandrovBasisSet.directed`: the Haag-Kastler-level restatement of
  `Spacetime.alexandrovBasis_directed` (any two basis sets lie in a common
  basis set).
* `dense_adjoin_iUnion_range_ι`: the `*`-subalgebra of `𝔘` generated by the
  union of the local images `ι_B(𝔘(B))` is dense - so it is a valid domain for
  the dense-extension lemma `exists_starAlgHom_extend_of_dense`.

The remaining step - defining the intertwiner `ι_B a ↦ ι_{L·B}(α_L a)` on this
generated subalgebra and checking it is a well-defined `*`-homomorphism - will
use `StarAlgebra.adjoin_induction` together with the isotony-coherence field
`QuasilocalAlgebra.ι_inclusion` and basis directedness.
-/

namespace Physicslib4
namespace AQFT
namespace HaagKastler

open Physicslib4

/-- **Haag-Kastler directedness of the Alexandrov basis.** Any two
Alexandrov-basis sets are contained in a common Alexandrov-basis set. -/
theorem IsAlexandrovBasisSet.directed
    {B₁ B₂ : Set StandardMinkowskiSpacetime.Carrier}
    (h₁ : IsAlexandrovBasisSet B₁) (h₂ : IsAlexandrovBasisSet B₂) :
    ∃ B, IsAlexandrovBasisSet B ∧ B₁ ⊆ B ∧ B₂ ⊆ B :=
  Spacetime.alexandrovBasis_directed h₁ h₂

/-- The `*`-subalgebra of the quasilocal algebra generated by the union of all
local images is dense: it contains the (already dense) union of the images
`ι_B(𝔘(B))`. -/
theorem dense_adjoin_iUnion_range_ι {U : LocalNet} (Q : QuasilocalAlgebra U) :
    Dense (StarAlgebra.adjoin ℂ
      (⋃ (B : Set StandardMinkowskiSpacetime.Carrier) (_ : IsAlexandrovBasisSet B),
        Set.range (Q.ι B)) : Set Q.carrier) :=
  Q.dense_range.mono (StarAlgebra.subset_adjoin ℂ _)

namespace QuasilocalAlgebra

variable {U : LocalNet} (Q : QuasilocalAlgebra U)

/-- The union of all local images `ι_B(𝔘(B))` over Alexandrov-basis sets `B`. -/
def localImages : Set Q.carrier :=
  ⋃ (B : Set StandardMinkowskiSpacetime.Carrier) (_ : IsAlexandrovBasisSet B),
    Set.range (Q.ι B)

@[simp] theorem mem_localImages {x : Q.carrier} :
    x ∈ Q.localImages ↔ ∃ B, IsAlexandrovBasisSet B ∧ ∃ a, Q.ι B a = x := by
  simp only [localImages, Set.mem_iUnion, Set.mem_range, exists_prop]

/-- **Directedness of the local images.** Any two elements of the union of
local images are images, from a *common* basis set `C`, of elements of
`𝔘(C)` - using basis directedness and the isotony-coherence `ι_inclusion`. -/
theorem exists_common_image {x y : Q.carrier}
    (hx : x ∈ Q.localImages) (hy : y ∈ Q.localImages) :
    ∃ C, IsAlexandrovBasisSet C ∧ ∃ a b : U.algebra C,
      Q.ι C a = x ∧ Q.ι C b = y := by
  rw [mem_localImages] at hx hy
  obtain ⟨B, hB, a, rfl⟩ := hx
  obtain ⟨B', hB', a', rfl⟩ := hy
  obtain ⟨C, hC, hBC, hB'C⟩ := IsAlexandrovBasisSet.directed hB hB'
  exact ⟨C, hC, Q.inclusion hB hC hBC a, Q.inclusion hB' hC hB'C a',
    Q.ι_inclusion hB hC hBC a, Q.ι_inclusion hB' hC hB'C a'⟩

/-- **The union of local images is a `*`-subalgebra of the quasilocal algebra.**
Closure under multiplication and addition uses directedness (`exists_common_image`)
to route both arguments through a single embedding `ι_C`; closure under `star`,
`1`, `0`, and scalars is pointwise. -/
def localStarSubalgebra : StarSubalgebra ℂ Q.carrier where
  carrier := Q.localImages
  mul_mem' := by
    intro x y hx hy
    obtain ⟨C, hC, a, b, rfl, rfl⟩ := Q.exists_common_image hx hy
    rw [mem_localImages]
    exact ⟨C, hC, a * b, by rw [map_mul]⟩
  add_mem' := by
    intro x y hx hy
    obtain ⟨C, hC, a, b, rfl, rfl⟩ := Q.exists_common_image hx hy
    rw [mem_localImages]
    exact ⟨C, hC, a + b, by rw [map_add]⟩
  one_mem' := by
    rw [mem_localImages]
    exact ⟨trivialBasisSet, isAlexandrovBasisSet_trivialBasisSet, 1, by rw [map_one]⟩
  zero_mem' := by
    rw [mem_localImages]
    exact ⟨trivialBasisSet, isAlexandrovBasisSet_trivialBasisSet, 0, by rw [map_zero]⟩
  algebraMap_mem' := by
    intro r
    rw [mem_localImages]
    exact ⟨trivialBasisSet, isAlexandrovBasisSet_trivialBasisSet,
      algebraMap ℂ _ r, AlgHomClass.commutes (Q.ι trivialBasisSet) r⟩
  star_mem' := by
    intro x hx
    rw [mem_localImages] at hx ⊢
    obtain ⟨B, hB, a, rfl⟩ := hx
    exact ⟨B, hB, star a, by rw [map_star]⟩

@[simp] theorem coe_localStarSubalgebra :
    (Q.localStarSubalgebra : Set Q.carrier) = Q.localImages := rfl

/-- The local `*`-subalgebra is dense in the quasilocal algebra. -/
theorem dense_localStarSubalgebra :
    Dense (Q.localStarSubalgebra : Set Q.carrier) := by
  rw [coe_localStarSubalgebra]
  exact Q.dense_range

end QuasilocalAlgebra

open scoped Pointwise

/-- **Covariance-compatible embeddings.** A quasilocal algebra `Q` of the net
`N` is *covariant-compatible* for a Lorentz transformation `L` if its local
embeddings intertwine the covariance action with the chosen isotony inclusions:
`ι_{L·B}(α_L a) = ι_{L·C}(α_L (incl_{B,C} a))` for `B ⊆ C`. This is the
honest content carried by the embeddings of a genuinely covariant `𝔘`. -/
def IsCovariantQuasilocal (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U)
    (L : InhomogeneousLorentzGroup) : Prop :=
  ∀ ⦃B C : Set StandardMinkowskiSpacetime.Carrier⦄
    (hB : IsAlexandrovBasisSet B) (hC : IsAlexandrovBasisSet C) (h : B ⊆ C)
    (a : N.U.algebra B),
      Q.ι (L • B) (N.covEquiv L B a)
        = Q.ι (L • C) (N.covEquiv L C (Q.inclusion hB hC h a))

/-- **Well-definedness of the intertwiner.** If two local elements `ι_B a` and
`ι_{B'} a'` agree in `𝔘`, then their intended images
`ι_{L·B}(α_L a)` and `ι_{L·B'}(α_L a')` agree. The proof routes both through a
common basis set `C` (directedness), uses `ι_inclusion` + injectivity to
identify the inclusions, and `hcompat` to push through the action. -/
theorem ι_covEquiv_congr (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U)
    (L : InhomogeneousLorentzGroup) (hcompat : IsCovariantQuasilocal N Q L)
    ⦃B B' : Set StandardMinkowskiSpacetime.Carrier⦄
    (hB : IsAlexandrovBasisSet B) (hB' : IsAlexandrovBasisSet B')
    (a : N.U.algebra B) (a' : N.U.algebra B') (heq : Q.ι B a = Q.ι B' a') :
    Q.ι (L • B) (N.covEquiv L B a) = Q.ι (L • B') (N.covEquiv L B' a') := by
  obtain ⟨C, hC, hBC, hB'C⟩ := IsAlexandrovBasisSet.directed hB hB'
  have hinj : Q.inclusion hB hC hBC a = Q.inclusion hB' hC hB'C a' := by
    apply Q.ι_injective hC
    rw [Q.ι_inclusion hB hC hBC a, Q.ι_inclusion hB' hC hB'C a']
    exact heq
  calc Q.ι (L • B) (N.covEquiv L B a)
      = Q.ι (L • C) (N.covEquiv L C (Q.inclusion hB hC hBC a)) := hcompat hB hC hBC a
    _ = Q.ι (L • C) (N.covEquiv L C (Q.inclusion hB' hC hB'C a')) := by rw [hinj]
    _ = Q.ι (L • B') (N.covEquiv L B' a') := (hcompat hB' hC hB'C a').symm

open Classical in
/-- The **intertwiner** on the quasilocal algebra: on a local element `ι_B a`
it returns `ι_{L·B}(α_L a)` (and `0` off the local images). Its characterising
equation is `intertwiner_ι`, valid once `Q` is covariance-compatible. -/
noncomputable def intertwiner (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U)
    (L : InhomogeneousLorentzGroup) (x : Q.carrier) : Q.carrier :=
  if h : ∃ B, IsAlexandrovBasisSet B ∧ ∃ a : N.U.algebra B, Q.ι B a = x then
    Q.ι (L • h.choose) (N.covEquiv L h.choose h.choose_spec.2.choose)
  else 0

/-- **Defining equation of the intertwiner.** On `ι_B a` it returns
`ι_{L·B}(α_L a)`, well-definedly. -/
theorem intertwiner_ι (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U)
    (L : InhomogeneousLorentzGroup) (hcompat : IsCovariantQuasilocal N Q L)
    {B : Set StandardMinkowskiSpacetime.Carrier} (hB : IsAlexandrovBasisSet B)
    (a : N.U.algebra B) :
    intertwiner N Q L (Q.ι B a) = Q.ι (L • B) (N.covEquiv L B a) := by
  have h₀ : ∃ B', IsAlexandrovBasisSet B' ∧ ∃ a' : N.U.algebra B', Q.ι B' a' = Q.ι B a :=
    ⟨B, hB, a, rfl⟩
  unfold intertwiner
  rw [dif_pos h₀]
  exact ι_covEquiv_congr N Q L hcompat h₀.choose_spec.1 hB h₀.choose_spec.2.choose a
    h₀.choose_spec.2.choose_spec

end HaagKastler
end AQFT
end Physicslib4
