/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.AQFT.HaagKastler.Net
import Physicslib4.AQFT.HaagKastler.QuasilocalAction
import Physicslib4.Spacetime.MinkowskiDirected
import Physicslib4.Spacetime.LorentzCausality
import Physicslib4.Analysis.CStarDenseExtend
import Physicslib4.GNS.UnitaryRepresentation
import Physicslib4.GNS.RadonNikodym
import Physicslib4.GNS.ExtremeState
import Physicslib4.GNS.Covariance

/-!
# Towards the intertwiner on the generated subalgebra

This file begins assembling the densely-defined intertwiner used to lift the
fiberwise covariance action to the quasilocal algebra (`QuasilocalLift`). Two
ingredients are established here:

* `IsAlexandrovBasisSet.directed`: the Haag-Kastler-level restatement of
  `Spacetime.alexandrovBasis_directed` (any two basis sets lie in a common
  basis set).
* `dense_adjoin_iUnion_range_ι`: the `*`-subalgebra of `𝔘` generated by the
  union of the local images `ι_B(𝔘(B))` is dense - so it is a valid domain for
  the dense-extension lemma `exists_starAlgHom_extend_of_dense`.

The remaining step - defining the intertwiner `ι_B a ↦ ι_{L·B}(α_L a)` on this
generated subalgebra and checking it is a well-defined `*`-homomorphism - will
use `StarAlgebra.adjoin_induction` together with the isotony-coherence field
`QuasilocalAlgebra.ι_inclusion` and basis directedness.
-/

namespace Physicslib4
namespace AQFT
namespace HaagKastler

open Physicslib4

universe u

/-- **Haag-Kastler directedness of the Alexandrov basis.** Any two
Alexandrov-basis sets are contained in a common Alexandrov-basis set. -/
theorem IsAlexandrovBasisSet.directed
    {B₁ B₂ : Set StandardMinkowskiSpacetime.Carrier}
    (h₁ : IsAlexandrovBasisSet B₁) (h₂ : IsAlexandrovBasisSet B₂) :
    ∃ B, IsAlexandrovBasisSet B ∧ B₁ ⊆ B ∧ B₂ ⊆ B :=
  Spacetime.alexandrovBasis_directed h₁ h₂

/-- The `*`-subalgebra of the quasilocal algebra generated by the union of all
local images is dense: it contains the (already dense) union of the images
`ι_B(𝔘(B))`. -/
theorem dense_adjoin_iUnion_range_ι {U : LocalNet} {i : Isotony U} (Q : QuasilocalAlgebra U i) :
    Dense (StarAlgebra.adjoin ℂ
      (⋃ (B : Set StandardMinkowskiSpacetime.Carrier) (hB : IsAlexandrovBasisSet B),
        Set.range (Q.ι hB)) : Set Q.carrier) :=
  Q.dense_range.mono (StarAlgebra.subset_adjoin ℂ _)

namespace QuasilocalAlgebra

variable {U : LocalNet} {i : Isotony U} (Q : QuasilocalAlgebra U i)

/-- The union of all local images `ι_B(𝔘(B))` over Alexandrov-basis sets `B`. -/
def localImages : Set Q.carrier :=
  ⋃ (B : Set StandardMinkowskiSpacetime.Carrier) (hB : IsAlexandrovBasisSet B),
    Set.range (Q.ι hB)

@[simp] theorem mem_localImages {x : Q.carrier} :
    x ∈ Q.localImages ↔
      ∃ B, ∃ hB : IsAlexandrovBasisSet B, ∃ a, Q.ι hB a = x := by
  simp only [localImages, Set.mem_iUnion, Set.mem_range]

/-- **Directedness of the local images.** Any two elements of the union of
local images are images, from a *common* basis set `C`, of elements of
`𝔘(C)` - using basis directedness and the isotony-coherence `ι_inclusion`. -/
theorem exists_common_image {x y : Q.carrier}
    (hx : x ∈ Q.localImages) (hy : y ∈ Q.localImages) :
    ∃ C, ∃ hC : IsAlexandrovBasisSet C, ∃ a b : U.algebra C,
      Q.ι hC a = x ∧ Q.ι hC b = y := by
  rw [mem_localImages] at hx hy
  obtain ⟨B, hB, a, rfl⟩ := hx
  obtain ⟨B', hB', a', rfl⟩ := hy
  obtain ⟨C, hC, hBC, hB'C⟩ := IsAlexandrovBasisSet.directed hB hB'
  exact ⟨C, hC, i.map hB hC hBC a, i.map hB' hC hB'C a',
    Q.ι_inclusion hB hC hBC a, Q.ι_inclusion hB' hC hB'C a'⟩

/-- **The union of local images is a `*`-subalgebra of the quasilocal algebra.**
Closure under multiplication and addition uses directedness (`exists_common_image`)
to route both arguments through a single embedding `ι_C`; closure under `star`,
`1`, `0`, and scalars is pointwise. -/
def localStarSubalgebra : StarSubalgebra ℂ Q.carrier where
  carrier := Q.localImages
  mul_mem' := by
    intro x y hx hy
    obtain ⟨C, hC, a, b, rfl, rfl⟩ := Q.exists_common_image hx hy
    rw [mem_localImages]
    exact ⟨C, hC, a * b, by rw [map_mul]⟩
  add_mem' := by
    intro x y hx hy
    obtain ⟨C, hC, a, b, rfl, rfl⟩ := Q.exists_common_image hx hy
    rw [mem_localImages]
    exact ⟨C, hC, a + b, by rw [map_add]⟩
  one_mem' := by
    rw [mem_localImages]
    exact ⟨trivialBasisSet, isAlexandrovBasisSet_trivialBasisSet, 1, by rw [map_one]⟩
  zero_mem' := by
    rw [mem_localImages]
    exact ⟨trivialBasisSet, isAlexandrovBasisSet_trivialBasisSet, 0, by rw [map_zero]⟩
  algebraMap_mem' := by
    intro r
    rw [mem_localImages]
    exact ⟨trivialBasisSet, isAlexandrovBasisSet_trivialBasisSet,
      algebraMap ℂ _ r, AlgHomClass.commutes (Q.ι isAlexandrovBasisSet_trivialBasisSet) r⟩
  star_mem' := by
    intro x hx
    rw [mem_localImages] at hx ⊢
    obtain ⟨B, hB, a, rfl⟩ := hx
    exact ⟨B, hB, star a, by rw [map_star]⟩

@[simp] theorem coe_localStarSubalgebra :
    (Q.localStarSubalgebra : Set Q.carrier) = Q.localImages := rfl

/-- The local `*`-subalgebra is dense in the quasilocal algebra. -/
theorem dense_localStarSubalgebra :
    Dense (Q.localStarSubalgebra : Set Q.carrier) := by
  rw [coe_localStarSubalgebra]
  exact Q.dense_range

/-- **Naturality of the embeddings under set equality.** If `B₁ = B₂` then the
embedding of `a` and of its transport agree in `𝔘`. Used to reconcile the
cross-fiber casts coming from `covEquiv_one` / `covEquiv_mul`. -/
theorem ι_cast ⦃B₁ B₂ : Set StandardMinkowskiSpacetime.Carrier⦄
    (hB₁ : IsAlexandrovBasisSet B₁) (hB₂ : IsAlexandrovBasisSet B₂) (h : B₁ = B₂)
    (a : U.algebra B₁) :
    Q.ι hB₂ ((congrArg U.algebra h).mp a) = Q.ι hB₁ a := by
  subst h; rfl

end QuasilocalAlgebra

open scoped Pointwise

/-- **Covariance-compatible embeddings.** A quasilocal algebra `Q` of the net
`N` is *covariant-compatible* for a Lorentz transformation `L` if its local
embeddings intertwine the covariance action with the chosen isotony inclusions:
`ι_{L·B}(α_L a) = ι_{L·C}(α_L (incl_{B,C} a))` for `B ⊆ C`. This is the
honest content carried by the embeddings of a genuinely covariant `𝔘`. -/
def IsCovariantQuasilocal (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) : Prop :=
  ∀ ⦃B C : Set StandardMinkowskiSpacetime.Carrier⦄
    (hB : IsAlexandrovBasisSet B) (hC : IsAlexandrovBasisSet C) (h : B ⊆ C)
    (a : N.U.algebra B),
      Q.ι (isAlexandrovBasisSet_smul L hB) (N.covEquiv L B a)
        = Q.ι (isAlexandrovBasisSet_smul L hC)
            (N.covEquiv L C (N.isotony.map hB hC h a))

/-- **Every quasilocal algebra is covariance-compatible.** Axiom 5 (3) is stated
for the Axiom 2 isotony family, so `α_L` intertwines the isotony embeddings, and
the cocone condition `ι_inclusion` then gives `IsCovariantQuasilocal` for every
quasilocal algebra and every Lorentz transformation. -/
theorem isCovariantQuasilocal (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) : IsCovariantQuasilocal N Q L := by
  intro B C hB hC h a
  rw [N.covEquiv_isotony L hB hC h (isAlexandrovBasisSet_smul L hB)
    (isAlexandrovBasisSet_smul L hC) (Set.smul_set_mono h) a, Q.ι_inclusion]

/-- **Well-definedness of the intertwiner.** If two local elements `ι_B a` and
`ι_{B'} a'` agree in `𝔘`, then their intended images
`ι_{L·B}(α_L a)` and `ι_{L·B'}(α_L a')` agree. The proof routes both through a
common basis set `C` (directedness), uses `ι_inclusion` + injectivity to
identify the inclusions, and `isCovariantQuasilocal` to push through the action. -/
theorem ι_covEquiv_congr (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    ⦃B B' : Set StandardMinkowskiSpacetime.Carrier⦄
    (hB : IsAlexandrovBasisSet B) (hB' : IsAlexandrovBasisSet B')
    (a : N.U.algebra B) (a' : N.U.algebra B') (heq : Q.ι hB a = Q.ι hB' a') :
    Q.ι (isAlexandrovBasisSet_smul L hB) (N.covEquiv L B a)
      = Q.ι (isAlexandrovBasisSet_smul L hB') (N.covEquiv L B' a') := by
  have hcompat := isCovariantQuasilocal N Q L
  obtain ⟨C, hC, hBC, hB'C⟩ := IsAlexandrovBasisSet.directed hB hB'
  have hinj : N.isotony.map hB hC hBC a = N.isotony.map hB' hC hB'C a' := by
    apply Q.ι_injective hC
    rw [Q.ι_inclusion hB hC hBC a, Q.ι_inclusion hB' hC hB'C a']
    exact heq
  calc Q.ι (isAlexandrovBasisSet_smul L hB) (N.covEquiv L B a)
      = Q.ι (isAlexandrovBasisSet_smul L hC)
          (N.covEquiv L C (N.isotony.map hB hC hBC a)) := hcompat hB hC hBC a
    _ = Q.ι (isAlexandrovBasisSet_smul L hC)
          (N.covEquiv L C (N.isotony.map hB' hC hB'C a')) := by rw [hinj]
    _ = Q.ι (isAlexandrovBasisSet_smul L hB') (N.covEquiv L B' a') := (hcompat hB' hC hB'C a').symm

open Classical in
/-- The **intertwiner** on the quasilocal algebra: on a local element `ι_B a`
it returns `ι_{L·B}(α_L a)` (and `0` off the local images). Its characterising
equation is `intertwiner_ι`. -/
noncomputable def intertwiner (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) (x : Q.carrier) : Q.carrier :=
  if h : ∃ B, ∃ hB : IsAlexandrovBasisSet B, ∃ a : N.U.algebra B, Q.ι hB a = x then
    Q.ι (isAlexandrovBasisSet_smul L h.choose_spec.choose)
      (N.covEquiv L h.choose h.choose_spec.choose_spec.choose)
  else 0

/-- **Defining equation of the intertwiner.** On `ι_B a` it returns
`ι_{L·B}(α_L a)`, well-definedly. -/
theorem intertwiner_ι (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    {B : Set StandardMinkowskiSpacetime.Carrier} (hB : IsAlexandrovBasisSet B)
    (a : N.U.algebra B) :
    intertwiner N Q L (Q.ι hB a)
      = Q.ι (isAlexandrovBasisSet_smul L hB) (N.covEquiv L B a) := by
  have h₀ : ∃ B', ∃ hB' : IsAlexandrovBasisSet B',
      ∃ a' : N.U.algebra B', Q.ι hB' a' = Q.ι hB a :=
    ⟨B, hB, a, rfl⟩
  unfold intertwiner
  rw [dif_pos h₀]
  exact ι_covEquiv_congr N Q L h₀.choose_spec.1 hB h₀.choose_spec.2.choose a
    h₀.choose_spec.2.choose_spec

/-- **Additivity of the intertwiner.** On the local images it preserves
addition - both arguments are routed through a common basis algebra `ι_C`. -/
theorem intertwiner_add (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    {x y : Q.carrier} (hx : x ∈ Q.localImages) (hy : y ∈ Q.localImages) :
    intertwiner N Q L (x + y) = intertwiner N Q L x + intertwiner N Q L y := by
  obtain ⟨C, hC, a, b, rfl, rfl⟩ := Q.exists_common_image hx hy
  rw [← map_add (Q.ι hC), intertwiner_ι N Q L hC (a + b),
    intertwiner_ι N Q L hC a, intertwiner_ι N Q L hC b,
    map_add (N.covEquiv L C), map_add (Q.ι (isAlexandrovBasisSet_smul L hC))]

/-- **Multiplicativity of the intertwiner.** On the local images it preserves
multiplication - both arguments are routed through a common basis algebra. -/
theorem intertwiner_mul (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    {x y : Q.carrier} (hx : x ∈ Q.localImages) (hy : y ∈ Q.localImages) :
    intertwiner N Q L (x * y) = intertwiner N Q L x * intertwiner N Q L y := by
  obtain ⟨C, hC, a, b, rfl, rfl⟩ := Q.exists_common_image hx hy
  rw [← map_mul (Q.ι hC), intertwiner_ι N Q L hC (a * b),
    intertwiner_ι N Q L hC a, intertwiner_ι N Q L hC b,
    map_mul (N.covEquiv L C), map_mul (Q.ι (isAlexandrovBasisSet_smul L hC))]

/-- The intertwiner preserves `0`. -/
theorem intertwiner_zero (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) :
    intertwiner N Q L 0 = 0 := by
  have h : intertwiner N Q L
      (Q.ι isAlexandrovBasisSet_trivialBasisSet (0 : N.U.algebra trivialBasisSet)) = 0 := by
    rw [intertwiner_ι N Q L isAlexandrovBasisSet_trivialBasisSet 0, map_zero, map_zero]
  simpa using h

/-- The intertwiner preserves `1`. -/
theorem intertwiner_one (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) :
    intertwiner N Q L 1 = 1 := by
  have h : intertwiner N Q L
      (Q.ι isAlexandrovBasisSet_trivialBasisSet (1 : N.U.algebra trivialBasisSet)) = 1 := by
    rw [intertwiner_ι N Q L isAlexandrovBasisSet_trivialBasisSet 1, map_one, map_one]
  simpa using h

/-- The intertwiner preserves `star` on the local images. -/
theorem intertwiner_star (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    {x : Q.carrier} (hx : x ∈ Q.localImages) :
    intertwiner N Q L (star x) = star (intertwiner N Q L x) := by
  rw [Q.mem_localImages] at hx
  obtain ⟨B, hB, a, rfl⟩ := hx
  rw [← map_star (Q.ι hB), intertwiner_ι N Q L hB (star a),
    intertwiner_ι N Q L hB a, map_star (N.covEquiv L B),
    map_star (Q.ι (isAlexandrovBasisSet_smul L hB))]

/-- The intertwiner is `ℂ`-linear on the local images. -/
theorem intertwiner_smul (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    (c : ℂ) {x : Q.carrier} (hx : x ∈ Q.localImages) :
    intertwiner N Q L (c • x) = c • intertwiner N Q L x := by
  rw [Q.mem_localImages] at hx
  obtain ⟨B, hB, a, rfl⟩ := hx
  rw [← map_smul (Q.ι hB) c a, intertwiner_ι N Q L hB (c • a),
    intertwiner_ι N Q L hB a, map_smul (N.covEquiv L B),
    map_smul (Q.ι (isAlexandrovBasisSet_smul L hB))]

/-- **The intertwiner as a `*`-homomorphism on the local subalgebra.** Bundles
the homomorphism laws of `intertwiner` into a `StarAlgHom` from the dense local
`*`-subalgebra of `𝔘` into `𝔘`. -/
noncomputable def intertwinerHom (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) :
    Q.localStarSubalgebra →⋆ₐ[ℂ] Q.carrier where
  toFun s := intertwiner N Q L (s : Q.carrier)
  map_one' := by
    change intertwiner N Q L ((1 : Q.localStarSubalgebra) : Q.carrier) = 1
    rw [OneMemClass.coe_one]; exact intertwiner_one N Q L
  map_mul' s t := by
    change intertwiner N Q L ((s * t : Q.localStarSubalgebra) : Q.carrier)
      = intertwiner N Q L (s : Q.carrier) * intertwiner N Q L (t : Q.carrier)
    rw [MulMemClass.coe_mul]; exact intertwiner_mul N Q L s.2 t.2
  map_zero' := by
    change intertwiner N Q L ((0 : Q.localStarSubalgebra) : Q.carrier) = 0
    rw [ZeroMemClass.coe_zero]; exact intertwiner_zero N Q L
  map_add' s t := by
    change intertwiner N Q L ((s + t : Q.localStarSubalgebra) : Q.carrier)
      = intertwiner N Q L (s : Q.carrier) + intertwiner N Q L (t : Q.carrier)
    rw [AddMemClass.coe_add]; exact intertwiner_add N Q L s.2 t.2
  commutes' r := by
    change intertwiner N Q L ((algebraMap ℂ Q.localStarSubalgebra r : Q.carrier))
      = algebraMap ℂ Q.carrier r
    have hcoe : ((algebraMap ℂ Q.localStarSubalgebra r : Q.carrier))
        = algebraMap ℂ Q.carrier r :=
      AlgHomClass.commutes (StarSubalgebra.subtype Q.localStarSubalgebra) r
    rw [hcoe, Algebra.algebraMap_eq_smul_one,
      intertwiner_smul N Q L r (one_mem Q.localStarSubalgebra),
      intertwiner_one N Q L]
  map_star' s := by
    rw [StarMemClass.coe_star]; exact intertwiner_star N Q L s.2

@[simp] theorem intertwinerHom_apply (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    (s : Q.localStarSubalgebra) :
    intertwinerHom N Q L s = intertwiner N Q L (s : Q.carrier) := rfl

/-- **The intertwiner is norm-preserving on the local images.** It maps
`ι_B a ↦ ι_{L·B}(α_L a)`; both embeddings are isometric (`norm_ι`, using that
`L·B` is again a basis set) and `α_L` is isometric (`norm_covEquiv`). -/
theorem intertwiner_norm (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup)
    {x : Q.carrier} (hx : x ∈ Q.localImages) :
    ‖intertwiner N Q L x‖ = ‖x‖ := by
  rw [Q.mem_localImages] at hx
  obtain ⟨B, hB, a, rfl⟩ := hx
  rw [intertwiner_ι N Q L hB a, Q.norm_ι (isAlexandrovBasisSet_smul L hB),
    N.norm_covEquiv, Q.norm_ι hB]

/-- **The bundled intertwiner is an isometry** on the local `*`-subalgebra. -/
theorem intertwinerHom_isometry (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) :
    Isometry (intertwinerHom N Q L) := by
  refine Isometry.of_dist_eq (fun x y => ?_)
  rw [Subtype.dist_eq, dist_eq_norm, dist_eq_norm,
    ← map_sub (intertwinerHom N Q L), intertwinerHom_apply,
    AddSubgroupClass.coe_sub]
  exact intertwiner_norm N Q L (sub_mem x.2 y.2)

/-- **Existence of the extended intertwiner.** The norm-preserving (hence
uniformly continuous) `*`-homomorphism on the dense local `*`-subalgebra extends
to a `*`-homomorphism `F : 𝔘 →⋆ₐ[ℂ] 𝔘` agreeing with the intertwiner on the
local images. -/
theorem exists_intertwiner_extend (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)
    (L : InhomogeneousLorentzGroup) :
    ∃ F : Q.carrier →⋆ₐ[ℂ] Q.carrier, Continuous F ∧
      ∀ s : Q.localStarSubalgebra, F (s : Q.carrier) = intertwiner N Q L (s : Q.carrier) := by
  obtain ⟨F, hFc, hF⟩ := exists_starAlgHom_extend_of_dense Q.localStarSubalgebra
    Q.dense_localStarSubalgebra (intertwinerHom N Q L)
    (intertwinerHom_isometry N Q L).uniformContinuous
  exact ⟨F, hFc, hF⟩

section Extend

variable (N : HaagKastlerNet) (Q : QuasilocalAlgebra N.U N.isotony)

/-- The chosen extended intertwiner `Φ_L : 𝔘 →⋆ₐ[ℂ] 𝔘` of a quasilocal
algebra. -/
noncomputable def extendHom (L : InhomogeneousLorentzGroup) : Q.carrier →⋆ₐ[ℂ] Q.carrier :=
  (exists_intertwiner_extend N Q L).choose

theorem extendHom_continuous (L : InhomogeneousLorentzGroup) : Continuous (extendHom N Q L) :=
  (exists_intertwiner_extend N Q L).choose_spec.1

/-- `Φ_L` implements the fiberwise action on the generators:
`Φ_L (ι_B a) = ι_{L·B}(α_L a)`. -/
theorem extendHom_ι (L : InhomogeneousLorentzGroup)
    {B : Set StandardMinkowskiSpacetime.Carrier} (hB : IsAlexandrovBasisSet B)
    (a : N.U.algebra B) :
    extendHom N Q L (Q.ι hB a)
      = Q.ι (isAlexandrovBasisSet_smul L hB) (N.covEquiv L B a) := by
  have hmem : Q.ι hB a ∈ Q.localStarSubalgebra := (Q.mem_localImages).mpr ⟨B, hB, a, rfl⟩
  have h := (exists_intertwiner_extend N Q L).choose_spec.2 ⟨Q.ι hB a, hmem⟩
  rw [intertwiner_ι N Q L hB a] at h
  exact h

variable {N Q} in
/-- Two `*`-homomorphisms of `𝔘` that are continuous and agree on the local
images are equal (the images are dense). -/
theorem starAlgHom_ext_localImages {f g : Q.carrier →⋆ₐ[ℂ] Q.carrier}
    (hf : Continuous f) (hg : Continuous g)
    (h : ∀ ⦃B : Set StandardMinkowskiSpacetime.Carrier⦄ (hB : IsAlexandrovBasisSet B)
      (a : N.U.algebra B), f (Q.ι hB a) = g (Q.ι hB a)) :
    f = g := by
  apply DFunLike.coe_injective
  apply Continuous.ext_on Q.dense_range hf hg
  intro x hx
  simp only [Set.mem_iUnion, Set.mem_range] at hx
  obtain ⟨B, hB, a, rfl⟩ := hx
  exact h hB a

/-- **`Φ` is multiplicative in the group element:** `Φ_{L'·L} = Φ_{L'} ∘ Φ_L`. -/
theorem extendHom_comp (L L' : InhomogeneousLorentzGroup) :
    extendHom N Q (L' * L) = (extendHom N Q L').comp (extendHom N Q L) := by
  refine starAlgHom_ext_localImages (extendHom_continuous N Q (L' * L))
    ((extendHom_continuous N Q L').comp (extendHom_continuous N Q L)) ?_
  intro B hB a
  rw [StarAlgHom.comp_apply, extendHom_ι N Q L hB a,
    extendHom_ι N Q L' (isAlexandrovBasisSet_smul L hB) (N.covEquiv L B a),
    extendHom_ι N Q (L' * L) hB a, N.covEquiv_mul L L' B a]
  exact Q.ι_cast (isAlexandrovBasisSet_smul L' (isAlexandrovBasisSet_smul L hB))
    (isAlexandrovBasisSet_smul (L' * L) hB) (mul_smul L' L B).symm
    (N.covEquiv L' (L • B) (N.covEquiv L B a))

/-- **`Φ_1 = id`.** -/
theorem extendHom_one :
    extendHom N Q 1 = StarAlgHom.id ℂ Q.carrier := by
  refine starAlgHom_ext_localImages (extendHom_continuous N Q 1) continuous_id ?_
  intro B hB a
  rw [extendHom_ι N Q 1 hB a, N.covEquiv_one B a]
  exact Q.ι_cast hB (isAlexandrovBasisSet_smul (1 : InhomogeneousLorentzGroup) hB)
    (one_smul InhomogeneousLorentzGroup B).symm a

theorem extendHom_comp_inv (L : InhomogeneousLorentzGroup) :
    (extendHom N Q L).comp (extendHom N Q L⁻¹) = StarAlgHom.id ℂ Q.carrier := by
  rw [← extendHom_comp N Q L⁻¹ L, mul_inv_cancel, extendHom_one]

theorem extendHom_inv_comp (L : InhomogeneousLorentzGroup) :
    (extendHom N Q L⁻¹).comp (extendHom N Q L) = StarAlgHom.id ℂ Q.carrier := by
  rw [← extendHom_comp N Q L L⁻¹, inv_mul_cancel, extendHom_one]

/-- **Existence of the quasilocal lift.** For every quasilocal algebra (all are
covariance-compatible, `isCovariantQuasilocal`), the fiberwise Lorentz action
lifts to a `*`-automorphism of `𝔘`, inhabiting `QuasilocalLift`. -/
noncomputable def quasilocalLift (L : InhomogeneousLorentzGroup) : N.QuasilocalLift Q L where
  β := StarAlgEquiv.ofStarAlgHom (extendHom N Q L) (extendHom N Q L⁻¹)
        (extendHom_inv_comp N Q L)
        (extendHom_comp_inv N Q L)
  intertwines := by
    intro B hB a
    rw [StarAlgEquiv.ofStarAlgHom_apply]
    exact extendHom_ι N Q L hB a

/-- The quasilocal lift exists for every Lorentz transformation. -/
theorem nonempty_quasilocalLift (L : InhomogeneousLorentzGroup) : Nonempty (N.QuasilocalLift Q L) :=
  ⟨quasilocalLift N Q L⟩

/-- **The quasilocal lift exists unconditionally for the trivial net.** -/
noncomputable def trivialQuasilocalLift (L : InhomogeneousLorentzGroup) :
    trivialHaagKastlerNet.QuasilocalLift trivialQuasilocalAlgebra L :=
  quasilocalLift trivialHaagKastlerNet trivialQuasilocalAlgebra L

theorem nonempty_trivialQuasilocalLift (L : InhomogeneousLorentzGroup) :
    Nonempty (trivialHaagKastlerNet.QuasilocalLift trivialQuasilocalAlgebra L) :=
  ⟨trivialQuasilocalLift L⟩

end Extend

namespace HaagKastlerNet

/-- The lift of the Lorentz action of `L` to a `*`-automorphism of the
quasilocal algebra, packaged as a `QuasilocalLift`. -/
noncomputable def lift (N : HaagKastlerNet)
    (L : InhomogeneousLorentzGroup) : N.QuasilocalLift N.quasilocal L :=
  quasilocalLift N N.quasilocal L

/-- The covariance `*`-automorphism `β_L` of the quasilocal algebra. -/
noncomputable def action (N : HaagKastlerNet)
    (L : InhomogeneousLorentzGroup) : N.quasilocal.carrier ≃⋆ₐ[ℂ] N.quasilocal.carrier :=
  (N.lift L).β

/-- The action implements the fiberwise covariance on the local images:
`β_L (ι_B a) = ι_{L·B}(α_L a)`. -/
theorem action_ι (N : HaagKastlerNet) (L : InhomogeneousLorentzGroup)
    {B : Set StandardMinkowskiSpacetime.Carrier} (hB : IsAlexandrovBasisSet B)
    (a : N.U.algebra B) :
    N.action L (N.quasilocal.ι hB a)
      = N.quasilocal.ι (isAlexandrovBasisSet_smul L hB) (N.covEquiv L B a) :=
  (N.lift L).intertwines hB a

/-- The action agrees with the underlying extended `*`-homomorphism. -/
theorem action_apply (N : HaagKastlerNet)
    (L : InhomogeneousLorentzGroup) (x : N.quasilocal.carrier) :
    N.action L x = extendHom N N.quasilocal L x :=
  StarAlgEquiv.ofStarAlgHom_apply (extendHom N N.quasilocal L)
    (extendHom N N.quasilocal L⁻¹)
    (extendHom_inv_comp N N.quasilocal L) (extendHom_comp_inv N N.quasilocal L) x

/-- **The action is trivial at the identity:** `β_1 = id`. -/
theorem action_one_apply (N : HaagKastlerNet)
    (x : N.quasilocal.carrier) : N.action 1 x = x := by
  rw [action_apply, DFunLike.congr_fun (extendHom_one N N.quasilocal) x]
  rfl

/-- **The action is multiplicative in the group element:**
`β_{L'·L} = β_{L'} ∘ β_L`. -/
theorem action_mul_apply (N : HaagKastlerNet)
    (L L' : InhomogeneousLorentzGroup) (x : N.quasilocal.carrier) :
    N.action (L' * L) x = N.action L' (N.action L x) := by
  rw [action_apply, action_apply, action_apply,
    DFunLike.congr_fun (extendHom_comp N N.quasilocal L L') x]
  rfl

/-- The covariance action sends the identity to the identity automorphism. -/
theorem action_one (N : HaagKastlerNet) :
    N.action 1 = StarAlgEquiv.refl ℂ N.quasilocal.carrier := by
  ext x; rw [action_one_apply]; rfl

/-- The covariance action is multiplicative: `β_{L'·L} = β_L` followed by
`β_{L'}`. -/
theorem action_mul (N : HaagKastlerNet)
    (L L' : InhomogeneousLorentzGroup) :
    N.action (L' * L) = (N.action L).trans (N.action L') := by
  ext x; rw [action_mul_apply]; rfl

/-- The covariance action packaged as a **group homomorphism** from the
inhomogeneous Lorentz group to the `*`-automorphism group of the quasilocal
algebra, `L ↦ β_L`. This bundles `action_one` and `action_mul`; the target's group
law is composition (`f * g = g.trans f`, `StarAlgEquiv.aut`), which is exactly the
form of `action_mul`. It exhibits the covariance action as a genuine unitary-free
representation of the Poincaré group by `*`-automorphisms of `𝔘`. -/
noncomputable def actionHom (N : HaagKastlerNet) :
    InhomogeneousLorentzGroup →* (N.quasilocal.carrier ≃⋆ₐ[ℂ] N.quasilocal.carrier) where
  toFun := N.action
  map_one' := N.action_one
  map_mul' a b := N.action_mul b a

@[simp] theorem actionHom_apply (N : HaagKastlerNet)
    (L : InhomogeneousLorentzGroup) : N.actionHom L = N.action L := rfl

/-- A state `ω` on the quasilocal algebra is *(Poincaré-)invariant* if it is a
fixed point of the dual covariance action: `ω(β_L a) = ω(a)` for every Lorentz
transformation `L` and every observable `a`. This is the invariance part of the
vacuum conditions; the spectrum condition is imposed separately. -/
def IsInvariantState (N : HaagKastlerNet)
    (ω : Physicslib4.GNS.State N.quasilocal.carrier) : Prop :=
  ∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier),
    ω (N.action L a) = ω a

/-- **Invariance of the GNS inner product.** For an invariant state, the
sesquilinear form `(a, b) ↦ ω(a^* b)` - which is the GNS inner product of the
cyclic vectors `π(a)Ω`, `π(b)Ω` - is preserved by the action. This is the
algebraic input that makes the implementing operator on the GNS space an
isometry, hence (Step 2) a unitary. -/
theorem IsInvariantState.inner_invariant (N : HaagKastlerNet)
    {ω : Physicslib4.GNS.State N.quasilocal.carrier} (hω : N.IsInvariantState ω)
    (L : InhomogeneousLorentzGroup) (a b : N.quasilocal.carrier) :
    ω (star (N.action L a) * N.action L b) = ω (star a * b) := by
  rw [← map_star (N.action L) a, ← map_mul (N.action L)]
  exact hω L (star a * b)

open scoped InnerProductSpace in
/-- **Step 2: GNS unitary implementation of an invariant state.** For an
invariant state `ω`, the fiberwise covariance action is implemented on the GNS
Hilbert space by a family of unitaries `U L` with `U L (π a Ω) = π (β_L a) Ω` and
`U L Ω = Ω`. The unitaries are the dense-extension of the isometry
`π a Ω ↦ π (β_L a) Ω` (isometric by `inner_invariant`), via
`LinearEquiv.extendOfIsometry`. -/
theorem IsInvariantState.exists_gns_unitary (N : HaagKastlerNet.{u})
    {ω : Physicslib4.GNS.State N.quasilocal.carrier} (hω : N.IsInvariantState ω) :
    ∃ (H : Type u) (_ : NormedAddCommGroup H) (_ : InnerProductSpace ℂ H)
      (_ : CompleteSpace H) (π : N.quasilocal.carrier →⋆ₐ[ℂ] (H →L[ℂ] H)) (Ω : H)
      (U : InhomogeneousLorentzGroup → (H ≃ₗᵢ[ℂ] H)),
        (∀ a : N.quasilocal.carrier, (ω a : ℂ) = ⟪Ω, π a Ω⟫_ℂ) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier),
          U L (π a Ω) = π (N.action L a) Ω) ∧
        (∀ L : InhomogeneousLorentzGroup, U L Ω = Ω) ∧
        (∀ L L' : InhomogeneousLorentzGroup, U (L' * L) = (U L).trans (U L')) ∧
        U 1 = LinearIsometryEquiv.refl ℂ H ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier) (x : H),
          U L (π a ((U L).symm x)) = π (N.action L a) x) ∧
        Physicslib4.GNS.IsCyclicVector π Ω :=
  -- This is the specialization of the algebra-agnostic
  -- `GNS.exists_gns_unitary_of_invariant` to the quasilocal algebra `𝔘` with the
  -- covariance action `β = N.action`: invariance is `hω`, multiplicativity is
  -- `action_mul_apply`, and the identity law is `action_one_apply`. The final
  -- clause is operator covariance `U(L) π(a) U(L)⁻¹ = π(β_L a)`.
  Physicslib4.GNS.exists_gns_unitary_of_invariant N.action ω hω
    N.action_mul_apply N.action_one_apply

open scoped InnerProductSpace in
/-- **Strongly continuous GNS unitary representation of an invariant state.**

Strengthening of `IsInvariantState.exists_gns_unitary`: if the quasilocal matrix
coefficients `L ↦ ω(a⋆ · β_L b)` are continuous in the Lorentz transformation
`L` (with respect to the topology on `InhomogeneousLorentzGroup`), then the
implementing unitary representation `U` is strongly continuous - `L ↦ U L ψ` is
continuous for every GNS vector `ψ`.

This is the quasilocal-state form of the weak-continuity hypothesis; it is the
direct specialization of the algebra-agnostic
`GNS.exists_gns_unitary_of_invariant_strongContinuous`. -/
theorem IsInvariantState.exists_gns_unitary_strongContinuous
    (N : HaagKastlerNet.{u})
    {ω : Physicslib4.GNS.State N.quasilocal.carrier} (hω : N.IsInvariantState ω)
    (hwc : ∀ a b : N.quasilocal.carrier,
      Continuous fun L : InhomogeneousLorentzGroup => (ω (star a * N.action L b) : ℂ)) :
    ∃ (H : Type u) (_ : NormedAddCommGroup H) (_ : InnerProductSpace ℂ H)
      (_ : CompleteSpace H) (π : N.quasilocal.carrier →⋆ₐ[ℂ] (H →L[ℂ] H)) (Ω : H)
      (U : InhomogeneousLorentzGroup → (H ≃ₗᵢ[ℂ] H)),
        (∀ a : N.quasilocal.carrier, (ω a : ℂ) = ⟪Ω, π a Ω⟫_ℂ) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier),
          U L (π a Ω) = π (N.action L a) Ω) ∧
        (∀ L : InhomogeneousLorentzGroup, U L Ω = Ω) ∧
        (∀ L L' : InhomogeneousLorentzGroup, U (L' * L) = (U L).trans (U L')) ∧
        U 1 = LinearIsometryEquiv.refl ℂ H ∧
        (∀ ψ : H, Continuous fun L : InhomogeneousLorentzGroup => U L ψ) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier) (x : H),
          U L (π a ((U L).symm x)) = π (N.action L a) x) :=
  Physicslib4.GNS.exists_gns_unitary_of_invariant_strongContinuous N.action ω hω
    N.action_mul_apply N.action_one_apply hwc

open scoped InnerProductSpace in
/-- **Bundled GNS unitary representation of an invariant state.** The bundled form
of `IsInvariantState.exists_gns_unitary`: the implementing unitaries are returned
as a genuine unitary representation `U : InhomogeneousLorentzGroup →* (H ≃ₗᵢ[ℂ] H)`
(a bundled group homomorphism), rather than a bare family with separate group-law
clauses. It feeds the covariance group homomorphism `N.actionHom` into the bundled
analytic core `GNS.exists_gns_unitaryRep_of_invariant`. -/
theorem IsInvariantState.exists_gns_unitaryRep (N : HaagKastlerNet.{u})
    {ω : Physicslib4.GNS.State N.quasilocal.carrier} (hω : N.IsInvariantState ω) :
    ∃ (H : Type u) (_ : NormedAddCommGroup H) (_ : InnerProductSpace ℂ H)
      (_ : CompleteSpace H) (π : N.quasilocal.carrier →⋆ₐ[ℂ] (H →L[ℂ] H)) (Ω : H)
      (U : InhomogeneousLorentzGroup →* (H ≃ₗᵢ[ℂ] H)),
        (∀ a : N.quasilocal.carrier, (ω a : ℂ) = ⟪Ω, π a Ω⟫_ℂ) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier),
          U L (π a Ω) = π (N.action L a) Ω) ∧
        (∀ L : InhomogeneousLorentzGroup, U L Ω = Ω) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier) (x : H),
          U L (π a ((U L).symm x)) = π (N.action L a) x) ∧
        Physicslib4.GNS.IsCyclicVector π Ω :=
  Physicslib4.GNS.exists_gns_unitaryRep_of_invariant N.actionHom ω hω

open scoped InnerProductSpace in
/-- **Bundled strongly continuous GNS unitary representation of an invariant state.**
The bundled form of `IsInvariantState.exists_gns_unitary_strongContinuous`: the
strongly continuous implementing unitaries are returned as a bundled group
homomorphism `U : InhomogeneousLorentzGroup →* (H ≃ₗᵢ[ℂ] H)`. -/
theorem IsInvariantState.exists_gns_unitaryRep_strongContinuous
    (N : HaagKastlerNet.{u})
    {ω : Physicslib4.GNS.State N.quasilocal.carrier} (hω : N.IsInvariantState ω)
    (hwc : ∀ a b : N.quasilocal.carrier,
      Continuous fun L : InhomogeneousLorentzGroup => (ω (star a * N.action L b) : ℂ)) :
    ∃ (H : Type u) (_ : NormedAddCommGroup H) (_ : InnerProductSpace ℂ H)
      (_ : CompleteSpace H) (π : N.quasilocal.carrier →⋆ₐ[ℂ] (H →L[ℂ] H)) (Ω : H)
      (U : InhomogeneousLorentzGroup →* (H ≃ₗᵢ[ℂ] H)),
        (∀ a : N.quasilocal.carrier, (ω a : ℂ) = ⟪Ω, π a Ω⟫_ℂ) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier),
          U L (π a Ω) = π (N.action L a) Ω) ∧
        (∀ L : InhomogeneousLorentzGroup, U L Ω = Ω) ∧
        (∀ ψ : H, Continuous fun L : InhomogeneousLorentzGroup => U L ψ) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier) (x : H),
          U L (π a ((U L).symm x)) = π (N.action L a) x) :=
  Physicslib4.GNS.exists_gns_unitaryRep_of_invariant_strongContinuous N.actionHom ω hω hwc

open scoped InnerProductSpace in
/-- **Irreducible covariant representation of a pure invariant state (Minkowski).**
A state `ω` on the quasilocal algebra that is both invariant under the covariance
action and pure yields a GNS representation that is simultaneously *covariant* -
implemented by a unitary representation `U` of the inhomogeneous Lorentz group
fixing the cyclic vector `Ω`, with the operator covariance
`U(L) π(a) U(L)⁻¹ = π(β_L a)` - and *irreducible*. It combines
`IsInvariantState.exists_gns_unitary` (a covariant GNS triple with invariant cyclic
`Ω`) with purity ⟹ irreducibility (`isPure_iff_isIrreducible`).

This is a necessary precursor to, but not yet, a *vacuum* representation: a genuine
vacuum would additionally require the spectrum condition (positivity of the energy-
momentum spectrum), which is not available here. -/
theorem IsInvariantState.exists_gns_irreducible_covariant (N : HaagKastlerNet.{u})
    {ω : Physicslib4.GNS.State N.quasilocal.carrier} (hω : N.IsInvariantState ω)
    (hpure : Physicslib4.GNS.IsPure ω) :
    ∃ (H : Type u) (_ : NormedAddCommGroup H) (_ : InnerProductSpace ℂ H)
      (_ : CompleteSpace H) (π : N.quasilocal.carrier →⋆ₐ[ℂ] (H →L[ℂ] H)) (Ω : H)
      (U : InhomogeneousLorentzGroup → (H ≃ₗᵢ[ℂ] H)),
        Physicslib4.GNS.IsCyclicVector π Ω ∧
        (∀ a : N.quasilocal.carrier, (ω a : ℂ) = ⟪Ω, π a Ω⟫_ℂ) ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier),
          U L (π a Ω) = π (N.action L a) Ω) ∧
        (∀ L : InhomogeneousLorentzGroup, U L Ω = Ω) ∧
        (∀ L L' : InhomogeneousLorentzGroup, U (L' * L) = (U L).trans (U L')) ∧
        U 1 = LinearIsometryEquiv.refl ℂ H ∧
        (∀ (L : InhomogeneousLorentzGroup) (a : N.quasilocal.carrier) (x : H),
          U L (π a ((U L).symm x)) = π (N.action L a) x) ∧
        Physicslib4.GNS.IsIrreducible π ∧
        Physicslib4.GNS.gnsVonNeumann π = Set.univ := by
  obtain ⟨H, i1, i2, i3, π, Ω, U, hrepro, himpl, hUΩ, hmul, hUone, hopcov, hcyc⟩ :=
    IsInvariantState.exists_gns_unitary N hω
  have hirr := (Physicslib4.GNS.isPure_iff_isIrreducible hcyc hrepro).mp hpure
  exact ⟨H, i1, i2, i3, π, Ω, U, hcyc, hrepro, himpl, hUΩ, hmul, hUone, hopcov, hirr,
    Physicslib4.GNS.gnsVonNeumann_eq_univ_of_isIrreducible hirr⟩

/-- **Purity is covariance-invariant (Minkowski).** A state `ω` on the quasilocal
algebra is pure if and only if its pullback `ω ∘ β_L` along the covariance
automorphism is pure: purity is preserved by the `*`-automorphism `β_L = N.action L`.
Specialization of `isPure_precomp_iff`. -/
theorem isPure_precomp_action_iff (N : HaagKastlerNet)
    (ω : Physicslib4.GNS.State N.quasilocal.carrier) (L : InhomogeneousLorentzGroup) :
    Physicslib4.GNS.IsPure (ω.precomp (N.action L)) ↔ Physicslib4.GNS.IsPure ω :=
  Physicslib4.GNS.isPure_precomp_iff ω (N.action L)

/-! ### GNS covariance along the quasilocal action -/

section GNSCovariance

open scoped InnerProductSpace

variable (N : HaagKastlerNet) (L : InhomogeneousLorentzGroup)
  (ω : Physicslib4.GNS.State N.quasilocal.carrier)
  {H₁ : Type*} [NormedAddCommGroup H₁] [InnerProductSpace ℂ H₁] [CompleteSpace H₁]
  (π₁ : N.quasilocal.carrier →⋆ₐ[ℂ] (H₁ →L[ℂ] H₁)) (Ω₁ : H₁)
  {H₂ : Type*} [NormedAddCommGroup H₂] [InnerProductSpace ℂ H₂] [CompleteSpace H₂]
  (π₂ : N.quasilocal.carrier →⋆ₐ[ℂ] (H₂ →L[ℂ] H₂)) (Ω₂ : H₂)

/-- **GNS covariance along the quasilocal action.** The lifted covariance automorphism
`β_L = N.action L` is a `*`-automorphism of the quasilocal algebra `𝔘`, so a cyclic
representation of `𝔘` reproducing the pullback state `ω ∘ β_L` is unitarily equivalent
to `π_ω ∘ β_L`. -/
theorem unitaryEquiv_gns_action
    (hcyc₁ : Physicslib4.GNS.IsCyclicVector π₁ Ω₁)
    (hrep₁ : ∀ a : N.quasilocal.carrier,
      ((ω.comp (N.action L).toStarAlgHom) a : ℂ) = ⟪Ω₁, π₁ a Ω₁⟫_ℂ)
    (hcyc₂ : Physicslib4.GNS.IsCyclicVector π₂ Ω₂)
    (hrep₂ : ∀ b : N.quasilocal.carrier, (ω b : ℂ) = ⟪Ω₂, π₂ b Ω₂⟫_ℂ) :
    Physicslib4.GNS.UnitaryEquiv π₁ (π₂.comp (N.action L).toStarAlgHom) :=
  Physicslib4.GNS.unitaryEquiv_comp_of_gns (N.action L) ω π₁ Ω₁ hcyc₁ hrep₁ π₂ Ω₂ hcyc₂ hrep₂

/-- **Irreducibility is Lorentz invariant on the quasilocal algebra.** With the GNS data
above, `π₁` is irreducible exactly when `π₂` is. -/
theorem isIrreducible_iff_gns_action
    (hcyc₁ : Physicslib4.GNS.IsCyclicVector π₁ Ω₁)
    (hrep₁ : ∀ a : N.quasilocal.carrier,
      ((ω.comp (N.action L).toStarAlgHom) a : ℂ) = ⟪Ω₁, π₁ a Ω₁⟫_ℂ)
    (hcyc₂ : Physicslib4.GNS.IsCyclicVector π₂ Ω₂)
    (hrep₂ : ∀ b : N.quasilocal.carrier, (ω b : ℂ) = ⟪Ω₂, π₂ b Ω₂⟫_ℂ) :
    Physicslib4.GNS.IsIrreducible π₁ ↔ Physicslib4.GNS.IsIrreducible π₂ :=
  Physicslib4.GNS.isIrreducible_iff_of_gns_comp (N.action L) ω π₁ Ω₁ hcyc₁ hrep₁ π₂ Ω₂ hcyc₂ hrep₂

/-- **Factoriality is Lorentz invariant on the quasilocal algebra.** With the GNS data
above, `π₁(𝔘)''` is a factor exactly when `π₂(𝔘)''` is. So the superselection type of a
*global* state is a Lorentz invariant. -/
theorem isFactor_iff_gns_action
    (hcyc₁ : Physicslib4.GNS.IsCyclicVector π₁ Ω₁)
    (hrep₁ : ∀ a : N.quasilocal.carrier,
      ((ω.comp (N.action L).toStarAlgHom) a : ℂ) = ⟪Ω₁, π₁ a Ω₁⟫_ℂ)
    (hcyc₂ : Physicslib4.GNS.IsCyclicVector π₂ Ω₂)
    (hrep₂ : ∀ b : N.quasilocal.carrier, (ω b : ℂ) = ⟪Ω₂, π₂ b Ω₂⟫_ℂ) :
    IsFactor (Physicslib4.GNS.gnsVonNeumann π₁)
      ↔ IsFactor (Physicslib4.GNS.gnsVonNeumann π₂) :=
  Physicslib4.GNS.isFactor_iff_of_gns_comp (N.action L) ω π₁ Ω₁ hcyc₁ hrep₁ π₂ Ω₂ hcyc₂ hrep₂

end GNSCovariance

end HaagKastlerNet

end HaagKastler
end AQFT
end Physicslib4
