/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.AQFT.HaagKastler.Net
import Physicslib4.Spacetime.MinkowskiDirected

/-!
# Towards the intertwiner on the generated subalgebra

This file begins assembling the densely-defined intertwiner used to lift the
fiberwise covariance action to the quasilocal algebra (`QuasilocalLift`). Two
ingredients are established here:

* `IsAlexandrovBasisSet.directed`: the Haag-Kastler-level restatement of
  `Spacetime.alexandrovBasis_directed` (any two basis sets lie in a common
  basis set).
* `dense_adjoin_iUnion_range_ι`: the `*`-subalgebra of `𝔘` generated by the
  union of the local images `ι_B(𝔘(B))` is dense - so it is a valid domain for
  the dense-extension lemma `exists_starAlgHom_extend_of_dense`.

The remaining step - defining the intertwiner `ι_B a ↦ ι_{L·B}(α_L a)` on this
generated subalgebra and checking it is a well-defined `*`-homomorphism - will
use `StarAlgebra.adjoin_induction` together with the isotony-coherence field
`QuasilocalAlgebra.ι_inclusion` and basis directedness.
-/

namespace Physicslib4
namespace AQFT
namespace HaagKastler

open Physicslib4

/-- **Haag-Kastler directedness of the Alexandrov basis.** Any two
Alexandrov-basis sets are contained in a common Alexandrov-basis set. -/
theorem IsAlexandrovBasisSet.directed
    {B₁ B₂ : Set StandardMinkowskiSpacetime.Carrier}
    (h₁ : IsAlexandrovBasisSet B₁) (h₂ : IsAlexandrovBasisSet B₂) :
    ∃ B, IsAlexandrovBasisSet B ∧ B₁ ⊆ B ∧ B₂ ⊆ B :=
  Spacetime.alexandrovBasis_directed h₁ h₂

/-- The `*`-subalgebra of the quasilocal algebra generated by the union of all
local images is dense: it contains the (already dense) union of the images
`ι_B(𝔘(B))`. -/
theorem dense_adjoin_iUnion_range_ι {U : LocalNet} (Q : QuasilocalAlgebra U) :
    Dense (StarAlgebra.adjoin ℂ
      (⋃ (B : Set StandardMinkowskiSpacetime.Carrier) (_ : IsAlexandrovBasisSet B),
        Set.range (Q.ι B)) : Set Q.carrier) :=
  Q.dense_range.mono (StarAlgebra.subset_adjoin ℂ _)

end HaagKastler
end AQFT
end Physicslib4
