/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.Spacetime.Pullback
import Physicslib4.Spacetime.DiffeoPath
import Physicslib4.Spacetime.Curves
import Physicslib4.Spacetime.Causality
import Physicslib4.Spacetime.IsometryCausality
import Physicslib4.Spacetime.LorentzianSpacetime

/-!
# Cross-metric isometries

This file formalises the second half of the blueprint subsection *Pullback
metrics and cross-metric isometries* (section 10.5 of the AQFT-in-Lean
blueprint).

General covariance compares two *different* metrics on one carrier, related by
pulling back along a diffeomorphism, so the causal-transport statements of
`Physicslib4/Spacetime/IsometryCausality.lean` — which compare a spacetime with
itself — have to be redone cross-metric. This file supplies that geometry and
concludes with the pullback of a `LorentzianSpacetime`.

## Main definitions

* `Physicslib4.Spacetime.CrossIsometry` (`def:cross-metric-isometry`): a
  diffeomorphism `ψ` between the manifolds of two spacetimes with
  `ψ^*g₂ = g₁`. The single-metric `Spacetime.Isometry` is the case `N = M`.
* `Physicslib4.homeomorphOfGenerateFrom`
  (`lmm:bijection-generated-topology-homeomorphism`): a bijection matching two
  generating families is a homeomorphism for the generated topologies.
* `Physicslib4.Spacetime.LorentzianSpacetime.pullback`
  (`thrm:pullback-is-lorentzian-spacetime`).

## Modelling notes

The blueprint phrases these statements as "two metrics `g₁`, `g₂` on the same
manifold `M`". Formally they are stated here for two `Spacetime` structures
`M`, `N` and a diffeomorphism `Diffeo M N` of the underlying manifolds — a
strict generalisation, and the one the type system supports without transport
along carrier equalities. The blueprint's situation is the instance
`M := M₀.pullback ψ`, `N := M₀`, whose carriers and models are *definitionally*
those of `M₀`; `Spacetime.pullbackDiffeo` performs that reading of `ψ`.
-/

namespace Physicslib4

/--
**Continuity for generated topologies, forward direction**
(`lmm:bijection-generated-topology-homeomorphism`, first half).

If every member of the generating family `T` of the target pulls back into the
generating family `S` of the source, then `f` is continuous for the two generated
topologies. This is `continuous_generateFrom_iff` together with
`TopologicalSpace.isOpen_generateFrom_of_mem`.

Note that `continuous_generateFrom_iff` writes only the *source* topology
explicitly, as an implicit variable, so it has to be instantiated by hand — at
the application sites below the source is the carrier of a spacetime, which
already carries its manifold topology as an instance, and letting that be
inferred yields a well-typed but wrong statement. That is exactly why the
statement here writes both topologies with `@`.
-/
theorem continuous_generateFrom_of_preimage_mem {X Y : Type*} (f : X → Y)
    {S : Set (Set X)} {T : Set (Set Y)} (hfT : ∀ t ∈ T, f ⁻¹' t ∈ S) :
    @Continuous X Y (TopologicalSpace.generateFrom S)
      (TopologicalSpace.generateFrom T) f := by
  exact (continuous_generateFrom_iff (t := TopologicalSpace.generateFrom S)
    (b := T) (f := f)).mpr (fun t ht =>
      TopologicalSpace.isOpen_generateFrom_of_mem (hfT t ht))

/--
**Continuity for generated topologies, inverse direction**
(`lmm:bijection-generated-topology-homeomorphism`, second half).

The same argument applied to `e.symm`, using that `e.symm ⁻¹' s = e '' s` because
`e` is a bijection; this is where the hypothesis `hfS` on *images* is spent.
-/
theorem continuous_symm_generateFrom_of_image_mem {X Y : Type*} (e : X ≃ Y)
    {S : Set (Set X)} {T : Set (Set Y)} (hfS : ∀ s ∈ S, e '' s ∈ T) :
    @Continuous Y X (TopologicalSpace.generateFrom T)
      (TopologicalSpace.generateFrom S) e.symm := by
  exact (continuous_generateFrom_iff (t := TopologicalSpace.generateFrom T)
    (b := S) (f := e.symm)).mpr (fun s hs =>
      (Equiv.image_eq_preimage_symm e s).symm ▸
        TopologicalSpace.isOpen_generateFrom_of_mem (hfS s hs))

/--
**A bijection matching generating families is a homeomorphism**
(`lmm:bijection-generated-topology-homeomorphism`).

If `e : X ≃ Y` is a bijection carrying the family `S` into `T` and pulling `T`
back into `S`, it is a homeomorphism for the topologies generated by `S` and
`T`. Purely topological, with no geometry involved: the two continuity
obligations are `continuous_generateFrom_of_preimage_mem` and
`continuous_symm_generateFrom_of_image_mem`.

The bijection is taken as a bundled `Equiv` rather than as a function together
with `Function.Bijective`, so that the inverse of the resulting homeomorphism is
the *given* inverse `e.symm` and not the choice-based `Function.surjInv`
produced by `Equiv.ofBijective`. Consumers such as
`Spacetime.pullbackAlexandrovHomeomorph` need to compute with that inverse.
-/
def homeomorphOfGenerateFrom {X Y : Type*} (e : X ≃ Y)
    (S : Set (Set X)) (T : Set (Set Y))
    (hfS : ∀ s ∈ S, e '' s ∈ T) (hfT : ∀ t ∈ T, e ⁻¹' t ∈ S) :
    @Homeomorph X Y (TopologicalSpace.generateFrom S)
      (TopologicalSpace.generateFrom T) :=
  @Homeomorph.mk X Y (TopologicalSpace.generateFrom S) (TopologicalSpace.generateFrom T)
    e (continuous_generateFrom_of_preimage_mem (e : X → Y) hfT)
    (continuous_symm_generateFrom_of_image_mem e hfS)

/-- The homeomorphism of `lmm:bijection-generated-topology-homeomorphism` is `e`
itself. -/
@[simp] theorem homeomorphOfGenerateFrom_apply {X Y : Type*} (e : X ≃ Y)
    (S : Set (Set X)) (T : Set (Set Y))
    (hfS : ∀ s ∈ S, e '' s ∈ T) (hfT : ∀ t ∈ T, e ⁻¹' t ∈ S) :
    ⇑(homeomorphOfGenerateFrom e S T hfS hfT) = e := rfl

/-- The inverse of the homeomorphism of
`lmm:bijection-generated-topology-homeomorphism` is `e.symm`. -/
@[simp] theorem homeomorphOfGenerateFrom_symm_apply {X Y : Type*} (e : X ≃ Y)
    (S : Set (Set X)) (T : Set (Set Y))
    (hfS : ∀ s ∈ S, e '' s ∈ T) (hfT : ∀ t ∈ T, e ⁻¹' t ∈ S) :
    ⇑(@Homeomorph.symm X Y (TopologicalSpace.generateFrom S)
        (TopologicalSpace.generateFrom T) (homeomorphOfGenerateFrom e S T hfS hfT))
      = e.symm := rfl

namespace Spacetime

open scoped Manifold Pointwise

variable {M N : Spacetime}

/-! ### Isometries between two metrics -/

/--
**Isometry between two metrics on one manifold** (`def:cross-metric-isometry`).

A `C^∞` diffeomorphism `ψ` from the manifold of `M` to that of `N` is an
*isometry from `(M, g₁)` to `(N, g₂)`* when `ψ^*g₂ = g₁`, that is when
`g₂(dψ_x v, dψ_x w) = g₁(v, w)` for every `x` and all `v, w ∈ T_xM`.

The usual single-metric notion — `Spacetime.Isometry M` — is exactly the case
`N = M`, and `ψ` is *tautologically* an isometry from `M.pullback ψ` to `M`; see
`pullbackCrossIsometry`.
-/
@[ext]
structure CrossIsometry (M N : Spacetime) where
  /-- The underlying `C^∞` diffeomorphism of the two underlying manifolds. -/
  toDiffeo : Diffeo M N
  /-- Cross-metric preservation: `g₂(dψ_x v, dψ_x w) = g₁(v, w)`. -/
  preserves : ∀ (x : M.Carrier) (v w : TangentSpace M.model x),
    N.val (toDiffeo x)
      (mfderiv M.model N.model toDiffeo x v)
      (mfderiv M.model N.model toDiffeo x w)
    = M.val x v w

/-- `ψ` is tautologically an isometry from the pullback spacetime `ψ^*(M,g)` to
`(M,g)`: the defining equation reads `ψ^*g = ψ^*g`. -/
noncomputable def pullbackCrossIsometry (M : Spacetime) (ψ : Diffeo M M) :
    CrossIsometry (M.pullback ψ) M where
  toDiffeo := M.pullbackDiffeo ψ
  preserves := fun x v w => (M.pullbackVal_apply ψ x v w).symm

/-- A single-metric `Spacetime.Isometry` is the case `N = M` of a cross-metric
isometry (`def:cross-metric-isometry`): its defining equation is literally the
`preserves` field of `CrossIsometry M M`.

The bridge points from the special case to the general one, so it cannot be used
in the other direction: it does **not** let the already-proved single-metric
statements of `Physicslib4/Spacetime/Isometry.lean` and
`Physicslib4/Spacetime/IsometryCausality.lean` discharge the cross-metric results
below (`CrossIsometry.preserves_self`, `CrossIsometry.isTimelike_mfderiv_iff` and
the chronology family), which are genuinely more general and have to be proved
in that generality. What the bridge does give is the converse traffic: once
proved, the cross-metric results *specialise back* to isometries by instantiating
`Ψ := g.toCrossIsometry`, so the single-metric statements need never be reproved
cross-metric. The genuinely metric-free ingredients, where duplication *is*
avoidable and avoided, are factored out instead into
`Physicslib4/Spacetime/Diffeo.lean` and
`Physicslib4/Spacetime/DiffeoPath.lean`. -/
def Isometry.toCrossIsometry {M : Spacetime} (g : Isometry M) : CrossIsometry M M :=
  ⟨g.toDiffeo, g.preserves⟩

@[simp] theorem Isometry.toCrossIsometry_toDiffeo {M : Spacetime} (g : Isometry M) :
    g.toCrossIsometry.toDiffeo = g.toDiffeo := rfl

/-- The single-metric future-orientation condition of
`Physicslib4/Spacetime/IsometryCausality.lean` is the two-metric
`Spacetime.PreservesFutureOrientation` at `t₁ = t₂ = t`, so the cross-metric
transport lemmas below apply verbatim to isometries. -/
theorem Isometry.preservesFutureOrientation_iff {M : Spacetime} (g : Isometry M)
    (t : M.TimeOrientation) :
    g.PreservesFutureOrientation t
      ↔ Spacetime.PreservesFutureOrientation g.toDiffeo t t :=
  Iff.rfl

/--
**The inverse of a cross-metric isometry is a cross-metric isometry**
(`lmm:cross-metric-isometry-symm`), pointwise form:
`g₁(d(ψ⁻¹)_y u, d(ψ⁻¹)_y u') = g₂(u, u')`.

This is *not* the defining equation of `def:cross-metric-isometry` read
backwards — reading it backwards gives an equation about `dψ`, not about
`d(ψ⁻¹)` — and passing between the two is exactly `mfderiv_symm_cancel_left`.
-/
theorem CrossIsometry.symm_preserves (Ψ : CrossIsometry M N) (y : N.Carrier)
    (u u' : TangentSpace N.model y) :
    M.val (Ψ.toDiffeo.symm y)
        (mfderiv N.model M.model Ψ.toDiffeo.symm y u)
        (mfderiv N.model M.model Ψ.toDiffeo.symm y u')
      = N.val y u u' := by
  have hcancel (a : TangentSpace N.model y) :
      mfderiv M.model N.model Ψ.toDiffeo (Ψ.toDiffeo.symm y)
        (mfderiv N.model M.model Ψ.toDiffeo.symm y a) = a := by
    have hc := mfderiv_symm_cancel_left Ψ.toDiffeo (Ψ.toDiffeo.symm y) a
    rw [Ψ.toDiffeo.apply_symm_apply y] at hc
    exact hc
  have hpres := Ψ.preserves (Ψ.toDiffeo.symm y)
    (mfderiv N.model M.model Ψ.toDiffeo.symm y u)
    (mfderiv N.model M.model Ψ.toDiffeo.symm y u')
  rw [hcancel u, hcancel u'] at hpres
  rw [Ψ.toDiffeo.apply_symm_apply y] at hpres
  exact hpres.symm

/-- The inverse of a cross-metric isometry, as a cross-metric isometry in the
opposite direction (`lmm:cross-metric-isometry-symm`).

This is `noncomputable` of necessity, not by oversight: `Diffeomorph.symm` takes
the `NontriviallyNormedField ℝ` instance as an explicit argument, and on `ℝ` that
instance factors through the noncomputable `Real.denselyNormedField`, so the
compiler cannot generate code for `Ψ.toDiffeo.symm`. Contrast
`Isometry.toCrossIsometry`, which only repackages existing fields and so is
computable. -/
noncomputable def CrossIsometry.symm (Ψ : CrossIsometry M N) : CrossIsometry N M where
  toDiffeo := Ψ.toDiffeo.symm
  preserves := Ψ.symm_preserves

/-- **The metric square is preserved**
(`lmm:cross-metric-isometry-preserves-classification`, equation part). -/
theorem CrossIsometry.preserves_self (Ψ : CrossIsometry M N) (x : M.Carrier)
    (v : TangentSpace M.model x) :
    N.val (Ψ.toDiffeo x) (mfderiv M.model N.model Ψ.toDiffeo x v)
        (mfderiv M.model N.model Ψ.toDiffeo x v) = M.val x v v :=
  Ψ.preserves x v v

/-- A cross-metric isometry preserves timelikeness
(`lmm:cross-metric-isometry-preserves-classification`). The single-metric
`Isometry.isTimelike_mfderiv_iff` does *not* apply: source and target metrics
differ here. -/
theorem CrossIsometry.isTimelike_mfderiv_iff (Ψ : CrossIsometry M N) (x : M.Carrier)
    (v : TangentSpace M.model x) :
    N.IsTimelike (mfderiv M.model N.model Ψ.toDiffeo x v) ↔ M.IsTimelike v := by
  simp only [IsTimelike, Ψ.preserves_self]

/-- A cross-metric isometry preserves nullness
(`lmm:cross-metric-isometry-preserves-classification`). -/
theorem CrossIsometry.isNull_mfderiv_iff (Ψ : CrossIsometry M N) (x : M.Carrier)
    (v : TangentSpace M.model x) :
    N.IsNull (mfderiv M.model N.model Ψ.toDiffeo x v) ↔ M.IsNull v := by
  simp only [IsNull, Ψ.preserves_self]

/-- A cross-metric isometry preserves spacelikeness
(`lmm:cross-metric-isometry-preserves-classification`). -/
theorem CrossIsometry.isSpacelike_mfderiv_iff (Ψ : CrossIsometry M N) (x : M.Carrier)
    (v : TangentSpace M.model x) :
    N.IsSpacelike (mfderiv M.model N.model Ψ.toDiffeo x v) ↔ M.IsSpacelike v := by
  simp only [IsSpacelike, Ψ.preserves_self]

/-! ### Pushforward of a path

The pushforward `ψ ∘ μ` of a path, the chain rule for its tangent vector and the
transport of endpoints depend on the diffeomorphism only and not on either metric,
so they are not stated here at all: they live in
`Physicslib4/Spacetime/DiffeoPath.lean`, low enough in the import graph that the
single-metric `Isometry.pushforwardPath` is *defined* as an instance of them.
What remains here are the statements that genuinely consume metric preservation. -/

/-- **The pushforward preserves the timelike condition**
(`lmm:cross-metric-pushforward-path-causal`): if `μ` is timelike for `g₁` then
`ψ ∘ μ` is timelike for `g₂`. -/
theorem CrossIsometry.pushforwardPath_isTimelike (Ψ : CrossIsometry M N)
    (μ : M.SmoothPath) (h : SmoothPath.IsTimelike M μ) :
    SmoothPath.IsTimelike N (pushforwardPath Ψ.toDiffeo μ) := by
  intro s hs
  simp only [pushforwardPath_tangent Ψ.toDiffeo μ hs]
  exact (isTimelike_mfderiv_iff Ψ (μ.toFun s) (μ.tangent s)).mpr (h s hs)

/-- **The pushforward preserves the causal condition**
(`lmm:cross-metric-pushforward-path-causal`). -/
theorem CrossIsometry.pushforwardPath_isCausal (Ψ : CrossIsometry M N)
    (μ : M.SmoothPath) (h : SmoothPath.IsCausal M μ) :
    SmoothPath.IsCausal N (pushforwardPath Ψ.toDiffeo μ) := by
  intro s hs
  simp only [pushforwardPath_tangent Ψ.toDiffeo μ hs]
  rcases h s hs with ht | hn
  · exact Or.inl ((isTimelike_mfderiv_iff Ψ (μ.toFun s) (μ.tangent s)).mpr ht)
  · exact Or.inr ((isNull_mfderiv_iff Ψ (μ.toFun s) (μ.tangent s)).mpr hn)

/-- Under future-orientation preservation the pushforward of a future-oriented
path is future-oriented. -/
theorem pushforwardPath_isFutureOriented (ψ : Diffeo M N) (μ : M.SmoothPath)
    (t₁ : M.TimeOrientation) (t₂ : N.TimeOrientation)
    (hψ : PreservesFutureOrientation ψ t₁ t₂)
    (h : SmoothPath.IsFutureOriented M μ t₁) :
    SmoothPath.IsFutureOriented N (pushforwardPath ψ μ) t₂ := by
  intro s hs
  simp only [pushforwardPath_tangent ψ μ hs]
  exact hψ (μ.toFun s) _ (h s hs)

/-! ### Transport of chronology -/

section Geodesic

open Bundle VectorField Filter
open scoped Topology ContDiff

/-- The differential of a cross-metric isometry `Ψ` undoes the pullback of a vector field
along `Ψ`. -/
theorem CrossIsometry.mfderiv_mpullback (Ψ : CrossIsometry M N)
    (V : Π y : N.Carrier, TangentSpace N.model y) (x : M.Carrier) :
    mfderiv M.model N.model Ψ.toDiffeo x (mpullback M.model N.model Ψ.toDiffeo V x)
      = V (Ψ.toDiffeo x) := by
  rw [mpullback_apply,
    (Ψ.toDiffeo.isInvertible_mfderiv (x := x) (by simp)).self_apply_inverse]

/-- The `g₁`-pairing of pullbacks along a cross-metric isometry is the pullback of the
`g₂`-pairing. -/
theorem CrossIsometry.val_mpullback (Ψ : CrossIsometry M N)
    (V W : Π y : N.Carrier, TangentSpace N.model y) (x : M.Carrier) :
    M.toPseudoRiemannianMetric.val x (mpullback M.model N.model Ψ.toDiffeo V x)
        (mpullback M.model N.model Ψ.toDiffeo W x)
      = N.toPseudoRiemannianMetric.val (Ψ.toDiffeo x) (V (Ψ.toDiffeo x))
          (W (Ψ.toDiffeo x)) := by
  rw [← Ψ.mfderiv_mpullback V x, ← Ψ.mfderiv_mpullback W x]
  exact (Ψ.preserves x _ _).symm

/-- Chain rule for the metric pairing of vector fields pulled back along a cross-metric
isometry. -/
theorem CrossIsometry.mfderiv_val_mpullback (Ψ : CrossIsometry M N)
    {A B C : Π y : N.Carrier, TangentSpace N.model y} {x : M.Carrier}
    (hB : MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel)) (T% B) (Ψ.toDiffeo x))
    (hC : MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel)) (T% C) (Ψ.toDiffeo x)) :
    (show ℝ from mfderiv M.model 𝓘(ℝ, ℝ) (fun y ↦ M.toPseudoRiemannianMetric.val y
        (mpullback M.model N.model Ψ.toDiffeo B y) (mpullback M.model N.model Ψ.toDiffeo C y)) x
        (mpullback M.model N.model Ψ.toDiffeo A x))
      = (show ℝ from mfderiv N.model 𝓘(ℝ, ℝ)
          (fun z ↦ N.toPseudoRiemannianMetric.val z (B z) (C z)) (Ψ.toDiffeo x)
          (A (Ψ.toDiffeo x))) := by
  have hfun : (fun y ↦ M.toPseudoRiemannianMetric.val y
      (mpullback M.model N.model Ψ.toDiffeo B y) (mpullback M.model N.model Ψ.toDiffeo C y))
      = (fun z ↦ N.toPseudoRiemannianMetric.val z (B z) (C z)) ∘ Ψ.toDiffeo :=
    funext fun y ↦ Ψ.val_mpullback B C y
  rw [hfun]
  exact (congrArg (fun L ↦ L (mpullback M.model N.model Ψ.toDiffeo A x))
    (mfderiv_comp x (N.toPseudoRiemannianMetric.mdifferentiableAt_val_apply hB hC)
      (Ψ.toDiffeo.mdifferentiable (by simp) x))).trans
    (by rw [ContinuousLinearMap.comp_apply, Ψ.mfderiv_mpullback])

/-- Naturality of the Lie bracket under a cross-metric isometry, paired with the metric. -/
theorem CrossIsometry.val_mlieBracket_mpullback (Ψ : CrossIsometry M N)
    {A B C : Π y : N.Carrier, TangentSpace N.model y} {x : M.Carrier}
    (hA : MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel)) (T% A) (Ψ.toDiffeo x))
    (hC : MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel)) (T% C) (Ψ.toDiffeo x)) :
    M.toPseudoRiemannianMetric.val x (mpullback M.model N.model Ψ.toDiffeo B x)
        (mlieBracket M.model (mpullback M.model N.model Ψ.toDiffeo A)
          (mpullback M.model N.model Ψ.toDiffeo C) x)
      = N.toPseudoRiemannianMetric.val (Ψ.toDiffeo x) (B (Ψ.toDiffeo x))
          (mlieBracket N.model A C (Ψ.toDiffeo x)) := by
  have : IsManifold M.model (minSmoothness ℝ 2) M.Carrier := IsManifold.of_le (n := ∞) (by simp)
  have : IsManifold N.model (minSmoothness ℝ 2) N.Carrier := IsManifold.of_le (n := ∞) (by simp)
  rw [← mpullback_mlieBracket hA hC (Ψ.toDiffeo.contMDiff x) (by simp)]
  exact Ψ.val_mpullback B (mlieBracket N.model A C) x

/-- **A cross-metric isometry intertwines the Levi-Civita connections**:
`dΨ(∇¹_{Ψ^*A} Ψ^*B) = ∇²_A B ∘ Ψ`.

Blueprint reference: `lmm:isometry-preserves-levi-civita` (cross-metric case). -/
theorem CrossIsometry.mfderiv_leviCivita_mpullback (Ψ : CrossIsometry M N)
    {A B : Π y : N.Carrier, TangentSpace N.model y} {x : M.Carrier}
    (hA : MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel)) (T% A) (Ψ.toDiffeo x))
    (hB : MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel)) (T% B) (Ψ.toDiffeo x)) :
    mfderiv M.model N.model Ψ.toDiffeo x
        (M.toPseudoRiemannianMetric.leviCivita (mpullback M.model N.model Ψ.toDiffeo B) x
          (mpullback M.model N.model Ψ.toDiffeo A x))
      = N.toPseudoRiemannianMetric.leviCivita B (Ψ.toDiffeo x) (A (Ψ.toDiffeo x)) := by
  set L := M.toPseudoRiemannianMetric
  set L' := N.toPseudoRiemannianMetric
  have hpb : ∀ {V : Π y : N.Carrier, TangentSpace N.model y},
      MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel)) (T% V) (Ψ.toDiffeo x) →
      MDifferentiableAt M.model (M.model.prod 𝓘(ℝ, SpacetimeModel))
        (T% (mpullback M.model N.model Ψ.toDiffeo V)) x := fun hV ↦
    hV.mpullback_vectorField (Ψ.toDiffeo.contMDiff x)
      (Ψ.toDiffeo.isInvertible_mfderiv (by simp)) (by simp)
  apply L'.eq_of_forall_val_apply_eq
  intro C hC
  have h1 := L.isLeviCivitaFor_leviCivita.koszul (hpb hA) (hpb hB) (hpb hC)
  have h2 := L'.isLeviCivitaFor_leviCivita.koszul hA hB hC
  rw [Ψ.mfderiv_val_mpullback hB hC, Ψ.mfderiv_val_mpullback hC hA,
    Ψ.mfderiv_val_mpullback hA hB, Ψ.val_mlieBracket_mpullback hA hC,
    Ψ.val_mlieBracket_mpullback hB hA, Ψ.val_mlieBracket_mpullback hC hB] at h1
  have e : L'.val (Ψ.toDiffeo x) (mfderiv M.model N.model Ψ.toDiffeo x
      (L.leviCivita (mpullback M.model N.model Ψ.toDiffeo B) x
        (mpullback M.model N.model Ψ.toDiffeo A x))) (C (Ψ.toDiffeo x))
      = L.val x (L.leviCivita (mpullback M.model N.model Ψ.toDiffeo B) x
        (mpullback M.model N.model Ψ.toDiffeo A x))
          (mpullback M.model N.model Ψ.toDiffeo C x) := by
    rw [← Ψ.mfderiv_mpullback C x]
    exact Ψ.preserves x _ _
  rw [e]
  linarith

/-- **Cross-metric isometries map geodesics to geodesics.** A cross-metric isometry
`Ψ : (M, g₁) → (N, g₂)` carries the Levi-Civita connection of `g₁` to that of `g₂`, so the
pushforward of a geodesic of `M` is a geodesic of `N`. This is the cross-metric version of
`Isometry.pushforwardPath_isGeodesic`.

Blueprint reference: `lmm:isometry-preserves-geodesics` (cross-metric case). -/
theorem CrossIsometry.pushforwardPath_isGeodesic (Ψ : CrossIsometry M N) (μ : M.SmoothPath)
    (h : IsGeodesic M μ) : IsGeodesic N (pushforwardPath Ψ.toDiffeo μ) := by
  intro s hs X hX hXt
  have hinv (y : M.Carrier) : (mfderiv M.model N.model Ψ.toDiffeo y).IsInvertible :=
    Ψ.toDiffeo.isInvertible_mfderiv (by simp)
  have hY : ContMDiff M.model (M.model.prod 𝓘(ℝ, SpacetimeModel)) ∞
      (T% (mpullback M.model N.model Ψ.toDiffeo X)) :=
    hX.mpullback_vectorField Ψ.toDiffeo.contMDiff hinv (by simp)
  have hYt : ∀ᶠ t in 𝓝 s,
      mpullback M.model N.model Ψ.toDiffeo X (μ.toFun t) = μ.tangent t := by
    filter_upwards [hXt, mem_interior_iff_mem_nhds.mp hs] with t ht htP
    rw [mpullback_apply]
    change X (Ψ.toDiffeo (μ.toFun t)) = _ at ht
    rw [ht, pushforwardPath_tangent Ψ.toDiffeo μ htP, (hinv _).inverse_apply_self]
  have hXd : MDifferentiableAt N.model (N.model.prod 𝓘(ℝ, SpacetimeModel))
      (T% X) (Ψ.toDiffeo (μ.toFun s)) :=
    (hX _).mdifferentiableAt (by simp)
  change N.toPseudoRiemannianMetric.leviCivita X (Ψ.toDiffeo (μ.toFun s))
    (X (Ψ.toDiffeo (μ.toFun s))) = 0
  rw [← Ψ.mfderiv_leviCivita_mpullback hXd hXd, h s hs _ hY hYt, map_zero]

end Geodesic

/-- A cross-metric isometry preserving the future orientation carries a single
trip segment forward. -/
theorem CrossIsometry.segmentPrecedes (Ψ : CrossIsometry M N)
    (t₁ : M.TimeOrientation) (t₂ : N.TimeOrientation)
    (hΨ : PreservesFutureOrientation Ψ.toDiffeo t₁ t₂) {p q : M.Carrier}
    (h : SegmentPrecedes M t₁ p q) :
    SegmentPrecedes N t₂ (Ψ.toDiffeo p) (Ψ.toDiffeo q) := by
  obtain ⟨c, rep, hc, htl, hfo, hgeo, hpe, hfe⟩ := h
  exact ⟨SmoothCurve.ofPath N (pushforwardPath Ψ.toDiffeo rep), pushforwardPath Ψ.toDiffeo rep, rfl,
    Ψ.pushforwardPath_isTimelike rep htl,
    pushforwardPath_isFutureOriented Ψ.toDiffeo rep t₁ t₂ hΨ hfo,
    Ψ.pushforwardPath_isGeodesic rep hgeo,
    pushforwardPath_isPastEndpoint Ψ.toDiffeo rep hpe,
    pushforwardPath_isFutureEndpoint Ψ.toDiffeo rep hfe⟩

/--
**Cross-metric isometries transport chronological precedence**
(`lmm:cross-metric-isometry-preserves-chronology`): `p ≪₁ q` implies
`ψ p ≪₂ ψ q`. A trip is a finite chain of trip segments, so this lifts
`CrossIsometry.segmentPrecedes` along the transitive closure
(`Relation.TransGen.lift`).
-/
theorem CrossIsometry.chronologicallyPrecedes (Ψ : CrossIsometry M N)
    (t₁ : M.TimeOrientation) (t₂ : N.TimeOrientation)
    (hΨ : PreservesFutureOrientation Ψ.toDiffeo t₁ t₂) {p q : M.Carrier}
    (h : ChronologicallyPrecedes M t₁ p q) :
    ChronologicallyPrecedes N t₂ (Ψ.toDiffeo p) (Ψ.toDiffeo q) := by
  exact Relation.TransGen.lift (f := Ψ.toDiffeo)
    (r := Spacetime.SegmentPrecedes M t₁) (p := Spacetime.SegmentPrecedes N t₂)
    (fun a b hs => segmentPrecedes Ψ t₁ t₂ hΨ hs) _ _ h

/--
**Image of the chronological future**
(`lmm:cross-metric-chronological-future-image`): `ψ(I⁺₁(p)) = I⁺₂(ψ p)`.

The `⊆` half is `CrossIsometry.chronologicallyPrecedes`; the `⊇` half applies the
same lemma to `ψ⁻¹`, which is a cross-metric isometry in the opposite direction
by `CrossIsometry.symm` and preserves the future orientation by the second half
of the two-sided hypothesis.
-/
theorem CrossIsometry.chronologicalFuture_image (Ψ : CrossIsometry M N)
    (t₁ : M.TimeOrientation) (t₂ : N.TimeOrientation)
    (hΨ : PreservesFutureOrientationTwoSided Ψ.toDiffeo t₁ t₂) (p : M.Carrier) :
    (Ψ.toDiffeo : M.Carrier → N.Carrier) '' chronologicalFuture M t₁ p
      = chronologicalFuture N t₂ (Ψ.toDiffeo p) := by
  refine Set.Subset.antisymm ?_ ?_
  · rintro _ ⟨q, hq, rfl⟩
    exact CrossIsometry.chronologicallyPrecedes Ψ t₁ t₂ hΨ.1 hq
  · intro r hr
    have hstep : ChronologicallyPrecedes M t₁ p (Ψ.symm.toDiffeo r) := by
      simpa [CrossIsometry.symm] using
        (CrossIsometry.chronologicallyPrecedes Ψ.symm t₂ t₁ hΨ.2 hr)
    exact ⟨Ψ.symm.toDiffeo r, hstep, by simp [CrossIsometry.symm]⟩

/-- **Image of the chronological past**
(`lmm:cross-metric-chronological-past-image`): `ψ(I⁻₁(p)) = I⁻₂(ψ p)`. -/
theorem CrossIsometry.chronologicalPast_image (Ψ : CrossIsometry M N)
    (t₁ : M.TimeOrientation) (t₂ : N.TimeOrientation)
    (hΨ : PreservesFutureOrientationTwoSided Ψ.toDiffeo t₁ t₂) (p : M.Carrier) :
    (Ψ.toDiffeo : M.Carrier → N.Carrier) '' chronologicalPast M t₁ p
      = chronologicalPast N t₂ (Ψ.toDiffeo p) := by
  refine Set.Subset.antisymm ?_ ?_
  · rintro _ ⟨q, hq, rfl⟩
    exact CrossIsometry.chronologicallyPrecedes Ψ t₁ t₂ hΨ.1 hq
  · intro r hr
    have hstep : ChronologicallyPrecedes M t₁ (Ψ.symm.toDiffeo r) p := by
      simpa [CrossIsometry.symm] using
        (CrossIsometry.chronologicallyPrecedes Ψ.symm t₂ t₁ hΨ.2 hr)
    exact ⟨Ψ.symm.toDiffeo r, hstep, by simp [CrossIsometry.symm]⟩

/--
**Cross-metric isometries preserve basis sets**
(`lmm:cross-metric-isometry-preserves-basis-sets`), diamond form:
`ψ(I⁺₁(p) ∩ I⁻₁(q)) = I⁺₂(ψ p) ∩ I⁻₂(ψ q)`.

The image of an intersection under an injective map is the intersection of the
images, and the two factors are `CrossIsometry.chronologicalFuture_image` and
`CrossIsometry.chronologicalPast_image`.
-/
theorem CrossIsometry.alexandrovDiamond_image (Ψ : CrossIsometry M N)
    (t₁ : M.TimeOrientation) (t₂ : N.TimeOrientation)
    (hΨ : PreservesFutureOrientationTwoSided Ψ.toDiffeo t₁ t₂) (p q : M.Carrier) :
    (Ψ.toDiffeo : M.Carrier → N.Carrier) ''
        (chronologicalFuture M t₁ p ∩ chronologicalPast M t₁ q)
      = chronologicalFuture N t₂ (Ψ.toDiffeo p) ∩ chronologicalPast N t₂ (Ψ.toDiffeo q) := by
  have hinj : Function.Injective (Ψ.toDiffeo : M.Carrier → N.Carrier) :=
    Ψ.toDiffeo.injective
  rw [Set.image_inter hinj, chronologicalFuture_image Ψ t₁ t₂ hΨ p,
    chronologicalPast_image Ψ t₁ t₂ hΨ q]

/-- **Cross-metric isometries preserve basis sets**
(`lmm:cross-metric-isometry-preserves-basis-sets`), membership form. -/
theorem CrossIsometry.alexandrovBasis_image (Ψ : CrossIsometry M N)
    (t₁ : M.TimeOrientation) (t₂ : N.TimeOrientation)
    (hΨ : PreservesFutureOrientationTwoSided Ψ.toDiffeo t₁ t₂)
    {B : Set M.Carrier} (hB : B ∈ alexandrovBasis M t₁) :
    (Ψ.toDiffeo : M.Carrier → N.Carrier) '' B ∈ alexandrovBasis N t₂ := by
  obtain ⟨p, q, rfl⟩ := hB
  refine ⟨Ψ.toDiffeo p, Ψ.toDiffeo q, ?_⟩
  exact alexandrovDiamond_image Ψ t₁ t₂ hΨ p q

/-! ### The pullback Alexandrov topology -/

/-- **`ψ` carries pullback Alexandrov basis sets to Alexandrov basis sets**
(`lmm:pullback-alexandrov-homeomorphism`, forward matching hypothesis).

This is `CrossIsometry.alexandrovBasis_image` applied to `pullbackCrossIsometry`,
whose two-sided orientation hypothesis is
`pullback_preservesFutureOrientationTwoSided`. -/
theorem pullback_alexandrovBasis_image (M : Spacetime) (ψ : Diffeo M M)
    (t : M.TimeOrientation) {B : Set (M.pullback ψ).Carrier}
    (hB : B ∈ alexandrovBasis (M.pullback ψ) (M.pullbackTimeOrientation ψ t)) :
    ((M.pullbackDiffeo ψ).toEquiv : (M.pullback ψ).Carrier → M.Carrier) '' B
      ∈ alexandrovBasis M t := by
  change ((M.pullbackDiffeo ψ : (M.pullback ψ).Carrier → M.Carrier)) '' B
    ∈ alexandrovBasis M t
  exact CrossIsometry.alexandrovBasis_image (pullbackCrossIsometry M ψ)
    (M.pullbackTimeOrientation ψ t) t
    (pullback_preservesFutureOrientationTwoSided M ψ t) hB

set_option backward.isDefEq.respectTransparency false in
/-- **`ψ⁻¹` carries Alexandrov basis sets to pullback Alexandrov basis sets**
(`lmm:pullback-alexandrov-homeomorphism`, backward matching hypothesis).

This is `CrossIsometry.alexandrovBasis_image` applied to
`(pullbackCrossIsometry M ψ).symm` together with the second half of
`pullback_preservesFutureOrientationTwoSided`, the preimage under `ψ` being the
image under `ψ⁻¹`. -/
theorem pullback_alexandrovBasis_preimage (M : Spacetime) (ψ : Diffeo M M)
    (t : M.TimeOrientation) {B : Set M.Carrier}
    (hB : B ∈ alexandrovBasis M t) :
    ((M.pullbackDiffeo ψ).toEquiv : (M.pullback ψ).Carrier → M.Carrier) ⁻¹' B
      ∈ alexandrovBasis (M.pullback ψ) (M.pullbackTimeOrientation ψ t) := by
  rw [← Equiv.image_symm_eq_preimage (M.pullbackDiffeo ψ).toEquiv B]
  have hΨ : PreservesFutureOrientationTwoSided (pullbackCrossIsometry M ψ).symm.toDiffeo
      t (M.pullbackTimeOrientation ψ t) := by
    simpa [pullbackCrossIsometry, CrossIsometry.symm] using
      (show PreservesFutureOrientationTwoSided (M.pullbackDiffeo ψ).symm
          t (M.pullbackTimeOrientation ψ t) from
        ⟨(pullback_preservesFutureOrientationTwoSided M ψ t).2,
          by
            change PreservesFutureOrientation (M.pullbackDiffeo ψ)
              (M.pullbackTimeOrientation ψ t) t
            exact (pullback_preservesFutureOrientationTwoSided M ψ t).1⟩)
  change (((M.pullbackDiffeo ψ).symm : M.Carrier → (M.pullback ψ).Carrier)) '' B
    ∈ alexandrovBasis (M.pullback ψ) (M.pullbackTimeOrientation ψ t)
  exact CrossIsometry.alexandrovBasis_image (pullbackCrossIsometry M ψ).symm
    t (M.pullbackTimeOrientation ψ t) hΨ hB

/--
**The pullback Alexandrov topology** (`lmm:pullback-alexandrov-homeomorphism`).

`ψ` is a homeomorphism from `ψ^*(M,g)` carrying the Alexandrov topology of
`ψ^*g` and `ψ^*t` to `(M,g)` carrying the Alexandrov topology of `g` and `t`.
This is `homeomorphOfGenerateFrom` applied to the two families of Alexandrov
diamonds, whose matching-up is `pullback_alexandrovBasis_image` and
`pullback_alexandrovBasis_preimage`; the proof of this node is pure citation and
introduces no obligation of its own.
-/
noncomputable def pullbackAlexandrovHomeomorph (M : Spacetime) (ψ : Diffeo M M)
    (t : M.TimeOrientation) :
    @Homeomorph (M.pullback ψ).Carrier M.Carrier
      (alexandrovTopology (M.pullback ψ) (M.pullbackTimeOrientation ψ t))
      (alexandrovTopology M t) :=
  homeomorphOfGenerateFrom (M.pullbackDiffeo ψ).toEquiv
    (alexandrovBasis (M.pullback ψ) (M.pullbackTimeOrientation ψ t))
    (alexandrovBasis M t)
    (fun _ hs => pullback_alexandrovBasis_image M ψ t hs)
    (fun _ ht => pullback_alexandrovBasis_preimage M ψ t ht)

/-- The homeomorphism of `lmm:pullback-alexandrov-homeomorphism` is `ψ` itself. -/
@[simp] theorem pullbackAlexandrovHomeomorph_apply (M : Spacetime) (ψ : Diffeo M M)
    (t : M.TimeOrientation) :
    ⇑(pullbackAlexandrovHomeomorph M ψ t) = ψ := rfl

/-- **The pullback Alexandrov topology is Hausdorff**
(`thrm:pullback-is-lorentzian-spacetime`, the only obligation of that node).

It transports from the Hausdorffness of the Alexandrov topology of `(M,g,t)`
along `pullbackAlexandrovHomeomorph` by `Homeomorph.t2Space`. -/
theorem LorentzianSpacetime.pullback_alexandrov_t2 (L : LorentzianSpacetime)
    (ψ : Diffeo L.toSpacetime L.toSpacetime) :
    @T2Space (L.toSpacetime.pullback ψ).Carrier
      (alexandrovTopology (L.toSpacetime.pullback ψ)
        (L.toSpacetime.pullbackTimeOrientation ψ L.timeOrientation)) := by
  letI tP : TopologicalSpace (L.toSpacetime.pullback ψ).Carrier :=
    alexandrovTopology (L.toSpacetime.pullback ψ)
      (L.toSpacetime.pullbackTimeOrientation ψ L.timeOrientation)
  letI tC : TopologicalSpace L.toSpacetime.Carrier :=
    alexandrovTopology L.toSpacetime L.timeOrientation
  haveI : T2Space L.toSpacetime.Carrier := L.alexandrov_t2
  exact (pullbackAlexandrovHomeomorph L.toSpacetime ψ L.timeOrientation).symm.t2Space

/--
**The pullback of a Lorentzian spacetime is a Lorentzian spacetime**
(`thrm:pullback-is-lorentzian-spacetime`).

The underlying spacetime is `Spacetime.pullback`, the time orientation is
`Spacetime.pullbackTimeOrientation` and the Hausdorff condition on the Alexandrov
topology is `LorentzianSpacetime.pullback_alexandrov_t2`.

This is what makes "the net over `ψ^*(M,g)`" meaningful in
`def:general-covariance-in-curved-spacetime`.
-/
noncomputable def LorentzianSpacetime.pullback (L : LorentzianSpacetime)
    (ψ : Diffeo L.toSpacetime L.toSpacetime) : LorentzianSpacetime where
  toSpacetime := L.toSpacetime.pullback ψ
  timeOrientation := L.toSpacetime.pullbackTimeOrientation ψ L.timeOrientation
  alexandrov_t2 := L.pullback_alexandrov_t2 ψ

@[simp] theorem LorentzianSpacetime.pullback_toSpacetime (L : LorentzianSpacetime)
    (ψ : Diffeo L.toSpacetime L.toSpacetime) :
    (L.pullback ψ).toSpacetime = L.toSpacetime.pullback ψ := rfl

@[simp] theorem LorentzianSpacetime.pullback_timeOrientation (L : LorentzianSpacetime)
    (ψ : Diffeo L.toSpacetime L.toSpacetime) :
    (L.pullback ψ).timeOrientation
      = L.toSpacetime.pullbackTimeOrientation ψ L.timeOrientation := rfl

end Spacetime

end Physicslib4
