/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.Spacetime.Causality
import Mathlib.Topology.Separation.Hausdorff
import Mathlib.Topology.Bases

/-!
# Lorentzian spacetime

This file formalises the blueprint declaration `def:lorentzian-spacetime`
(Chapter 10, `sections/sec10/10-2_spacetime`, of the AQFT-in-Lean blueprint;
the notion is also discussed expositorily in the Chapter 9 prologue):

> A *Lorentzian spacetime* is a smooth, connected, four-dimensional
> manifold equipped with a smooth, nowhere-vanishing global vector
> field `tᵃ` and associated Lorentzian metric. In addition it is
> equipped with an associated Hausdorff Alexandrov topology.

## Main definitions

* `Physicslib4.Spacetime.LorentzianSpacetime`: the bundled
  curved-spacetime object (`def:lorentzian-spacetime`, Chapter 10).

## Modelling notes

The three ingredients of the blueprint definition are already
available individually in this development, so the bundle simply
records them together:

* the smooth, connected, four-dimensional Hausdorff manifold with its
  smooth, non-degenerate, symmetric Lorentzian `(0,2)` metric is the
  existing `Physicslib4.Spacetime` structure (`def:spacetime`);
* the smooth, nowhere-vanishing global timelike vector field `tᵃ` is a
  `Physicslib4.Spacetime.TimeOrientation` on that spacetime
  (`field` + `nonvanishing` + `timelike_at` + `smooth`);
* the *Hausdorff Alexandrov topology* assumption is the field
  `alexandrov_t2`, asserting that the Alexandrov topology
  `alexandrovTopology toSpacetime timeOrientation` — generated by the
  diamonds `I⁺(p) ∩ I⁻(q)` — is `T2`.

By the blueprint's "Properties of the Alexandrov Topology" theorem the
Hausdorff-Alexandrov assumption is equivalent to strong causality and
to the agreement of the Alexandrov and manifold topologies; we take the
Hausdorff form as the primitive assumption, exactly as the Chapter 9 prologue
does.

This bundle is the concrete object intended to instantiate the abstract
`Physicslib4.AQFT.HaagKastlerCurved.LorentzianSpacetime` interface over
which Axioms 1-5 are stated. The remaining ingredient for that bridge
is the identity-component isometry group of the spacetime (used by
Axiom 5), which is developed separately.
-/

namespace Physicslib4

namespace Spacetime

/--
**Lorentzian spacetime** (blueprint `def:lorentzian-spacetime`).

A smooth, connected, four-dimensional Hausdorff manifold with a smooth
non-degenerate symmetric Lorentzian metric (`toSpacetime`), equipped
with a smooth nowhere-vanishing global timelike vector field
(`timeOrientation`) and an associated *Hausdorff* Alexandrov topology
(`alexandrov_t2`).

This is the geometric bundle; `LorentzianSpacetime.toAbstract` exposes
it as the axiom-facing interface
`Physicslib4.AQFT.HaagKastlerCurved.LorentzianSpacetime` over which the
curved Haag-Kastler axioms are stated.

Blueprint reference: `def:lorentzian-spacetime`.
-/
structure LorentzianSpacetime where
  /-- The underlying spacetime: a 4D connected smooth Hausdorff
  manifold with a smooth non-degenerate symmetric Lorentzian metric
  (`def:spacetime`). -/
  toSpacetime : Spacetime
  /-- The smooth, nowhere-vanishing, everywhere-timelike global vector
  field `tᵃ` orienting time. -/
  timeOrientation : toSpacetime.TimeOrientation
  /-- The associated Alexandrov topology (generated by the diamonds
  `I⁺(p) ∩ I⁻(q)`) is Hausdorff. By the Alexandrov-topology theorem
  this is equivalent to strong causality and to the Alexandrov topology
  agreeing with the manifold topology. -/
  alexandrov_t2 :
    @T2Space toSpacetime.Carrier
      (alexandrovTopology toSpacetime timeOrientation)

namespace LorentzianSpacetime

variable (M : LorentzianSpacetime)

/-- The points of the Lorentzian spacetime. -/
abbrev Carrier : Type _ := M.toSpacetime.Carrier

/-- The Alexandrov-basis sets `I⁺(p) ∩ I⁻(q)` of the Lorentzian
spacetime, as a predicate on subsets of the carrier. -/
def IsBasisSet (B : Set M.Carrier) : Prop :=
  B ∈ alexandrovBasis M.toSpacetime M.timeOrientation

/-- Complete spacelike separation of two regions, with respect to the
spacetime's time orientation (used by Axiom 3). -/
def IsCompletelySpacelike (O₁ O₂ : Set M.Carrier) : Prop :=
  Spacetime.IsCompletelySpacelike M.toSpacetime M.timeOrientation O₁ O₂

/-- The Alexandrov topology of the Lorentzian spacetime is Hausdorff,
re-exposed from the structure field as a `T2Space` instance on the
carrier with the Alexandrov topology. -/
instance instT2SpaceAlexandrov :
    @T2Space M.Carrier (alexandrovTopology M.toSpacetime M.timeOrientation) :=
  M.alexandrov_t2

/-- Complete spacelike separation of two regions is symmetric. -/
theorem isCompletelySpacelike_comm {O₁ O₂ : Set M.Carrier} :
    M.IsCompletelySpacelike O₁ O₂ ↔ M.IsCompletelySpacelike O₂ O₁ :=
  Spacetime.isCompletelySpacelike_comm M.toSpacetime M.timeOrientation

/-- Complete spacelike separation is monotone under shrinking either region. -/
theorem isCompletelySpacelike_mono {O₁ O₁' O₂ O₂' : Set M.Carrier}
    (h₁ : O₁' ⊆ O₁) (h₂ : O₂' ⊆ O₂) (h : M.IsCompletelySpacelike O₁ O₂) :
    M.IsCompletelySpacelike O₁' O₂' :=
  Spacetime.isCompletelySpacelike_mono M.toSpacetime M.timeOrientation h₁ h₂ h

@[simp] theorem isCompletelySpacelike_empty_left (O : Set M.Carrier) :
    M.IsCompletelySpacelike ∅ O :=
  Spacetime.isCompletelySpacelike_empty_left M.toSpacetime M.timeOrientation O

@[simp] theorem isCompletelySpacelike_empty_right (O : Set M.Carrier) :
    M.IsCompletelySpacelike O ∅ :=
  Spacetime.isCompletelySpacelike_empty_right M.toSpacetime M.timeOrientation O

/-- A union of regions is completely spacelike to `O₂` iff each part is. -/
theorem isCompletelySpacelike_union_left (O₁ O₁' O₂ : Set M.Carrier) :
    M.IsCompletelySpacelike (O₁ ∪ O₁') O₂ ↔
      M.IsCompletelySpacelike O₁ O₂ ∧ M.IsCompletelySpacelike O₁' O₂ :=
  Spacetime.isCompletelySpacelike_union_left M.toSpacetime M.timeOrientation O₁ O₁' O₂

/-- `O₁` is completely spacelike to a union iff it is to each part. -/
theorem isCompletelySpacelike_union_right (O₁ O₂ O₂' : Set M.Carrier) :
    M.IsCompletelySpacelike O₁ (O₂ ∪ O₂') ↔
      M.IsCompletelySpacelike O₁ O₂ ∧ M.IsCompletelySpacelike O₁ O₂' :=
  Spacetime.isCompletelySpacelike_union_right M.toSpacetime M.timeOrientation O₁ O₂ O₂'

/-- Every Alexandrov-basis set `I⁺(p) ∩ I⁻(q)` is open in the Alexandrov
topology of the Lorentzian spacetime. -/
theorem isOpen_alexandrov_of_isBasisSet {B : Set M.Carrier}
    (hB : M.IsBasisSet B) :
    @IsOpen M.Carrier (alexandrovTopology M.toSpacetime M.timeOrientation) B :=
  Spacetime.isOpen_alexandrov_of_mem_basis M.toSpacetime M.timeOrientation hB

/-! ### The Alexandrov diamonds as a genuine topological basis -/

/-- **Covering from the Hausdorff assumption.** On a Lorentzian spacetime with at
least two points, the Alexandrov diamonds cover the whole space: every point lies in
some diamond `I⁺(p) ∩ I⁻(q)`. A point in no diamond would have `univ` as its only
Alexandrov-open neighbourhood, contradicting Hausdorffness. -/
theorem sUnion_alexandrovBasis_eq_univ [Nontrivial M.Carrier] :
    ⋃₀ (alexandrovBasis M.toSpacetime M.timeOrientation) = Set.univ := by
  rw [Set.eq_univ_iff_forall]
  intro x
  by_contra hx
  -- hx : x ∉ ⋃₀ (alexandrovBasis ...) means every basis set misses x
  have hx' : ∀ s ∈ alexandrovBasis M.toSpacetime M.timeOrientation, x ∉ s :=
    fun s hs hxs => hx ⟨s, hs, hxs⟩
  -- Key: any Alexandrov-open set containing x must be the whole space.
  have key : ∀ (U : Set M.Carrier),
      TopologicalSpace.GenerateOpen (alexandrovBasis M.toSpacetime M.timeOrientation) U →
      x ∈ U → U = Set.univ := by
    intro U hU hxU
    induction hU with
    | basic s hs => exact absurd hxU (hx' s hs)
    | univ => rfl
    | inter s t hs ht ihs iht => rw [ihs hxU.1, iht hxU.2, Set.inter_univ]
    | sUnion G hG ih =>
      obtain ⟨g, hgG, hxg⟩ := hxU
      exact Set.univ_subset_iff.mp (ih g hgG hxg ▸ Set.subset_sUnion_of_mem hgG)
  -- Choose a second point y ≠ x (the space is nontrivial); T₂ separation gives
  -- disjoint open sets around x and y, but the one around x is forced to be `univ`.
  obtain ⟨y, hy⟩ := exists_ne x
  obtain ⟨U, V, hUo, _, hxU, hyV, hdisj⟩ :=
    @t2_separation M.Carrier (alexandrovTopology M.toSpacetime M.timeOrientation)
      M.instT2SpaceAlexandrov x y (Ne.symm hy)
  exact Set.disjoint_left.mp hdisj ((key U hUo hxU).ge (Set.mem_univ y)) hyV

/-- **The Alexandrov diamonds form a topological basis.** On a Lorentzian spacetime
with at least two points, if the diamonds are downward-directed (the intersection
property), they form a genuine `IsTopologicalBasis` for the Alexandrov topology. The
covering condition is `sUnion_alexandrovBasis_eq_univ`; the generation condition is
definitional. -/
theorem isTopologicalBasis_alexandrovBasis [Nontrivial M.Carrier]
    (hdir : ∀ B₁ ∈ alexandrovBasis M.toSpacetime M.timeOrientation,
      ∀ B₂ ∈ alexandrovBasis M.toSpacetime M.timeOrientation,
      ∀ x ∈ B₁ ∩ B₂, ∃ B₃ ∈ alexandrovBasis M.toSpacetime M.timeOrientation,
        x ∈ B₃ ∧ B₃ ⊆ B₁ ∩ B₂) :
    @TopologicalSpace.IsTopologicalBasis M.Carrier
      (alexandrovTopology M.toSpacetime M.timeOrientation)
      (alexandrovBasis M.toSpacetime M.timeOrientation) := by
  refine @TopologicalSpace.IsTopologicalBasis.mk M.Carrier
    (alexandrovTopology M.toSpacetime M.timeOrientation)
    (alexandrovBasis M.toSpacetime M.timeOrientation)
    hdir (sUnion_alexandrovBasis_eq_univ M) ?_
  rfl

end LorentzianSpacetime

end Spacetime

end Physicslib4
