/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.Spacetime.Basic
import Physicslib4.Spacetime.CausalStructure
import Physicslib4.Spacetime.Curves
import Physicslib4.Spacetime.Causality
import Mathlib.Geometry.Manifold.MFDeriv.SpecificFunctions
import Mathlib.Geometry.Manifold.MFDeriv.Atlas
import Mathlib.Geometry.Manifold.ContMDiff.NormedSpace
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus
import Mathlib.Analysis.Calculus.ContDiff.Deriv
import Mathlib.Analysis.Convex.Basic

/-!
# Minkowski spacetime and the Alexandrov topology

This file formalises the last three definitions of section 10.2 of the
AQFT-in-Lean blueprint: standard Minkowski spacetime, the Alexandrov
topology generated by intersections of chronological futures and pasts,
and Minkowski spacetime (= standard Minkowski equipped with the
Alexandrov topology).

## Main definitions

* `Physicslib4.StandardMinkowskiSpacetime`: the unique spacetime whose
  underlying manifold is `ℝ⁴` with its Euclidean topology and whose
  metric is `diag(-1, 1, 1, 1)` in the standard coordinates.
* `Physicslib4.Spacetime.alexandrovTopology`: the topology on a spacetime
  generated by all sets of the form `I^+(p) ∩ I^-(q)`.
* `Physicslib4.MinkowskiSpacetime`: a `Type` synonym for
  `StandardMinkowskiSpacetime.Carrier` carrying the Alexandrov topology
  as the canonical topology instance.

## Modelling notes

* The bilinear form on `T_p ℝ⁴` corresponding to `diag(-1,1,1,1)` is
  constructed pointwise as a continuous bilinear map. We expose the
  underlying function on the model space; symmetry, non-degeneracy, and
  the Lorentzian condition are all proved in the
  `StandardMinkowskiSpacetime` construction, and the smooth-manifold data
  is the identity charted space on `ℝ⁴`. The blueprint's statement is
  faithfully captured by the shape of `StandardMinkowskiSpacetime`.

* `MinkowskiSpacetime` is defined as a type synonym for the carrier of
  `StandardMinkowskiSpacetime` (i.e. `ℝ⁴`), with a `TopologicalSpace`
  instance given by the Alexandrov topology. The smooth-manifold
  structure is inherited from `StandardMinkowskiSpacetime` if one wishes
  to view the same underlying point set as both.
-/

namespace Physicslib4

open scoped Manifold

/-! ### Standard Minkowski spacetime -/

/-- The underlying bilinear `LinearMap` for the Minkowski metric on
`ℝ⁴`: `(v, w) ↦ -v 0 * w 0 + v 1 * w 1 + v 2 * w 2 + v 3 * w 3`. -/
noncomputable def minkowskiFormₗ :
    SpacetimeModel →ₗ[ℝ] SpacetimeModel →ₗ[ℝ] ℝ :=
  LinearMap.mk₂ ℝ
    (fun v w => -(v 0) * (w 0) + (v 1) * (w 1) + (v 2) * (w 2) + (v 3) * (w 3))
    (fun v₁ v₂ w => by simp; ring)
    (fun c v w => by simp; ring)
    (fun v w₁ w₂ => by simp; ring)
    (fun c v w => by simp; ring)

/-- The Minkowski metric on `T_p ℝ⁴ = ℝ⁴`, viewed as a continuous bilinear
form `ℝ⁴ →L[ℝ] ℝ⁴ →L[ℝ] ℝ` given by `(v, w) ↦ -v 0 * w 0 + v 1 * w 1 +
v 2 * w 2 + v 3 * w 3`. This is the form whose Gram matrix in the standard
basis is `diag(-1, 1, 1, 1) = lorentzSignature`. -/
noncomputable def minkowskiForm :
    SpacetimeModel →L[ℝ] SpacetimeModel →L[ℝ] ℝ :=
  LinearMap.toContinuousLinearMap
    { toFun := fun v => LinearMap.toContinuousLinearMap (minkowskiFormₗ v)
      map_add' := fun v₁ v₂ => by
        ext w
        simp [minkowskiFormₗ]
      map_smul' := fun c v => by
        ext w
        simp [minkowskiFormₗ] }

@[simp] theorem minkowskiForm_apply (v w : SpacetimeModel) :
    minkowskiForm v w =
      -(v 0) * (w 0) + (v 1) * (w 1) + (v 2) * (w 2) + (v 3) * (w 3) := by
  rfl

/--
*Standard Minkowski spacetime* is the spacetime whose underlying real,
four-dimensional, connected, smooth, Hausdorff manifold is `ℝ⁴` (with the
Euclidean topology) and whose metric `g|_p` is `diag(-1, 1, 1, 1)` in the
standard coordinates, for every `p`.

We package the spacetime via the `Spacetime` structure, using the identity
charted space on `EuclideanSpace ℝ (Fin 4)` and the identity model with
corners. The metric is the constant continuous bilinear form
`minkowskiForm`.
-/
noncomputable def StandardMinkowskiSpacetime : Spacetime where
  Carrier := SpacetimeModel
  topology := inferInstance
  hausdorff := inferInstance
  connected := inferInstance
  chartedSpace := chartedSpaceSelf SpacetimeModel
  model := modelWithCornersSelf ℝ SpacetimeModel
  isManifold := by
    -- The identity charted space is a `C^∞` manifold.
    infer_instance
  tangent_findim := fun _ => by
    -- `TangentSpace (modelWithCornersSelf ℝ SpacetimeModel) _` reduces to
    -- `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`, which is finite-dimensional.
    change FiniteDimensional ℝ SpacetimeModel
    infer_instance
  val := fun _ => minkowskiForm
  symm := by
    intro _ v w
    change minkowskiForm v w = minkowskiForm w v
    simp only [minkowskiForm_apply]
    ring
  nondegenerate := by
    intro _ v hv
    -- `TangentSpace 𝓘(ℝ, SpacetimeModel) _` reduces to `SpacetimeModel`, so
    -- the hypothesis `hv` can be viewed at the model type for the `PiLp` API.
    have hv' : ∀ w : SpacetimeModel, minkowskiForm v w = 0 := hv
    apply PiLp.ext
    intro i
    -- The RHS `WithLp.ofLp 0 i` reduces definitionally to `(0 : ℝ)`.
    change v.ofLp i = (0 : ℝ)
    -- Instantiate `hv'` at the basis vector `EuclideanSpace.single i 1`.
    have hi := hv' (PiLp.single 2 i (1 : ℝ))
    simp only [minkowskiForm_apply] at hi
    -- `(PiLp.single 2 i 1).ofLp j = if j = i then 1 else 0`. Splitting on
    -- `i : Fin 4` and simplifying collapses `hi` to `v.ofLp i = 0`.
    fin_cases i <;> simp_all
  lorentzian := by
    intro x
    -- Witness: the standard orthonormal basis of `EuclideanSpace ℝ (Fin 4)`,
    -- viewed as a `Module.Basis` via `OrthonormalBasis.toBasis`.
    refine ⟨(EuclideanSpace.basisFun (Fin 4) ℝ).toBasis, ?_⟩
    intro i j
    -- Unfold the lambda and the `TangentSpace`/`OrthonormalBasis.toBasis`
    -- machinery so the goal becomes about `minkowskiForm` on
    -- `EuclideanSpace.single _ 1` vectors.
    change minkowskiForm
        ((EuclideanSpace.basisFun (Fin 4) ℝ) i)
        ((EuclideanSpace.basisFun (Fin 4) ℝ) j) =
        lorentzSignature i j
    rw [EuclideanSpace.basisFun_apply, EuclideanSpace.basisFun_apply]
    simp only [minkowskiForm_apply, lorentzSignature, Matrix.diagonal]
    fin_cases i <;> fin_cases j <;> simp [Matrix.of_apply]
  smooth_in_charts := by
    intro x₀ v w
    -- Unfold the `let e := extChartAt ... x₀` binding.
    simp only
    -- On the model space, `mfderiv I I (e.symm) y = id`, so the integrand is
    -- the constant `minkowskiForm v w` on `e.target = univ`.
    apply ContDiffWithinAt.congr_of_eventuallyEq
      (f := fun _ : SpacetimeModel => minkowskiForm v w)
    · exact contDiffWithinAt_const
    · -- Pointwise equality of the integrand with the constant `minkowskiForm v w`
      -- on a neighborhood of `e x₀` within `e.target`.
      filter_upwards with y
      have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀).symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, mfderiv_id]
      rfl
    · -- `(fun _ => minkowskiForm v w) (e x₀) = minkowskiForm v w`, and the
      -- function we replaced it with also evaluates to `minkowskiForm v w`
      -- at `y = e x₀` (since `e.symm (e x₀) = x₀` and `mfderiv id = id`).
      have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀).symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, mfderiv_id]
      rfl

/-- Additive-group structure on the Minkowski spacetime carrier,
inherited from `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`. -/
noncomputable instance instAddCommGroupStandardMinkowskiCarrier :
    AddCommGroup StandardMinkowskiSpacetime.Carrier := by
  change AddCommGroup SpacetimeModel
  infer_instance

/-- `ℝ`-module structure on the Minkowski spacetime carrier,
inherited from `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`. -/
noncomputable instance instModuleStandardMinkowskiCarrier :
    Module ℝ StandardMinkowskiSpacetime.Carrier := by
  change Module ℝ SpacetimeModel
  infer_instance

/-- `StandardMinkowskiSpacetime.Carrier` is definitionally `SpacetimeModel`
(`= EuclideanSpace ℝ (Fin 4)`); expose its normed/finite-dimensional structure
so that the Fréchet-derivative and continuity API applies to the affine
Lorentz action directly. -/
noncomputable instance instNormedAddCommGroupStandardMinkowskiCarrier :
    NormedAddCommGroup StandardMinkowskiSpacetime.Carrier :=
  inferInstanceAs (NormedAddCommGroup SpacetimeModel)

noncomputable instance instNormedSpaceStandardMinkowskiCarrier :
    NormedSpace ℝ StandardMinkowskiSpacetime.Carrier :=
  inferInstanceAs (NormedSpace ℝ SpacetimeModel)

instance instFiniteDimensionalStandardMinkowskiCarrier :
    FiniteDimensional ℝ StandardMinkowskiSpacetime.Carrier :=
  inferInstanceAs (FiniteDimensional ℝ SpacetimeModel)

/-! ### The orthochronous Lorentz group SO(1,3)↑ -/

/-- A linear automorphism `L` of the spacetime model preserves the
Minkowski form: `⟨L v, L w⟩ = ⟨v, w⟩` for all `v, w`. -/
def IsLorentz (L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel) : Prop :=
  ∀ v w, minkowskiForm (L v) (L w) = minkowskiForm v w

/-- A linear automorphism `L` is *proper* if its determinant is `1`. -/
def IsProper (L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel) : Prop :=
  LinearMap.det L.toLinearMap = 1

/-- A linear automorphism `L` is *orthochronous* if it preserves the
direction of time: the time component of `L e₀` is positive, where
`e₀ = EuclideanSpace.single 0 1` is the standard timelike basis vector. -/
def IsOrthochronous (L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel) : Prop :=
  0 < (L (EuclideanSpace.single (0 : Fin 4) (1 : ℝ))) 0

/-- The identity preserves the Minkowski form. -/
theorem isLorentz_refl : IsLorentz (LinearEquiv.refl ℝ SpacetimeModel) := by
  intro v w; rfl

/-- The composition of two Lorentz transformations is Lorentz. -/
theorem isLorentz_trans {L₁ L₂ : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h₁ : IsLorentz L₁) (h₂ : IsLorentz L₂) : IsLorentz (L₁.trans L₂) := by
  intro v w
  simp only [LinearEquiv.trans_apply]
  rw [h₂, h₁]

/-- The inverse of a Lorentz transformation is Lorentz. -/
theorem isLorentz_symm {L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h : IsLorentz L) : IsLorentz L.symm := by
  intro v w
  have := h (L.symm v) (L.symm w)
  rw [L.apply_symm_apply, L.apply_symm_apply] at this
  exact this.symm

/-- The identity is proper. -/
theorem isProper_refl : IsProper (LinearEquiv.refl ℝ SpacetimeModel) := by
  unfold IsProper
  rw [LinearEquiv.refl_toLinearMap]
  exact LinearMap.det_id

/-- The composition of two proper transformations is proper. -/
theorem isProper_trans {L₁ L₂ : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h₁ : IsProper L₁) (h₂ : IsProper L₂) : IsProper (L₁.trans L₂) := by
  unfold IsProper at h₁ h₂ ⊢
  show LinearMap.det (L₁.trans L₂).toLinearMap = 1
  -- `(L₁.trans L₂).toLinearMap = L₂.toLinearMap ∘ₗ L₁.toLinearMap`.
  have : (L₁.trans L₂).toLinearMap = L₂.toLinearMap ∘ₗ L₁.toLinearMap := rfl
  rw [this, LinearMap.det_comp, h₁, h₂, mul_one]

/-- The inverse of a proper transformation is proper. -/
theorem isProper_symm {L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h : IsProper L) : IsProper L.symm := by
  -- Use that `LinearEquiv.det` is a monoid hom to `Rˣ` and
  -- `LinearEquiv.coe_inv_det` relates it to `LinearMap.det _.symm`.
  unfold IsProper at h ⊢
  have h1 : (LinearEquiv.det L : ℝ) = 1 := by
    rw [LinearEquiv.coe_det]; exact h
  -- `LinearMap.det L.symm = ↑(LinearEquiv.det L)⁻¹`.
  rw [← LinearEquiv.coe_inv_det]
  -- `↑(u⁻¹) = (↑u)⁻¹` for units, then use `h1`.
  rw [Units.val_inv_eq_inv_val, h1, inv_one]

/-- The identity is orthochronous. -/
theorem isOrthochronous_refl :
    IsOrthochronous (LinearEquiv.refl ℝ SpacetimeModel) := by
  unfold IsOrthochronous
  simp only [LinearEquiv.refl_apply]
  -- `(EuclideanSpace.single 0 1) 0 = 1 > 0`.
  -- `EuclideanSpace ℝ (Fin 4)` is definitionally `PiLp 2 (fun _ => ℝ)`,
  -- and `(x : EuclideanSpace ℝ ι) i = x.ofLp i` definitionally.
  change (0 : ℝ) < (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0
  have : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 = 1 := by
    rw [PiLp.single_apply]; simp
  rw [this]
  exact one_pos

/-- Cauchy–Schwarz for the three-dimensional spatial parts, proved from the
Lagrange identity. -/
private lemma cauchySchwarz_sq_three (a₁ a₂ a₃ b₁ b₂ b₃ : ℝ) : -- (extracted by Fuse golfer)
    (a₁ * b₁ + a₂ * b₂ + a₃ * b₃) ^ 2
      ≤ (a₁ ^ 2 + a₂ ^ 2 + a₃ ^ 2) * (b₁ ^ 2 + b₂ ^ 2 + b₃ ^ 2) := by
  have hL : (a₁ ^ 2 + a₂ ^ 2 + a₃ ^ 2) * (b₁ ^ 2 + b₂ ^ 2 + b₃ ^ 2)
      - (a₁ * b₁ + a₂ * b₂ + a₃ * b₃) ^ 2
      = (a₁ * b₂ - a₂ * b₁) ^ 2 + (a₁ * b₃ - a₃ * b₁) ^ 2
        + (a₂ * b₃ - a₃ * b₂) ^ 2 := by ring
  linarith [sq_nonneg (a₁ * b₂ - a₂ * b₁), sq_nonneg (a₁ * b₃ - a₃ * b₁),
    sq_nonneg (a₂ * b₃ - a₃ * b₂)]

/-- Reverse Cauchy–Schwarz in coordinates: if `(a, p, q, r)` and `(b, p', q', r')`
are unit timelike vectors of `ℝ^{1,3}` whose Minkowski product is negative, then
their time components `a` and `b` have the same sign. -/
private lemma pos_of_reverse_cauchySchwarz -- (extracted by Fuse golfer)
    {a b p q r p' q' r' : ℝ}
    (hv : -a * a + p * p + q * q + r * r = -1)
    (hw : -b * b + p' * p' + q' * q' + r' * r' = -1)
    (hb : 0 < b) (hs : -a * b + p * p' + q * q' + r * r' < 0) :
    0 < a := by
  by_contra! ha0
  have ha2 : 1 ≤ a * a := by
    linarith [mul_self_nonneg p, mul_self_nonneg q, mul_self_nonneg r]
  have hb2 : 1 ≤ b * b := by
    linarith [mul_self_nonneg p', mul_self_nonneg q', mul_self_nonneg r']
  have ha : a < 0 := ha0.lt_of_ne (by rintro rfl; norm_num at ha2)
  have hab : a * b < 0 := mul_neg_of_neg_of_pos ha hb
  -- Cauchy–Schwarz bounds `⟨v,w⟩²` above by `(a² - 1)(b² - 1)`.
  have hCS : (p * p' + q * q' + r * r') ^ 2 ≤ (a * a - 1) * (b * b - 1) := by
    have h1 : p ^ 2 + q ^ 2 + r ^ 2 = a * a - 1 := by linarith
    have h2 : p' ^ 2 + q' ^ 2 + r' ^ 2 = b * b - 1 := by linarith
    rw [← h1, ← h2]
    exact cauchySchwarz_sq_three p q r p' q' r'
  -- Both `⟨v,w⟩` and `a * b` are negative with `⟨v,w⟩ < a * b`, so `⟨v,w⟩² > (a*b)²`.
  have hs2 : (0 : ℝ) < (a * b - (p * p' + q * q' + r * r')) *
      (-(a * b) - (p * p' + q * q' + r * r')) :=
    mul_pos (by linarith) (by linarith)
  linarith

/-- Helper: if two timelike unit vectors `v, w` (with
`minkowskiForm v v = minkowskiForm w w = -1`) satisfy
`minkowskiForm v w < 0` and `w` has positive time component,
then `v` also has positive time component. This is the
"reverse Cauchy-Schwarz" lemma underlying orthochronousness. -/
private lemma timelike_sameSign_of_minkowskiForm_neg
    {v w : SpacetimeModel}
    (hv : minkowskiForm v v = -1) (hw : minkowskiForm w w = -1)
    (hpos : 0 < w.ofLp 0) (hvw : minkowskiForm v w < 0) :
    0 < v.ofLp 0 := by
  simp only [minkowskiForm_apply] at hv hw hvw
  exact pos_of_reverse_cauchySchwarz hv hw hpos hvw

/-- The composition of two orthochronous Lorentz transformations is
orthochronous. (Requires that both transformations are Lorentz.) -/
theorem isOrthochronous_trans {L₁ L₂ : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (hL₁ : IsLorentz L₁) (hO₁ : IsOrthochronous L₁)
    (hL₂ : IsLorentz L₂) (hO₂ : IsOrthochronous L₂) :
    IsOrthochronous (L₁.trans L₂) := by
  set e₀ : SpacetimeModel := EuclideanSpace.single (0 : Fin 4) (1 : ℝ) with he₀
  have he₀_form : minkowskiForm e₀ e₀ = -1 := by
    simp only [minkowskiForm_apply]
    have h0 : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
    have h1 : e₀.ofLp 1 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h2 : e₀.ofLp 2 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h3 : e₀.ofLp 3 = 0 := by rw [he₀, PiLp.single_apply]; simp
    change -(e₀.ofLp 0) * (e₀.ofLp 0) + (e₀.ofLp 1) * (e₀.ofLp 1) +
        (e₀.ofLp 2) * (e₀.ofLp 2) + (e₀.ofLp 3) * (e₀.ofLp 3) = -1
    rw [h0, h1, h2, h3]; ring
  have huu : minkowskiForm (L₁ e₀) (L₁ e₀) = -1 := by rw [hL₁]; exact he₀_form
  have hvv : minkowskiForm (L₂ (L₁ e₀)) (L₂ (L₁ e₀)) = -1 := by
    rw [hL₂]; exact huu
  have hww : minkowskiForm (L₂ e₀) (L₂ e₀) = -1 := by rw [hL₂]; exact he₀_form
  have hvw_eq : minkowskiForm (L₂ (L₁ e₀)) (L₂ e₀) = -((L₁ e₀).ofLp 0) := by
    rw [hL₂]
    simp only [minkowskiForm_apply]
    have h0 : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
    have h1 : e₀.ofLp 1 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h2 : e₀.ofLp 2 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h3 : e₀.ofLp 3 = 0 := by rw [he₀, PiLp.single_apply]; simp
    change -((L₁ e₀).ofLp 0) * (e₀.ofLp 0) + ((L₁ e₀).ofLp 1) * (e₀.ofLp 1) +
        ((L₁ e₀).ofLp 2) * (e₀.ofLp 2) + ((L₁ e₀).ofLp 3) * (e₀.ofLp 3) =
          -((L₁ e₀).ofLp 0)
    rw [h0, h1, h2, h3]; ring
  have hu0 : (0 : ℝ) < (L₁ e₀).ofLp 0 := hO₁
  have hw0 : (0 : ℝ) < (L₂ e₀).ofLp 0 := hO₂
  have hvw_neg : minkowskiForm (L₂ (L₁ e₀)) (L₂ e₀) < 0 := by
    rw [hvw_eq]; linarith
  unfold IsOrthochronous
  change (0 : ℝ) < ((L₁.trans L₂) e₀).ofLp 0
  have htrans : (L₁.trans L₂) e₀ = L₂ (L₁ e₀) := rfl
  rw [htrans]
  exact timelike_sameSign_of_minkowskiForm_neg hvv hww hw0 hvw_neg

/-- The inverse of an orthochronous Lorentz transformation is
orthochronous. -/
theorem isOrthochronous_symm {L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (hL : IsLorentz L) (hO : IsOrthochronous L) : IsOrthochronous L.symm := by
  set e₀ : SpacetimeModel := EuclideanSpace.single (0 : Fin 4) (1 : ℝ) with he₀
  have he₀_form : minkowskiForm e₀ e₀ = -1 := by
    simp only [minkowskiForm_apply]
    have h0 : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
    have h1 : e₀.ofLp 1 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h2 : e₀.ofLp 2 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h3 : e₀.ofLp 3 = 0 := by rw [he₀, PiLp.single_apply]; simp
    change -(e₀.ofLp 0) * (e₀.ofLp 0) + (e₀.ofLp 1) * (e₀.ofLp 1) +
        (e₀.ofLp 2) * (e₀.ofLp 2) + (e₀.ofLp 3) * (e₀.ofLp 3) = -1
    rw [h0, h1, h2, h3]; ring
  have hLsymm : IsLorentz L.symm := isLorentz_symm hL
  have hvv : minkowskiForm (L.symm e₀) (L.symm e₀) = -1 := by
    rw [hLsymm]; exact he₀_form
  have hww : minkowskiForm e₀ e₀ = -1 := he₀_form
  have hkey : minkowskiForm (L.symm e₀) e₀ = -((L e₀).ofLp 0) := by
    have hL' := hL (L.symm e₀) e₀
    rw [L.apply_symm_apply] at hL'
    rw [← hL']
    simp only [minkowskiForm_apply]
    have h0 : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
    have h1 : e₀.ofLp 1 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h2 : e₀.ofLp 2 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h3 : e₀.ofLp 3 = 0 := by rw [he₀, PiLp.single_apply]; simp
    change -(e₀.ofLp 0) * ((L e₀).ofLp 0) + (e₀.ofLp 1) * ((L e₀).ofLp 1)
        + (e₀.ofLp 2) * ((L e₀).ofLp 2) + (e₀.ofLp 3) * ((L e₀).ofLp 3)
          = -((L e₀).ofLp 0)
    rw [h0, h1, h2, h3]; ring
  have hw0 : (0 : ℝ) < e₀.ofLp 0 := by
    have : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
    rw [this]; exact one_pos
  have hLe0 : (0 : ℝ) < (L e₀).ofLp 0 := hO
  have hvw_neg : minkowskiForm (L.symm e₀) e₀ < 0 := by
    rw [hkey]; linarith
  unfold IsOrthochronous
  change (0 : ℝ) < (L.symm e₀).ofLp 0
  exact timelike_sameSign_of_minkowskiForm_neg hvv hww hw0 hvw_neg

/-! ### Future-cone preservation under orthochronous Lorentz maps -/

/-- The Minkowski inner product of any vector `v` with the canonical timelike
basis vector `e₀ = ∂₀` equals `-(v 0)`. -/
theorem minkowskiForm_single_zero_right (v : SpacetimeModel) :
    minkowskiForm v (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) = -(v.ofLp 0) := by
  set e₀ : SpacetimeModel := EuclideanSpace.single (0 : Fin 4) (1 : ℝ) with he₀
  simp only [minkowskiForm_apply]
  have h0 : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
  have h1 : e₀.ofLp 1 = 0 := by rw [he₀, PiLp.single_apply]; simp
  have h2 : e₀.ofLp 2 = 0 := by rw [he₀, PiLp.single_apply]; simp
  have h3 : e₀.ofLp 3 = 0 := by rw [he₀, PiLp.single_apply]; simp
  change -(v.ofLp 0) * (e₀.ofLp 0) + (v.ofLp 1) * (e₀.ofLp 1)
      + (v.ofLp 2) * (e₀.ofLp 2) + (v.ofLp 3) * (e₀.ofLp 3) = -(v.ofLp 0)
  rw [h0, h1, h2, h3]; ring

/-- The Minkowski inner product of the canonical timelike basis vector
`e₀ = ∂₀` with any vector `v` equals `-(v 0)`. -/
theorem minkowskiForm_single_zero_left (v : SpacetimeModel) :
    minkowskiForm (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) v = -(v.ofLp 0) := by
  set e₀ : SpacetimeModel := EuclideanSpace.single (0 : Fin 4) (1 : ℝ) with he₀
  simp only [minkowskiForm_apply]
  have h0 : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
  have h1 : e₀.ofLp 1 = 0 := by rw [he₀, PiLp.single_apply]; simp
  have h2 : e₀.ofLp 2 = 0 := by rw [he₀, PiLp.single_apply]; simp
  have h3 : e₀.ofLp 3 = 0 := by rw [he₀, PiLp.single_apply]; simp
  change -(e₀.ofLp 0) * (v.ofLp 0) + (e₀.ofLp 1) * (v.ofLp 1)
      + (e₀.ofLp 2) * (v.ofLp 2) + (e₀.ofLp 3) * (v.ofLp 3) = -(v.ofLp 0)
  rw [h0, h1, h2, h3]; ring

/-- Bilinearity of `minkowskiForm` in the left argument under scalar
multiplication. -/
private theorem minkowskiForm_smul_left (r : ℝ) (a b : SpacetimeModel) :
    minkowskiForm (r • a) b = r * minkowskiForm a b := by
  rw [map_smul, smul_apply, smul_eq_mul]

/-- Bilinearity of `minkowskiForm` in the right argument under scalar
multiplication. -/
private theorem minkowskiForm_smul_right (r : ℝ) (a b : SpacetimeModel) :
    minkowskiForm a (r • b) = r * minkowskiForm a b := by
  rw [map_smul, smul_eq_mul]

/-- **An orthochronous Lorentz transformation preserves the sign of the time
component of a timelike vector.** If `v` is timelike (`⟨v, v⟩ < 0`) with
positive time component, then so is `L v`. This is the geometric heart of
"the future cone is preserved", and underlies the future-orientation
invariance of causal curves. The proof normalises `v` to a unit timelike
vector and compares it with the (already unit, future-pointing) reference
`L e₀` via the reverse Cauchy-Schwarz lemma
`timelike_sameSign_of_minkowskiForm_neg`. -/
theorem isOrthochronous_pos_time_of_timelike
    {L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (hL : IsLorentz L) (hO : IsOrthochronous L) {v : SpacetimeModel}
    (htl : minkowskiForm v v < 0) (hpos : 0 < v.ofLp 0) : 0 < (L v).ofLp 0 := by
  set e₀ : SpacetimeModel := EuclideanSpace.single (0 : Fin 4) (1 : ℝ) with he₀
  -- The reference vector `W = L e₀` is unit timelike and future-pointing.
  have he₀_form : minkowskiForm e₀ e₀ = -1 := by
    simp only [minkowskiForm_apply]
    have h0 : e₀.ofLp 0 = 1 := by rw [he₀, PiLp.single_apply]; simp
    have h1 : e₀.ofLp 1 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h2 : e₀.ofLp 2 = 0 := by rw [he₀, PiLp.single_apply]; simp
    have h3 : e₀.ofLp 3 = 0 := by rw [he₀, PiLp.single_apply]; simp
    change -(e₀.ofLp 0) * (e₀.ofLp 0) + (e₀.ofLp 1) * (e₀.ofLp 1) +
        (e₀.ofLp 2) * (e₀.ofLp 2) + (e₀.ofLp 3) * (e₀.ofLp 3) = -1
    rw [h0, h1, h2, h3]; ring
  have hWW : minkowskiForm (L e₀) (L e₀) = -1 := by rw [hL]; exact he₀_form
  have hW0 : (0 : ℝ) < (L e₀).ofLp 0 := hO
  -- Normalisation constant `c = √(-⟨v,v⟩) > 0`.
  set c : ℝ := Real.sqrt (-(minkowskiForm v v)) with hc
  have hcpos : 0 < c := Real.sqrt_pos.mpr (by linarith)
  have hcne : c ≠ 0 := ne_of_gt hcpos
  have hc2 : c * c = -(minkowskiForm v v) := Real.mul_self_sqrt (by linarith)
  -- The normalised vector `V = c⁻¹ • L v` is unit timelike.
  set V : SpacetimeModel := c⁻¹ • (L v) with hV
  have hVV : minkowskiForm V V = -1 := by
    have hexp : minkowskiForm V V = c⁻¹ * (c⁻¹ * minkowskiForm v v) := by
      rw [hV, minkowskiForm_smul_left, minkowskiForm_smul_right, hL]
    have hmv : minkowskiForm v v = -(c * c) := by linarith [hc2]
    rw [hexp, hmv]
    have hrw : c⁻¹ * (c⁻¹ * -(c * c)) = -((c⁻¹ * c) * (c⁻¹ * c)) := by ring
    rw [hrw, inv_mul_cancel₀ hcne]; norm_num
  -- `⟨V, L e₀⟩ < 0`, since it equals `c⁻¹ * (-(v 0))`.
  have hVW : minkowskiForm V (L e₀) < 0 := by
    have hexp : minkowskiForm V (L e₀) = c⁻¹ * (-(v.ofLp 0)) := by
      rw [hV, minkowskiForm_smul_left, hL, minkowskiForm_single_zero_right]
    rw [hexp]
    exact mul_neg_of_pos_of_neg (inv_pos.mpr hcpos) (by linarith)
  -- Reverse Cauchy-Schwarz: `V` has positive time component, hence so does `L v`.
  have hVpos : 0 < V.ofLp 0 :=
    timelike_sameSign_of_minkowskiForm_neg hVV hWW hW0 hVW
  have hVcoord : V.ofLp 0 = c⁻¹ * (L v).ofLp 0 := by
    rw [hV]; rfl
  rw [hVcoord] at hVpos
  have hmul := mul_pos hcpos hVpos
  rwa [← mul_assoc, mul_inv_cancel₀ hcne, one_mul] at hmul

/-! ### The forward and backward Minkowski-cones -/

/-- The *forward Minkowski-cone* of a point `p ∈ ℝ⁴`: the set of
points `q` with `p.0 < q.0` and `-(q.0 - p.0)² + Σ_{i>0} (q.i - p.i)² < 0`.
This is the coordinate-explicit form of the chronological future of `p`
on standard Minkowski spacetime. -/
def minkowskiForwardCone (p : SpacetimeModel) : Set SpacetimeModel :=
  {q | p 0 < q 0 ∧
    -(q 0 - p 0)^2 + (q 1 - p 1)^2 + (q 2 - p 2)^2 + (q 3 - p 3)^2 < 0}

/-- The *backward Minkowski-cone* of a point `q ∈ ℝ⁴`: the set of points
`p` with `p.0 < q.0` and `-(q.0 - p.0)² + Σ_{i>0} (q.i - p.i)² < 0`.
Equivalently, `p ∈ minkowskiBackwardCone q ↔ q ∈ minkowskiForwardCone p`. -/
def minkowskiBackwardCone (q : SpacetimeModel) : Set SpacetimeModel :=
  {p | p 0 < q 0 ∧
    -(q 0 - p 0)^2 + (q 1 - p 1)^2 + (q 2 - p 2)^2 + (q 3 - p 3)^2 < 0}

@[simp] theorem mem_minkowskiForwardCone (p q : SpacetimeModel) :
    q ∈ minkowskiForwardCone p ↔
      p 0 < q 0 ∧
      -(q 0 - p 0)^2 + (q 1 - p 1)^2 + (q 2 - p 2)^2 + (q 3 - p 3)^2 < 0 := Iff.rfl

@[simp] theorem mem_minkowskiBackwardCone (p q : SpacetimeModel) :
    p ∈ minkowskiBackwardCone q ↔
      p 0 < q 0 ∧
      -(q 0 - p 0)^2 + (q 1 - p 1)^2 + (q 2 - p 2)^2 + (q 3 - p 3)^2 < 0 := Iff.rfl

theorem minkowskiBackwardCone_eq (q : SpacetimeModel) :
    minkowskiBackwardCone q = {p | q ∈ minkowskiForwardCone p} := rfl

/-- The forward Minkowski-cone of `p` is an open subset of the Euclidean
topology on `ℝ⁴`. -/
theorem isOpen_minkowskiForwardCone (p : SpacetimeModel) :
    IsOpen (minkowskiForwardCone p) := by
  have h0 : Continuous fun q : SpacetimeModel => q 0 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 0
  have h1 : Continuous fun q : SpacetimeModel => q 1 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 1
  have h2 : Continuous fun q : SpacetimeModel => q 2 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 2
  have h3 : Continuous fun q : SpacetimeModel => q 3 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 3
  have hOpen1 : IsOpen {q : SpacetimeModel | p 0 < q 0} :=
    h0.isOpen_preimage _ isOpen_Ioi
  have hCont :
      Continuous fun q : SpacetimeModel =>
        -(q 0 - p 0) ^ 2 + (q 1 - p 1) ^ 2 + (q 2 - p 2) ^ 2 + (q 3 - p 3) ^ 2 := by
    refine ((((h0.sub continuous_const).pow 2).neg.add
      ((h1.sub continuous_const).pow 2)).add
      ((h2.sub continuous_const).pow 2)).add
      ((h3.sub continuous_const).pow 2)
  have hOpen2 :
      IsOpen {q : SpacetimeModel |
        -(q 0 - p 0) ^ 2 + (q 1 - p 1) ^ 2 + (q 2 - p 2) ^ 2 + (q 3 - p 3) ^ 2 < 0} :=
    hCont.isOpen_preimage _ isOpen_Iio
  exact hOpen1.inter hOpen2

/-- The backward Minkowski-cone of `q` is an open subset of the Euclidean
topology on `ℝ⁴`. -/
theorem isOpen_minkowskiBackwardCone (q : SpacetimeModel) :
    IsOpen (minkowskiBackwardCone q) := by
  have h0 : Continuous fun p : SpacetimeModel => p 0 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 0
  have h1 : Continuous fun p : SpacetimeModel => p 1 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 1
  have h2 : Continuous fun p : SpacetimeModel => p 2 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 2
  have h3 : Continuous fun p : SpacetimeModel => p 3 :=
    PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 3
  have hOpen1 : IsOpen {p : SpacetimeModel | p 0 < q 0} :=
    h0.isOpen_preimage _ isOpen_Iio
  have hCont :
      Continuous fun p : SpacetimeModel =>
        -(q 0 - p 0) ^ 2 + (q 1 - p 1) ^ 2 + (q 2 - p 2) ^ 2 + (q 3 - p 3) ^ 2 := by
    refine ((((continuous_const.sub h0).pow 2).neg.add
      ((continuous_const.sub h1).pow 2)).add
      ((continuous_const.sub h2).pow 2)).add
      ((continuous_const.sub h3).pow 2)
  have hOpen2 :
      IsOpen {p : SpacetimeModel |
        -(q 0 - p 0) ^ 2 + (q 1 - p 1) ^ 2 + (q 2 - p 2) ^ 2 + (q 3 - p 3) ^ 2 < 0} :=
    hCont.isOpen_preimage _ isOpen_Iio
  exact hOpen1.inter hOpen2

/-! ### Minkowski spacetime -/

/--
*Minkowski spacetime* is the carrier of `StandardMinkowskiSpacetime`
viewed as a topological space under the Alexandrov topology.

We expose `MinkowskiSpacetime` as a `def` returning a `Spacetime`,
following the convention used for `StandardMinkowskiSpacetime`. The
"underlying topology is the Alexandrov topology" character of Minkowski
spacetime is captured at the typeclass level by the alternative
`MinkowskiSpacetimeCarrier` synonym below, which carries the Alexandrov
topology directly.

A time orientation `t` on standard Minkowski spacetime is required to
talk about the Alexandrov topology. It is the constant timelike vector
field `∂_0` pointing in the `0`-th coordinate direction, with its
non-vanishing discharged below.
-/
noncomputable def standardMinkowskiTimeOrientation :
    StandardMinkowskiSpacetime.TimeOrientation where
  field := fun _ => EuclideanSpace.single (0 : Fin 4) (1 : ℝ)
  nonvanishing := by
    intro x h
    have h0 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 = 1 := by
      rw [PiLp.single_apply]; simp
    have hzero : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 =
        (0 : SpacetimeModel).ofLp 0 := by rw [h]; rfl
    have hz : (0 : SpacetimeModel).ofLp 0 = (0 : ℝ) := rfl
    rw [h0, hz] at hzero
    exact one_ne_zero hzero
  timelike_at := by
    intro x
    change minkowskiForm (EuclideanSpace.single (0 : Fin 4) (1 : ℝ))
                         (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) < 0
    simp only [minkowskiForm_apply]
    have h0 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 = 1 := by
      rw [PiLp.single_apply]; simp
    have h1 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 1 = 0 := by
      rw [PiLp.single_apply]; simp
    have h2 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 2 = 0 := by
      rw [PiLp.single_apply]; simp
    have h3 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 3 = 0 := by
      rw [PiLp.single_apply]; simp
    change -((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0) +
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 1) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 1) +
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 2) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 2) +
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 3) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 3) < 0
    rw [h0, h1, h2, h3]
    norm_num
  smooth := by
    intro x₀
    -- `StandardMinkowskiSpacetime.Carrier = SpacetimeModel` by `rfl`. Cast
    -- `x₀` to `SpacetimeModel` explicitly so the structure projections in
    -- the goal reduce, matching the pattern of `smooth_in_charts`.
    let x₀' : SpacetimeModel := x₀
    change ContDiffWithinAt ℝ ⊤
      (fun y => mfderiv (modelWithCornersSelf ℝ SpacetimeModel)
                        (modelWithCornersSelf ℝ SpacetimeModel)
          (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm y
          (mfderiv (modelWithCornersSelf ℝ SpacetimeModel)
                   (modelWithCornersSelf ℝ SpacetimeModel)
            (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀')
            ((extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm y)
            (EuclideanSpace.single (0 : Fin 4) (1 : ℝ))))
      (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').target
      ((extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀') x₀')
    apply ContDiffWithinAt.congr_of_eventuallyEq
      (f := fun _ : SpacetimeModel => EuclideanSpace.single (0 : Fin 4) (1 : ℝ))
    · exact contDiffWithinAt_const
    · filter_upwards with y
      have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      have hchart :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀') =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, hchart]
      simp only [mfderiv_id]
      rfl
    · have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      have hchart :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀') =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, hchart]
      simp only [mfderiv_id]
      rfl

/-!
### Characterisation of the chronological future on standard Minkowski

The two theorems below identify `chronologicalFuture` and
`chronologicalPast` on `StandardMinkowskiSpacetime` (with the canonical
time orientation `∂_0`) with the coordinate-explicit forward / backward
Minkowski-cones. Both statements are needed downstream to compare the
Alexandrov topology with the Euclidean topology on `ℝ⁴`; both are proved
below. The proof structure is as follows.

* **Forward direction** (`chronologicalFuture ⊆ minkowskiForwardCone`):
  given a chronological trip from `p` to `q`, one has a smooth curve
  `μ : [a, b] → ℝ⁴` whose tangent `μ'(s)` is everywhere timelike
  (`g(μ'(s), μ'(s)) < 0`) and future-oriented
  (`g(∂_0, μ'(s)) < 0`). Integrating `μ'` over `[a, b]` yields
  `q - p = ∫_a^b μ'(s) ds`. The open forward time-cone in `ℝ⁴` is a
  convex cone (closed under positive-linear combinations of timelike
  future-oriented vectors), so `q - p` lies in the open forward cone,
  i.e. `(q - p) 0 > 0` and `-((q - p) 0)^2 + Σ_{i>0} ((q - p) i)^2 < 0`.
* **Reverse direction** (`minkowskiForwardCone ⊆ chronologicalFuture`):
  given `q ∈ minkowskiForwardCone p`, define the straight-line path
  `μ : [0, 1] → ℝ⁴`, `s ↦ p + s • (q - p)`. Then `μ` is linear, hence
  `C^∞`; its derivative is the constant vector `q - p`, which is
  nonvanishing (since `p 0 < q 0` forces `q ≠ p`), timelike (the
  Minkowski form of `q - p` with itself is the hypothesis), and
  future-oriented (since `(q - p) 0 > 0`). The geodesic flag
  `IsGeodesic = True` is automatic for the chosen API, and the endpoint
  conditions are witnessed by `0`, `1 ∈ frontier (Set.Icc 0 1) = {0, 1}`
  together with `μ 0 = p` and `μ 1 = q`.

Both directions ultimately appeal to the smooth-curve API in
`Physicslib4.Spacetime.Curves` and the chronological-trip definition in
`Physicslib4.Spacetime.Causality`. The reverse direction is
`minkowskiForwardCone_subset_chronologicalFuture_standardMinkowski`,
with the analytic content factored into the named lemmas
`standardMinkowskiLineSegmentPath_continuousOn`,
`standardMinkowskiLineSegmentPath_smoothOn`,
`standardMinkowskiLineSegmentPath_mfderivWithin` and
`standardMinkowskiLineSegmentPath_nonvanishing`. The forward direction is
`chronologicalFuture_standardMinkowski_subset`, via the integration
argument below.
-/

/-- The straight-line path `s ↦ p + s • (q - p)` is continuous on `[0, 1]`
(from `continuousOn_const` / `Continuous.smul` / `continuousOn_id`). A
component of the chronological-future characterisation. -/
theorem standardMinkowskiLineSegmentPath_continuousOn (p q : SpacetimeModel) :
    ContinuousOn (fun s : ℝ => (p : SpacetimeModel) + s • (q - p))
      (Set.Icc (0 : ℝ) 1) :=
  (continuous_const.add (Continuous.smul continuous_id continuous_const)).continuousOn

/-- The straight-line path `s ↦ p + s • (q - p)` is `C^∞` on `[0, 1]`,
viewed as a map from `(ℝ, modelWithCornersSelf ℝ ℝ)` to standard Minkowski
spacetime. A component of the chronological-future characterisation. -/
theorem standardMinkowskiLineSegmentPath_smoothOn (p q : SpacetimeModel) :
    ContMDiffOn (modelWithCornersSelf ℝ ℝ)
      StandardMinkowskiSpacetime.model ⊤
      (fun s : ℝ => (p : SpacetimeModel) + s • (q - p))
      (Set.Icc (0 : ℝ) 1) := by
  have h : ContDiff ℝ (⊤ : WithTop ℕ∞) (fun s : ℝ => (p : SpacetimeModel) + s • (q - p)) :=
    contDiff_const.add (contDiff_id.smul contDiff_const)
  exact (contMDiff_iff_contDiff.mpr h).contMDiffOn

/-- The derivative of the straight-line path `s ↦ p + s • (q - p)` at every
point of `[0, 1]`, applied to the basis vector `1 : ℝ`, equals `q - p`.
A component of the chronological-future characterisation. -/
theorem standardMinkowskiLineSegmentPath_mfderivWithin (p q : SpacetimeModel) :
    ∀ s ∈ Set.Icc (0 : ℝ) 1,
      mfderivWithin (modelWithCornersSelf ℝ ℝ)
        StandardMinkowskiSpacetime.model
        (fun s : ℝ => (p : SpacetimeModel) + s • (q - p))
        (Set.Icc 0 1) s (1 : ℝ) = q - p := by
  intro s hs
  -- Reduce `mfderivWithin` to `fderivWithin` on the self-models.
  have hmodel : StandardMinkowskiSpacetime.model
      = modelWithCornersSelf ℝ SpacetimeModel := rfl
  rw [hmodel, mfderivWithin_eq_fderivWithin]
  -- The Fréchet derivative of `s ↦ p + s • (q - p)` at `s` is
  -- `(ContinuousLinearMap.id ℝ ℝ).smulRight (q - p)`.
  have hfderiv :
      HasFDerivAt (fun s : ℝ => (p : SpacetimeModel) + s • (q - p))
        ((ContinuousLinearMap.id ℝ ℝ).smulRight (q - p)) s := by
    have hidf : HasFDerivAt (fun s : ℝ => s) (ContinuousLinearMap.id ℝ ℝ) s :=
      hasFDerivAt_id s
    have h2 : HasFDerivAt (fun s : ℝ => s • (q - p))
        ((ContinuousLinearMap.id ℝ ℝ).smulRight (q - p)) s :=
      HasFDerivAt.smul_const hidf (q - p)
    exact HasFDerivAt.const_add p h2
  -- Use the within-version to identify `fderivWithin`.
  have hwithin : HasFDerivWithinAt (fun s : ℝ => (p : SpacetimeModel) + s • (q - p))
      ((ContinuousLinearMap.id ℝ ℝ).smulRight (q - p)) (Set.Icc (0 : ℝ) 1) s :=
    hfderiv.hasFDerivWithinAt
  have hunique : UniqueDiffWithinAt ℝ (Set.Icc (0 : ℝ) 1) s :=
    uniqueDiffOn_Icc zero_lt_one s hs
  rw [HasFDerivWithinAt.fderivWithin hwithin hunique]
  -- Compute the action on `1`.
  change ((ContinuousLinearMap.id ℝ ℝ).smulRight (q - p)) (1 : ℝ) = q - p
  rw [ContinuousLinearMap.smulRight_apply, ContinuousLinearMap.id_apply, one_smul]

/-- The straight-line path `s ↦ p + s • (q - p)` has non-vanishing derivative
`q - p` (assuming `p ≠ q`); follows from
`standardMinkowskiLineSegmentPath_mfderivWithin` together with `p ≠ q`. A
component of the chronological-future characterisation. -/
theorem standardMinkowskiLineSegmentPath_nonvanishing (p q : SpacetimeModel)
    (hpq : p ≠ q) :
    ∀ s ∈ Set.Icc (0 : ℝ) 1,
      mfderivWithin (modelWithCornersSelf ℝ ℝ)
        StandardMinkowskiSpacetime.model
        (fun s : ℝ => (p : SpacetimeModel) + s • (q - p))
        (Set.Icc 0 1) s (1 : ℝ) ≠ 0 := by
  intro s hs
  rw [standardMinkowskiLineSegmentPath_mfderivWithin p q s hs]
  intro hzero
  apply hpq
  have hqp : q = p := sub_eq_zero.mp hzero
  exact hqp.symm

/-- The straight-line `SmoothPath` from `p` to `q` on standard Minkowski
spacetime: `s ↦ p + s • (q - p)` parametrised by `[0, 1]`. This is the
canonical witness for the reverse direction of
`chronologicalFuture_standardMinkowski`. -/
noncomputable def standardMinkowskiLineSegmentPath
    (p q : SpacetimeModel) (hpq : p ≠ q) :
    StandardMinkowskiSpacetime.SmoothPath where
  parameterSpace := Set.Icc (0 : ℝ) 1
  isClosed := isClosed_Icc
  isConnected := ⟨⟨0, by simp⟩, isPreconnected_Icc⟩
  nontrivial := ⟨0, 1, by simp, by simp, zero_ne_one⟩
  toFun := fun s => (p : SpacetimeModel) + s • (q - p)
  continuousOn := standardMinkowskiLineSegmentPath_continuousOn p q
  smoothOn := standardMinkowskiLineSegmentPath_smoothOn p q
  nonvanishing := standardMinkowskiLineSegmentPath_nonvanishing p q hpq

/-!
### Forward direction: scaffolding for `chronologicalFuture ⊆ minkowskiForwardCone`

The forward subset of `chronologicalFuture_standardMinkowski` says: if there
is a chronological trip from `p` to `q` on standard Minkowski spacetime, then
`q` lies in the open forward Minkowski-cone of `p`. We package the analytic
content into four named lemmas and assemble the proof from them:

1. `mem_minkowskiForwardCone_iff_sub_mem` — the obvious translation
   `q ∈ minkowskiForwardCone p ↔ (q - p) ∈ minkowskiForwardCone 0`,
   reducing membership to the based-at-zero cone.
2. `standardMinkowski_timelike_futurePointing_iff_mem_minkowskiForwardCone_zero`
   — a vector `v : ℝ⁴` is timelike and future-pointing for the canonical
   time orientation `∂_0` iff `v ∈ minkowskiForwardCone 0`.
3. `standardMinkowski_trip_displacement_eq_intervalIntegral` — the
   fundamental theorem of calculus applied to a trip: given a trip from `p`
   to `q` witnessed by a smooth path `rep`, there exist parameter values
   `a ≤ b` in `rep.parameterSpace` with `rep a = p`, `rep b = q`, and
   `q - p = ∫_a^b tangent(s) ds`, where `tangent(s)` is the manifold
   derivative of `rep.toFun` at `s` applied to `1 : ℝ`. Its body wires
   together four further named sub-lemmas:

   * `standardMinkowski_smoothPath_fundamental_theorem_calculus`
     (sub-lemma A) — the integration content: for a smooth path on standard
     Minkowski parametrised by `Set.Icc a b`, the displacement
     `μ b - μ a` equals the interval integral of the manifold tangent.
   * `standardMinkowski_trip_tangent_mem_minkowskiForwardCone_zero`
     (sub-lemma B) — the geometric content: a trip witness produces a
     `rep : SmoothPath` whose endpoint structure matches `p, q` and
     whose manifold tangent at every parameter point lies in
     `minkowskiForwardCone 0`. Discharged by unpacking the trip and
     pointwise applying step 2.
   * `standardMinkowski_smoothPath_parameterSpace_eq_Icc_of_endpoints`
     (sub-lemma C) — the geometric structural content: a closed connected
     non-singleton subset of `ℝ` carrying a past and a future endpoint
     in its frontier is exhaustively a closed interval `Set.Icc a b`
     with `a < b`.
   * `standardMinkowski_smoothPath_tangent_continuousOn` (sub-lemma D)
     — the analytic regularity content: the manifold tangent
     `s ↦ mfderivWithin _ _ rep.toFun rep.parameterSpace s 1` is
     continuous on `rep.parameterSpace` whenever it equals an `Icc a b`.
4. `intervalIntegral_mem_minkowskiForwardCone_zero` — closure of the open
   forward Minkowski-cone (at the origin) under positive interval
   integration: if a continuous-on-`[a, b]` integrand lands in
   `minkowskiForwardCone 0` on the open interval `(a, b)` and `a < b`,
   then `∫_a^b f s ds ∈ minkowskiForwardCone 0`. This is the geometric
   "convex cone closed under positive linear combinations" fact, passed
   through Mathlib's interval-integral machinery.

The forward-subset proof itself wires these together: from the trip
witness, FTC (step 3) gives an interval-integral representation of
`q - p`; the trip's timelike future-pointing tangent (combined with step
2) shows the integrand lies in `minkowskiForwardCone 0`; closure under
positive integration (step 4) puts `q - p` in `minkowskiForwardCone 0`;
and the translation lemma (step 1) converts back to
`q ∈ minkowskiForwardCone p`. Each step is one of the four named lemmas
(or, for step 3, one of the four sub-lemmas A–D above).
-/

/-- Translation lemma: `q ∈ minkowskiForwardCone p ↔ (q - p) ∈
minkowskiForwardCone 0`. Both sides reduce to the same conjunction of
inequalities on the components of `q - p`. -/
theorem mem_minkowskiForwardCone_iff_sub_mem (p q : SpacetimeModel) :
    q ∈ minkowskiForwardCone p ↔ (q - p) ∈ minkowskiForwardCone 0 := by
  constructor
  · rintro ⟨h_time, h_cone⟩
    refine ⟨?_, ?_⟩
    · -- `0 0 < (q - p) 0` reduces to `0 < q 0 - p 0`, i.e. `p 0 < q 0`.
      change (0 : ℝ) < (q - p) 0
      have hsub : (q - p) 0 = q 0 - p 0 := rfl
      rw [hsub]; linarith
    · -- The quadratic form on `q - p` matches the quadratic form on `q - p`
      -- via componentwise definitional equalities.
      change -((q - p) 0 - (0 : SpacetimeModel) 0) ^ 2 +
          ((q - p) 1 - (0 : SpacetimeModel) 1) ^ 2 +
          ((q - p) 2 - (0 : SpacetimeModel) 2) ^ 2 +
          ((q - p) 3 - (0 : SpacetimeModel) 3) ^ 2 < 0
      have h0 : (0 : SpacetimeModel) 0 = 0 := rfl
      have h1 : (0 : SpacetimeModel) 1 = 0 := rfl
      have h2 : (0 : SpacetimeModel) 2 = 0 := rfl
      have h3 : (0 : SpacetimeModel) 3 = 0 := rfl
      have e0 : (q - p) 0 = q 0 - p 0 := rfl
      have e1 : (q - p) 1 = q 1 - p 1 := rfl
      have e2 : (q - p) 2 = q 2 - p 2 := rfl
      have e3 : (q - p) 3 = q 3 - p 3 := rfl
      rw [h0, h1, h2, h3, e0, e1, e2, e3]
      simp only [sub_zero]
      exact h_cone
  · rintro ⟨h_time, h_cone⟩
    refine ⟨?_, ?_⟩
    · have hsub : (q - p) 0 = q 0 - p 0 := rfl
      have h0 : (0 : SpacetimeModel) 0 = 0 := rfl
      have h_time' : (0 : ℝ) < q 0 - p 0 := by
        rw [show ((0 : SpacetimeModel) 0 : ℝ) = (0 : ℝ) from h0, hsub] at h_time
        exact h_time
      linarith
    · have h0 : (0 : SpacetimeModel) 0 = 0 := rfl
      have h1 : (0 : SpacetimeModel) 1 = 0 := rfl
      have h2 : (0 : SpacetimeModel) 2 = 0 := rfl
      have h3 : (0 : SpacetimeModel) 3 = 0 := rfl
      have e0 : (q - p) 0 = q 0 - p 0 := rfl
      have e1 : (q - p) 1 = q 1 - p 1 := rfl
      have e2 : (q - p) 2 = q 2 - p 2 := rfl
      have e3 : (q - p) 3 = q 3 - p 3 := rfl
      have h_cone' : -((q - p) 0) ^ 2 + ((q - p) 1) ^ 2 +
          ((q - p) 2) ^ 2 + ((q - p) 3) ^ 2 < 0 := by
        have := h_cone
        rw [show ((0 : SpacetimeModel) 0 : ℝ) = (0 : ℝ) from h0,
            show ((0 : SpacetimeModel) 1 : ℝ) = (0 : ℝ) from h1,
            show ((0 : SpacetimeModel) 2 : ℝ) = (0 : ℝ) from h2,
            show ((0 : SpacetimeModel) 3 : ℝ) = (0 : ℝ) from h3] at this
        simpa using this
      rw [e0, e1, e2, e3] at h_cone'
      linarith [h_cone']

/-- **Timelike + future-pointing ↔ in the forward cone.** On
standard Minkowski spacetime with canonical time orientation `∂_0`, a
tangent vector `v` is timelike and future-pointing in the
`Spacetime`-theoretic sense iff `v ∈ minkowskiForwardCone 0`. This packs
together the chain of definitional unfoldings of `IsTimelike`,
`IsFuturePointing`, and the explicit form of `minkowskiForm` against the
distinguished basis vector. -/
theorem standardMinkowski_timelike_futurePointing_iff_mem_minkowskiForwardCone_zero
    (v : SpacetimeModel) :
    (StandardMinkowskiSpacetime.IsTimelike (x := (0 : SpacetimeModel)) v ∧
      StandardMinkowskiSpacetime.IsFuturePointing
        standardMinkowskiTimeOrientation (x := (0 : SpacetimeModel)) v) ↔
    v ∈ minkowskiForwardCone 0 := by
  -- The two Minkowski products involved, in explicit coordinates.
  have hz : ∀ i : Fin 4, (0 : SpacetimeModel) i = (0 : ℝ) := fun _ => rfl
  have hvv : minkowskiForm v v = -(v 0) ^ 2 + (v 1) ^ 2 + (v 2) ^ 2 + (v 3) ^ 2 := by
    rw [minkowskiForm_apply]; ring
  have he0 : minkowskiForm (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) v = -(v 0) :=
    minkowskiForm_single_zero_left v
  constructor
  · rintro ⟨h_timelike, h_fp⟩
    have h_tl : minkowskiForm v v < 0 := h_timelike
    rw [hvv] at h_tl
    rcases h_fp with ⟨_, h_e0_v⟩ | ⟨h_null, _⟩
    · have h_e0 : minkowskiForm
            (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) v < 0 := h_e0_v
      rw [he0] at h_e0
      exact ⟨by rw [hz]; linarith, by simp only [hz, sub_zero]; exact h_tl⟩
    · have h_null' : minkowskiForm v v = 0 := h_null
      rw [hvv] at h_null'
      exact absurd h_null' h_tl.ne
  · rintro ⟨h_pos, h_cone⟩
    rw [hz] at h_pos
    simp only [hz, sub_zero] at h_cone
    have h_tl : minkowskiForm v v < 0 := by rw [hvv]; exact h_cone
    refine ⟨h_tl, Or.inl ⟨h_tl, ?_⟩⟩
    change minkowskiForm (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) v < 0
    rw [he0]; linarith

/-- **Smooth-path FTC for standard Minkowski.** For any smooth path `μ` on
standard Minkowski spacetime whose parameter space is the closed interval
`Set.Icc a b` with `a < b`, the difference of endpoints equals the interval
integral of the manifold tangent. This is the fundamental theorem of
calculus packaged for the `mfderivWithin` of a smooth path. -/
theorem standardMinkowski_smoothPath_fundamental_theorem_calculus
    (μ : StandardMinkowskiSpacetime.SmoothPath) {a b : ℝ}
    (hab : a < b) (hparam : μ.parameterSpace = Set.Icc a b) :
    (μ.toFun b - μ.toFun a : SpacetimeModel) =
      ∫ s in a..b,
        mfderivWithin (modelWithCornersSelf ℝ ℝ)
          StandardMinkowskiSpacetime.model
          μ.toFun μ.parameterSpace s (1 : ℝ) := by
  let f : ℝ → SpacetimeModel := μ.toFun
  rw [hparam]
  have hsmooth : ContDiffOn ℝ ⊤ f (Set.Icc a b) := by
    have h := μ.smoothOn
    rw [hparam] at h
    exact contMDiffOn_iff_contDiffOn.mp h
  have hcont : ContinuousOn f (Set.Icc a b) := hsmooth.continuousOn
  have hUnique : UniqueDiffOn ℝ (Set.Icc a b) := uniqueDiffOn_Icc hab
  have hderiv : ∀ x ∈ Set.Ioo a b,
      HasDerivAt f (derivWithin f (Set.Icc a b) x) x := by
    intro x hx
    have hxIcc : x ∈ Set.Icc a b := Set.Ioo_subset_Icc_self hx
    have hmem : Set.Icc a b ∈ nhds x := Icc_mem_nhds hx.1 hx.2
    have hdiffWithin : DifferentiableWithinAt ℝ f (Set.Icc a b) x :=
      hsmooth.differentiableOn (by norm_num) x hxIcc
    have hdiffAt : DifferentiableAt ℝ f x := hdiffWithin.differentiableAt hmem
    have hderivAt : HasDerivAt f (deriv f x) x := hdiffAt.hasDerivAt
    have heq : derivWithin f (Set.Icc a b) x = deriv f x :=
      derivWithin_of_mem_nhds hmem
    rw [heq]; exact hderivAt
  have hcont_deriv : ContinuousOn (derivWithin f (Set.Icc a b)) (Set.Icc a b) :=
    ContDiffOn.continuousOn_derivWithin hsmooth hUnique le_top
  have hint : IntervalIntegrable (derivWithin f (Set.Icc a b))
      MeasureTheory.volume a b :=
    hcont_deriv.intervalIntegrable_of_Icc hab.le
  have hFTC : ∫ x in a..b, derivWithin f (Set.Icc a b) x = f b - f a :=
    intervalIntegral.integral_eq_sub_of_hasDerivAt_of_le hab.le hcont hderiv hint
  have hpw : ∀ s,
      mfderivWithin (modelWithCornersSelf ℝ ℝ)
          StandardMinkowskiSpacetime.model
          μ.toFun (Set.Icc a b) s (1 : ℝ)
        = derivWithin f (Set.Icc a b) s := by
    intro s
    change mfderivWithin (modelWithCornersSelf ℝ ℝ)
          (modelWithCornersSelf ℝ SpacetimeModel) f (Set.Icc a b) s (1 : ℝ)
        = derivWithin f (Set.Icc a b) s
    rw [mfderivWithin_eq_fderivWithin]; rfl
  simp_rw [hpw]
  exact hFTC.symm

/-- **Trip tangent ∈ forward cone.** For any trip `rep` on standard Minkowski
spacetime witnessing a chronological precedence, the manifold tangent at every
parameter point lies in `minkowskiForwardCone 0`. The proof unpacks the trip
witness (yielding `rep` together with the past/future endpoint data and the
timelike future-oriented properties of `rep`) and pointwise applies
`standardMinkowski_timelike_futurePointing_iff_mem_minkowskiForwardCone_zero`. -/
theorem standardMinkowski_trip_tangent_mem_minkowskiForwardCone_zero
    {p q : SpacetimeModel} {c : StandardMinkowskiSpacetime.SmoothCurve}
    (htrip : Spacetime.IsTripSegment StandardMinkowskiSpacetime
              standardMinkowskiTimeOrientation p q c) :
    ∃ (rep : StandardMinkowskiSpacetime.SmoothPath),
      c = Spacetime.SmoothCurve.ofPath StandardMinkowskiSpacetime rep ∧
      Spacetime.IsPastEndpoint StandardMinkowskiSpacetime rep p ∧
      Spacetime.IsFutureEndpoint StandardMinkowskiSpacetime rep q ∧
      (∀ s ∈ rep.parameterSpace,
        (mfderivWithin (modelWithCornersSelf ℝ ℝ)
          StandardMinkowskiSpacetime.model
          rep.toFun rep.parameterSpace s (1 : ℝ))
          ∈ minkowskiForwardCone (0 : SpacetimeModel)) := by
  obtain ⟨rep, hc, htimelike, hfuture, _hgeo, hpast, hfuture_ep⟩ := htrip
  refine ⟨rep, hc, hpast, hfuture_ep, ?_⟩
  intro s hs
  have h1 : StandardMinkowskiSpacetime.IsTimelike (x := (0 : SpacetimeModel))
      (mfderivWithin (modelWithCornersSelf ℝ ℝ)
        StandardMinkowskiSpacetime.model
        rep.toFun rep.parameterSpace s (1 : ℝ)) := htimelike s hs
  have h2 : StandardMinkowskiSpacetime.IsFuturePointing
      standardMinkowskiTimeOrientation (x := (0 : SpacetimeModel))
      (mfderivWithin (modelWithCornersSelf ℝ ℝ)
        StandardMinkowskiSpacetime.model
        rep.toFun rep.parameterSpace s (1 : ℝ)) := hfuture s hs
  exact (standardMinkowski_timelike_futurePointing_iff_mem_minkowskiForwardCone_zero
    _).mp ⟨h1, h2⟩

/-- **Parameter space is a closed bounded interval.** A smooth path
`rep` on standard Minkowski spacetime carrying both a past endpoint `p` and
a future endpoint `q` has parameter space exhaustively equal to
`Set.Icc a b` with `a < b`, `rep.toFun a = p`, and `rep.toFun b = q`. With
the strengthened `IsPastEndpoint` / `IsFutureEndpoint` of `Curves.lean`,
the witnesses are genuine min/max of the parameter space, so `a < b`
follows from the smooth path's `nontrivial` condition alone, no `p ≠ q`
hypothesis is needed. -/
theorem standardMinkowski_smoothPath_parameterSpace_eq_Icc_of_endpoints
    (rep : StandardMinkowskiSpacetime.SmoothPath)
    {p q : SpacetimeModel}
    (hp : Spacetime.IsPastEndpoint StandardMinkowskiSpacetime rep p)
    (hq : Spacetime.IsFutureEndpoint StandardMinkowskiSpacetime rep q) :
    ∃ a b : ℝ, a < b ∧ rep.parameterSpace = Set.Icc a b ∧
      rep.toFun a = p ∧ rep.toFun b = q := by
  obtain ⟨sp, hsp_mem, hsp_eq, hsp_min⟩ := hp
  obtain ⟨sq, hsq_mem, hsq_eq, hsq_max⟩ := hq
  -- sp ≤ sq from min applied to sq
  have hsp_le_sq : sp ≤ sq := hsp_min sq hsq_mem
  -- sp < sq from nontriviality of the parameter space
  have hsp_lt_sq : sp < sq := by
    rcases rep.nontrivial with ⟨s, t, hs, ht, hst⟩
    have h1 : sp ≤ s := hsp_min s hs
    have h2 : sp ≤ t := hsp_min t ht
    have h3 : s ≤ sq := hsq_max s hs
    have h4 : t ≤ sq := hsq_max t ht
    by_contra h
    push Not at h
    have heq : sp = sq := le_antisymm hsp_le_sq h
    -- Then both s and t are squeezed: s = sp = sq = t, contradiction
    have hs_eq : s = sp := le_antisymm (heq ▸ h3) h1
    have ht_eq : t = sp := le_antisymm (heq ▸ h4) h2
    exact hst (hs_eq.trans ht_eq.symm)
  refine ⟨sp, sq, hsp_lt_sq, ?_, hsp_eq, hsq_eq⟩
  -- parameter space = Icc sp sq
  -- ⊆: by min/max
  -- ⊇: by ord-connectedness from IsConnected
  apply Set.Subset.antisymm
  · intro t ht
    exact ⟨hsp_min t ht, hsq_max t ht⟩
  · have hpre : IsPreconnected rep.parameterSpace := rep.isConnected.isPreconnected
    have hord : rep.parameterSpace.OrdConnected := hpre.ordConnected
    exact hord.out hsp_mem hsq_mem

/-- **Continuity of the manifold tangent of a smooth path on its parameter
`Icc`.** For a smooth path `μ` on standard Minkowski spacetime with parameter
space `Set.Icc a b`, the manifold tangent
`s ↦ mfderivWithin _ _ μ.toFun μ.parameterSpace s 1` is continuous on
`Set.Icc a b`. This is the `ContMDiffOn` → continuity-of-`mfderivWithin`
content packaged in a single declaration. -/
theorem standardMinkowski_smoothPath_tangent_continuousOn
    (μ : StandardMinkowskiSpacetime.SmoothPath) {a b : ℝ}
    (hparam : μ.parameterSpace = Set.Icc a b) :
    ContinuousOn
      (fun s => mfderivWithin (modelWithCornersSelf ℝ ℝ)
                  StandardMinkowskiSpacetime.model
                  μ.toFun μ.parameterSpace s (1 : ℝ))
      (Set.Icc a b) := by
  let f : ℝ → SpacetimeModel := μ.toFun
  -- Smoothness reduced to ContDiffOn on `Set.Icc a b`.
  have hsmooth : ContDiffOn ℝ ⊤ f (Set.Icc a b) := by
    have h := μ.smoothOn
    rw [hparam] at h
    exact contMDiffOn_iff_contDiffOn.mp h
  -- `a < b` from nontriviality of the parameter space.
  have hab : a < b := by
    rcases μ.nontrivial with ⟨s, t, hs, ht, hst⟩
    rw [hparam] at hs ht
    obtain ⟨has, hsb⟩ := hs
    obtain ⟨hat, htb⟩ := ht
    rcases lt_or_eq_of_le (has.trans hsb) with hlt | heq
    · exact hlt
    · exfalso
      have hsa : s = a := le_antisymm (heq ▸ hsb) has
      have hta : t = a := le_antisymm (heq ▸ htb) hat
      exact hst (hsa.trans hta.symm)
  have hUnique : UniqueDiffOn ℝ (Set.Icc a b) := uniqueDiffOn_Icc hab
  have hcont_deriv : ContinuousOn (derivWithin f (Set.Icc a b)) (Set.Icc a b) :=
    ContDiffOn.continuousOn_derivWithin hsmooth hUnique le_top
  -- Pointwise: `mfderivWithin … 1 = derivWithin f (Icc a b)`.
  have hpw : ∀ s,
      mfderivWithin (modelWithCornersSelf ℝ ℝ)
          StandardMinkowskiSpacetime.model
          μ.toFun (Set.Icc a b) s (1 : ℝ)
        = derivWithin f (Set.Icc a b) s := by
    intro s
    change mfderivWithin (modelWithCornersSelf ℝ ℝ)
          (modelWithCornersSelf ℝ SpacetimeModel) f (Set.Icc a b) s (1 : ℝ)
        = derivWithin f (Set.Icc a b) s
    rw [mfderivWithin_eq_fderivWithin]; rfl
  -- Conclude continuity by rewriting the parameter space and using `congr`.
  rw [hparam]
  refine hcont_deriv.congr ?_
  intro s _hs
  exact hpw s

/-- **FTC for a trip on standard Minkowski.** Every trip `c`
from `p` to `q` on standard Minkowski spacetime is represented by a
smooth path `rep` with parameter values `a ≤ b` lying in
`rep.parameterSpace`, satisfying `rep a = p`, `rep b = q`, with the
property that the trip's tangent at every interior `s ∈ (a, b)` is
timelike future-pointing, and such that the fundamental theorem of
calculus gives `q - p = ∫_a^b rep.tangent(s) ds`. Continuity of the
tangent on the closed parameter interval is also exposed for use in the
integration argument.

The body wires together four named sub-lemmas:
`standardMinkowski_trip_tangent_mem_minkowskiForwardCone_zero`,
`standardMinkowski_smoothPath_parameterSpace_eq_Icc_of_endpoints`,
`standardMinkowski_smoothPath_fundamental_theorem_calculus`, and
`standardMinkowski_smoothPath_tangent_continuousOn`. -/
theorem standardMinkowski_trip_displacement_eq_intervalIntegral
    {p q : SpacetimeModel} {c : StandardMinkowskiSpacetime.SmoothCurve}
    (htrip : Spacetime.IsTripSegment StandardMinkowskiSpacetime
              standardMinkowskiTimeOrientation p q c) :
    ∃ (rep : StandardMinkowskiSpacetime.SmoothPath) (a b : ℝ),
      a < b ∧ a ∈ rep.parameterSpace ∧ b ∈ rep.parameterSpace ∧
      rep.toFun a = p ∧ rep.toFun b = q ∧
      ContinuousOn
        (fun s => mfderivWithin (modelWithCornersSelf ℝ ℝ)
                    StandardMinkowskiSpacetime.model
                    rep.toFun rep.parameterSpace s (1 : ℝ))
        (Set.Icc a b) ∧
      (∀ s ∈ Set.Ioo a b,
        (mfderivWithin (modelWithCornersSelf ℝ ℝ)
            StandardMinkowskiSpacetime.model
            rep.toFun rep.parameterSpace s (1 : ℝ))
          ∈ minkowskiForwardCone (0 : SpacetimeModel)) ∧
      (q - p : SpacetimeModel) = ∫ s in a..b,
        mfderivWithin (modelWithCornersSelf ℝ ℝ)
          StandardMinkowskiSpacetime.model
          rep.toFun rep.parameterSpace s (1 : ℝ) := by
  -- (B) Unpack the trip into a representative `rep` together with the
  -- endpoint data and the pointwise tangent-in-cone witness.
  obtain ⟨rep, _hrep_eq, hpast, hfuture, htangent_cone⟩ :=
    standardMinkowski_trip_tangent_mem_minkowskiForwardCone_zero
      (p := p) (q := q) (c := c) htrip
  -- (C) Extract `a, b` with `parameterSpace = Set.Icc a b`, `a < b`, and
  -- the endpoint values.
  obtain ⟨a, b, hab, hparam, ha_eq, hb_eq⟩ :=
    standardMinkowski_smoothPath_parameterSpace_eq_Icc_of_endpoints
      rep (p := p) (q := q) hpast hfuture
  -- Membership of `a, b` in the parameter space.
  have ha_mem : a ∈ rep.parameterSpace := by
    rw [hparam]; exact Set.left_mem_Icc.mpr hab.le
  have hb_mem : b ∈ rep.parameterSpace := by
    rw [hparam]; exact Set.right_mem_Icc.mpr hab.le
  -- (D) Continuity of the tangent on `[a, b]`.
  have hcont :
      ContinuousOn
        (fun s => mfderivWithin (modelWithCornersSelf ℝ ℝ)
                    StandardMinkowskiSpacetime.model
                    rep.toFun rep.parameterSpace s (1 : ℝ))
        (Set.Icc a b) :=
    standardMinkowski_smoothPath_tangent_continuousOn rep hparam
  -- Tangent membership in the cone on the open interior `(a, b)`, obtained
  -- by restricting `htangent_cone` to `Set.Ioo a b ⊆ rep.parameterSpace`.
  have hmem :
      ∀ s ∈ Set.Ioo a b,
        (mfderivWithin (modelWithCornersSelf ℝ ℝ)
            StandardMinkowskiSpacetime.model
            rep.toFun rep.parameterSpace s (1 : ℝ))
          ∈ minkowskiForwardCone (0 : SpacetimeModel) := by
    intro s hs
    apply htangent_cone
    rw [hparam]
    exact Set.Ioo_subset_Icc_self hs
  -- (A) FTC: `rep b - rep a = ∫ s in a..b, tangent s`.
  have hftc :
      (rep.toFun b - rep.toFun a : SpacetimeModel) =
        ∫ s in a..b,
          mfderivWithin (modelWithCornersSelf ℝ ℝ)
            StandardMinkowskiSpacetime.model
            rep.toFun rep.parameterSpace s (1 : ℝ) :=
    standardMinkowski_smoothPath_fundamental_theorem_calculus rep hab hparam
  -- Substitute the endpoint values and assemble the existential.
  refine ⟨rep, a, b, hab, ha_mem, hb_mem, ha_eq, hb_eq, hcont, hmem, ?_⟩
  rw [← ha_eq, ← hb_eq]
  exact hftc

/-- The **spatial projection** on `ℝ^{1,3}`: `v ↦ v - (v 0) • e₀`, i.e. the
continuous linear endomorphism zeroing the time coordinate and fixing the
three spatial ones. -/
private noncomputable def spatialProj :
    SpacetimeModel →L[ℝ] SpacetimeModel := -- (extracted by Fuse golfer)
  ContinuousLinearMap.id ℝ SpacetimeModel -
    (EuclideanSpace.proj (0 : Fin 4)).smulRight
      (EuclideanSpace.single (0 : Fin 4) (1 : ℝ))

private theorem spatialProj_apply (v : SpacetimeModel) (i : Fin 4) :
    spatialProj v i = if i = 0 then 0 else v i := by -- (extracted by Fuse golfer)
  have hpt : spatialProj v i
      = v i - v 0 * (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) i := rfl
  rw [hpt, PiLp.single_apply]
  rcases eq_or_ne i 0 with rfl | h
  · simp
  · simp [h]

/-- The squared norm of the spatial part of `v` is `(v 1)² + (v 2)² + (v 3)²`. -/
private theorem norm_spatialProj_sq (v : SpacetimeModel) :
    ‖spatialProj v‖ ^ 2 = (v 1) ^ 2 + (v 2) ^ 2 + (v 3) ^ 2 := by
      -- (extracted by Fuse golfer)
  rw [EuclideanSpace.real_norm_sq_eq]
  simp [Fin.sum_univ_four, spatialProj_apply]

/-- **The open forward cone at the origin is the "spatial norm < time" region.**
`v ∈ minkowskiForwardCone 0` exactly when `‖spatial part of v‖ < v 0`. -/
private theorem mem_minkowskiForwardCone_zero_iff_norm_spatialProj_lt
    (v : SpacetimeModel) : -- (extracted by Fuse golfer)
    v ∈ minkowskiForwardCone (0 : SpacetimeModel) ↔ ‖spatialProj v‖ < v 0 := by
  have hz : ∀ i : Fin 4, (0 : SpacetimeModel) i = (0 : ℝ) := fun _ => rfl
  constructor
  · rintro ⟨h1, h2⟩
    rw [hz] at h1
    simp only [hz, sub_zero] at h2
    exact lt_of_pow_lt_pow_left₀ 2 h1.le (by rw [norm_spatialProj_sq]; linarith)
  · intro h
    have hsq : ‖spatialProj v‖ ^ 2 < (v 0) ^ 2 :=
      pow_lt_pow_left₀ h (norm_nonneg _) two_ne_zero
    rw [norm_spatialProj_sq] at hsq
    exact ⟨by rw [hz]; exact (norm_nonneg _).trans_lt h,
      by simp only [hz, sub_zero]; linarith⟩

/-- **Closure under positive interval integration.** If `f :
ℝ → ℝ⁴` is continuous on `[a, b]` and lies in the open forward
Minkowski-cone at the origin throughout the open interval `(a, b)` (with
`a < b`), then the interval integral `∫_a^b f s ds` also lies in
`minkowskiForwardCone 0`. This is the analytic incarnation of "the open
forward Minkowski-cone is a convex cone, closed under positive convex
combinations and hence under positive integration of cone-valued
integrands". -/
theorem intervalIntegral_mem_minkowskiForwardCone_zero
    {f : ℝ → SpacetimeModel} {a b : ℝ}
    (_hab : a < b)
    (_hf : ContinuousOn f (Set.Icc a b))
    (_hmem : ∀ s ∈ Set.Ioo a b, f s ∈ minkowskiForwardCone (0 : SpacetimeModel)) :
    (∫ s in a..b, f s) ∈ minkowskiForwardCone (0 : SpacetimeModel) := by
  have hf_int : IntervalIntegrable f MeasureTheory.volume a b :=
    _hf.intervalIntegrable_of_Icc _hab.le
  have hf0_cont : ContinuousOn (fun s => (f s) 0) (Set.Icc a b) :=
    (PiLp.continuous_apply (β := fun _ : Fin 4 => ℝ) (p := 2) 0).comp_continuousOn _hf
  have hS_cont : ContinuousOn (fun s => ‖spatialProj (f s)‖) (Set.Icc a b) :=
    continuous_norm.comp_continuousOn (spatialProj.continuous.comp_continuousOn _hf)
  -- `‖spatial‖ < time` holds strictly on `(a, b)`, hence weakly on `[a, b]`
  -- (the strict inequality extends by continuity from a dense subset).
  have hlt : ∀ s ∈ Set.Ioo a b, ‖spatialProj (f s)‖ < (f s) 0 := fun s hs =>
    (mem_minkowskiForwardCone_zero_iff_norm_spatialProj_lt _).1 (_hmem s hs)
  have hle : ∀ s ∈ Set.Icc a b, ‖spatialProj (f s)‖ ≤ (f s) 0 := fun s hs =>
    ContinuousWithinAt.closure_le (by rw [closure_Ioo _hab.ne]; exact hs)
      ((hS_cont s hs).mono Set.Ioo_subset_Icc_self)
      ((hf0_cont s hs).mono Set.Ioo_subset_Icc_self)
      fun y hy => (hlt y hy).le
  -- Strict integral inequality: ∫ ‖spatial‖ < ∫ time.
  have h_int_lt : (∫ s in a..b, ‖spatialProj (f s)‖) < ∫ s in a..b, (f s) 0 :=
    intervalIntegral.integral_lt_integral_of_continuousOn_of_le_of_exists_lt
      _hab hS_cont hf0_cont (fun x hx => hle x (Set.Ioc_subset_Icc_self hx))
      ⟨(a + b) / 2, Set.mem_Icc.mpr ⟨by linarith, by linarith⟩,
        hlt _ (Set.mem_Ioo.mpr ⟨by linarith, by linarith⟩)⟩
  -- Both `spatialProj` and the coordinate `0` functional commute with `∫`.
  have hI0 : (∫ s in a..b, f s) 0 = ∫ s in a..b, (f s) 0 := by
    have h := (ContinuousLinearMap.intervalIntegral_comp_comm
      (E := SpacetimeModel) (F := ℝ) (𝕜 := ℝ) (μ := MeasureTheory.volume)
      (f := f) (a := a) (b := b) (EuclideanSpace.proj 0) hf_int).symm
    simpa only [EuclideanSpace.coe_proj] using h
  refine (mem_minkowskiForwardCone_zero_iff_norm_spatialProj_lt _).2 ?_
  rw [hI0, ← (spatialProj.intervalIntegral_comp_comm (μ := MeasureTheory.volume) hf_int)]
  exact (intervalIntegral.norm_integral_le_integral_norm _hab.le).trans_lt h_int_lt

/-- *Forward subset* of `chronologicalFuture_standardMinkowski`: every
point in the chronological future of `p` lies in the open forward
Minkowski-cone. The body wires together
`standardMinkowski_trip_displacement_eq_intervalIntegral`,
`intervalIntegral_mem_minkowskiForwardCone_zero`, and
`mem_minkowskiForwardCone_iff_sub_mem`; the analytic content
sits in those named lemmas. -/
theorem segmentPrecedes_mem_minkowskiForwardCone {p q : SpacetimeModel}
    (hq : Spacetime.SegmentPrecedes StandardMinkowskiSpacetime
            standardMinkowskiTimeOrientation p q) :
    q ∈ minkowskiForwardCone p := by
  -- `StandardMinkowskiSpacetime.Carrier = SpacetimeModel` definitionally; we
  -- re-bind `q` at the model type so that arithmetic and cone membership
  -- elaborate cleanly.
  let q' : SpacetimeModel := q
  -- Unpack the segment witness.
  obtain ⟨c, htrip⟩ := hq
  -- FTC representation of `q' - p` as an interval integral of the trip's
  -- tangent. The lemma also delivers continuity of the tangent on `[a, b]`
  -- and membership of the tangent in `minkowskiForwardCone 0` on the open
  -- interval `(a, b)` (with `a < b` guaranteed by the nontriviality of a
  -- trip's parameter space combined with the past/future endpoint data).
  obtain ⟨rep, a, b, hab, _ha, _hb, _hpa, _hqb,
           hcont, hmem, hftc⟩ :=
    standardMinkowski_trip_displacement_eq_intervalIntegral (p := p) (q := q')
      (c := c) htrip
  -- Apply the cone's closure under positive interval integration to get
  -- `(q' - p) ∈ minkowskiForwardCone 0`.
  have hsub : (q' - p) ∈ minkowskiForwardCone (0 : SpacetimeModel) := by
    rw [hftc]
    exact intervalIntegral_mem_minkowskiForwardCone_zero hab hcont hmem
  -- Translate back: `q' ∈ minkowskiForwardCone p` iff
  -- `(q' - p) ∈ minkowskiForwardCone 0`.
  change q' ∈ minkowskiForwardCone p
  exact (mem_minkowskiForwardCone_iff_sub_mem p q').mpr hsub

/-- The open forward light cone of `ℝ^{1,3}` is closed under addition, in
coordinates: the sum of two future-pointing timelike vectors is again
future-pointing and timelike. -/
private lemma minkowskiCone_add -- (extracted by Fuse golfer)
    {a₀ a₁ a₂ a₃ b₀ b₁ b₂ b₃ : ℝ} (ha : 0 < a₀) (hb : 0 < b₀)
    (ha' : -a₀ ^ 2 + a₁ ^ 2 + a₂ ^ 2 + a₃ ^ 2 < 0)
    (hb' : -b₀ ^ 2 + b₁ ^ 2 + b₂ ^ 2 + b₃ ^ 2 < 0) :
    -(a₀ + b₀) ^ 2 + (a₁ + b₁) ^ 2 + (a₂ + b₂) ^ 2 + (a₃ + b₃) ^ 2 < 0 := by
  have hSa : a₁ ^ 2 + a₂ ^ 2 + a₃ ^ 2 < a₀ ^ 2 := by linarith
  have hSb : b₁ ^ 2 + b₂ ^ 2 + b₃ ^ 2 < b₀ ^ 2 := by linarith
  -- Cauchy–Schwarz bounds the spatial inner product by `a₀ * b₀`.
  have hdot : a₁ * b₁ + a₂ * b₂ + a₃ * b₃ < a₀ * b₀ := by
    refine (abs_lt_of_sq_lt_sq' ?_ (mul_pos ha hb).le).2
    rw [mul_pow]
    exact (cauchySchwarz_sq_three a₁ a₂ a₃ b₁ b₂ b₃).trans_lt
      (mul_lt_mul'' hSa hSb (by positivity) (by positivity))
  linarith

/-- *Forward subset* of `chronologicalFuture_standardMinkowski`: every
point in the chronological future of `p` lies in the open forward
Minkowski-cone. Because a trip is a finite chain of trip segments, this is a
transitive-closure induction: the base case is
`segmentPrecedes_mem_minkowskiForwardCone`, and the inductive step uses
forward-cone nesting `minkowskiForwardCone_subset`. -/
theorem chronologicalFuture_standardMinkowski_subset (p : SpacetimeModel) :
    Spacetime.chronologicalFuture StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation p
      ⊆ minkowskiForwardCone p := by
  intro q hq
  unfold Spacetime.chronologicalFuture at hq
  simp only [Set.mem_setOf_eq, Spacetime.ChronologicallyPrecedes, Spacetime.IsTrip] at hq
  induction hq with
  | single h =>
      exact segmentPrecedes_mem_minkowskiForwardCone h
  | tail h₁ h₂ ih =>
      obtain ⟨hp_b, hc_b⟩ := ih
      obtain ⟨hb_c, hc_c⟩ := segmentPrecedes_mem_minkowskiForwardCone h₂
      exact ⟨hp_b.trans hb_c, by
        linarith [minkowskiCone_add (sub_pos.mpr hb_c) (sub_pos.mpr hp_b) hc_c hc_b]⟩

/-- *Reverse subset* of `chronologicalFuture_standardMinkowski`: every
point of the open forward Minkowski-cone of `p` lies in the chronological
future of `p`. Witnessed by the straight-line path
`standardMinkowskiLineSegmentPath`. -/
theorem minkowskiForwardCone_subset_segmentPrecedes {p q : SpacetimeModel}
    (hq : q ∈ minkowskiForwardCone p) :
    Spacetime.SegmentPrecedes StandardMinkowskiSpacetime
      standardMinkowskiTimeOrientation p q := by
  have hpq : p ≠ q := fun h => lt_irrefl _ (h ▸ hq.1)
  -- The constant tangent `q - p` lies in the forward cone at the origin, so it
  -- is timelike and future-pointing.
  obtain ⟨htl, hfut⟩ :=
    (standardMinkowski_timelike_futurePointing_iff_mem_minkowskiForwardCone_zero (q - p)).2
      ((mem_minkowskiForwardCone_iff_sub_mem p q).1 hq)
  have htan : ∀ s ∈ Set.Icc (0 : ℝ) 1,
      (standardMinkowskiLineSegmentPath p q hpq).tangent s = q - p :=
    fun s hs => standardMinkowskiLineSegmentPath_mfderivWithin p q s hs
  refine ⟨Spacetime.SmoothCurve.ofPath _
    (standardMinkowskiLineSegmentPath p q hpq), ?_⟩
  refine ⟨standardMinkowskiLineSegmentPath p q hpq, rfl, ?_, ?_, trivial, ?_, ?_⟩
  · intro s hs
    rw [htan s hs]; exact htl
  · intro s hs
    rw [htan s hs]; exact hfut
  · refine ⟨0, Set.left_mem_Icc.mpr zero_le_one, ?_, fun _ hs' => hs'.1⟩
    change (p : SpacetimeModel) + (0 : ℝ) • (q - p) = p
    simp
  · refine ⟨1, Set.right_mem_Icc.mpr zero_le_one, ?_, fun _ hs' => hs'.2⟩
    change (p : SpacetimeModel) + (1 : ℝ) • (q - p) = q
    simp

/-- *Reverse subset* of `chronologicalFuture_standardMinkowski`: every point of
the open forward Minkowski-cone of `p` lies in the chronological future of `p`.
A single straight-line trip segment already realises the precedence, so this is
`Relation.TransGen.single` applied to `minkowskiForwardCone_subset_segmentPrecedes`. -/
theorem minkowskiForwardCone_subset_chronologicalFuture_standardMinkowski
    (p : SpacetimeModel) :
    minkowskiForwardCone p ⊆
      Spacetime.chronologicalFuture StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation p := by
  intro q hq
  -- Unfold `chronologicalFuture`, `ChronologicallyPrecedes`, `IsTrip`.
  change Relation.TransGen
    (Spacetime.SegmentPrecedes StandardMinkowskiSpacetime
      standardMinkowskiTimeOrientation) p q
  exact Relation.TransGen.single (minkowskiForwardCone_subset_segmentPrecedes hq)

/-- **Characterisation of `chronologicalFuture` on standard Minkowski.**
The chronological future of `p` on `StandardMinkowskiSpacetime` agrees with
the forward Minkowski-cone of `p`. This is the coordinate-explicit form of
`I⁺(p)` that lets the agreement of the Alexandrov topology with the
Euclidean topology on `ℝ⁴` be proved. The two directions are split into
`chronologicalFuture_standardMinkowski_subset` and
`minkowskiForwardCone_subset_chronologicalFuture_standardMinkowski`
(each assembled from the small analytic lemmas above). -/
theorem chronologicalFuture_standardMinkowski (p : SpacetimeModel) :
    Spacetime.chronologicalFuture StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation p
      = minkowskiForwardCone p :=
  Set.Subset.antisymm
    (chronologicalFuture_standardMinkowski_subset p)
    (minkowskiForwardCone_subset_chronologicalFuture_standardMinkowski p)

/-- **Characterisation of `chronologicalPast` on standard Minkowski.**
Dual to `chronologicalFuture_standardMinkowski`, obtained from it by the
definitional time-reversal symmetry of `ChronologicallyPrecedes`. -/
theorem chronologicalPast_standardMinkowski (q : SpacetimeModel) :
    Spacetime.chronologicalPast StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation q
      = minkowskiBackwardCone q := by
  ext p
  change p ∈ Spacetime.chronologicalPast StandardMinkowskiSpacetime
                 standardMinkowskiTimeOrientation q
       ↔ p ∈ minkowskiBackwardCone q
  rw [show p ∈ Spacetime.chronologicalPast StandardMinkowskiSpacetime
              standardMinkowskiTimeOrientation q
        ↔ q ∈ Spacetime.chronologicalFuture StandardMinkowskiSpacetime
              standardMinkowskiTimeOrientation p
        from Iff.rfl,
      chronologicalFuture_standardMinkowski p,
      minkowskiBackwardCone_eq]
  rfl

/-- *Easy direction of the Alexandrov-vs-Euclidean topology comparison.*
Every Alexandrov-basis set `I⁺(p) ∩ I⁻(q)` on standard Minkowski spacetime
is open in the Euclidean topology on `ℝ⁴`. In Mathlib's convention
(`t₁ ≤ t₂ ↔ ∀ U, IsOpen[t₂] U → IsOpen[t₁] U`), this is stated as
`Euclidean ≤ Alexandrov`. -/
theorem euclidean_le_alexandrov_standardMinkowski :
    (inferInstance : TopologicalSpace SpacetimeModel)
      ≤ Spacetime.alexandrovTopology StandardMinkowskiSpacetime
          standardMinkowskiTimeOrientation := by
  apply le_generateFrom
  rintro s ⟨p, q, rfl⟩
  rw [chronologicalFuture_standardMinkowski, chronologicalPast_standardMinkowski]
  exact (isOpen_minkowskiForwardCone p).inter (isOpen_minkowskiBackwardCone q)

/-- *Hard direction of the Alexandrov-vs-Euclidean topology comparison.*
Every Euclidean-open subset of standard Minkowski spacetime is open in the
Alexandrov topology. In Mathlib's convention
(`t₁ ≤ t₂ ↔ ∀ U, IsOpen[t₂] U → IsOpen[t₁] U`), this is stated as
`Alexandrov ≤ Euclidean`. Around each Euclidean-open point `x` we find a
double cone `I⁺(x⁻) ∩ I⁻(x⁺)` shrunk to fit inside an open ball of `U`. -/
theorem alexandrov_le_euclidean_standardMinkowski :
    Spacetime.alexandrovTopology StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation
      ≤ (inferInstance : TopologicalSpace SpacetimeModel) := by
  rw [TopologicalSpace.le_def]
  -- `StandardMinkowskiSpacetime.Carrier` is definitionally `SpacetimeModel`,
  -- so we may transport everything to the underlying Euclidean model.
  change ∀ U : Set SpacetimeModel, IsOpen U →
      @IsOpen SpacetimeModel
        (Spacetime.alexandrovTopology StandardMinkowskiSpacetime
          standardMinkowskiTimeOrientation) U
  intro U hU
  -- We prove `IsOpen[Alexandrov] U` by showing every point of `U` has an
  -- Alexandrov-open neighbourhood inside `U`.
  refine (@isOpen_iff_forall_mem_open SpacetimeModel
      (Spacetime.alexandrovTopology StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation) U).mpr ?_
  intro x hxU
  obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.mp hU x hxU
  set δ : ℝ := ε / 2 with hδ
  have hδpos : 0 < δ := by rw [hδ]; linarith
  have hε4 : ε ^ 2 = 4 * δ ^ 2 := by rw [hδ]; ring
  -- Define the shifted points x⁻ and x⁺
  set xMinus : SpacetimeModel := x - δ • EuclideanSpace.single (0 : Fin 4) (1 : ℝ)
    with hxMinus
  set xPlus : SpacetimeModel := x + δ • EuclideanSpace.single (0 : Fin 4) (1 : ℝ)
    with hxPlus
  -- Coordinate evaluations of x⁻ and x⁺
  obtain ⟨xMinus0, xMinus1, xMinus2, xMinus3⟩ :
      xMinus 0 = x 0 - δ ∧ xMinus 1 = x 1 ∧ xMinus 2 = x 2 ∧ xMinus 3 = x 3 := by
    rw [hxMinus]
    refine ⟨?_, ?_, ?_, ?_⟩ <;>
      simp [PiLp.sub_apply, PiLp.smul_apply]
  obtain ⟨xPlus0, xPlus1, xPlus2, xPlus3⟩ :
      xPlus 0 = x 0 + δ ∧ xPlus 1 = x 1 ∧ xPlus 2 = x 2 ∧ xPlus 3 = x 3 := by
    rw [hxPlus]
    refine ⟨?_, ?_, ?_, ?_⟩ <;>
      simp [PiLp.add_apply, PiLp.smul_apply]
  -- Everything below only needs the coordinates above, so forget the bodies of
  -- `δ`, `x⁻`, `x⁺`: this keeps the remaining goals free of `PiLp` unfolding.
  clear_value xMinus xPlus δ
  clear hxMinus hxPlus hδ
  refine ⟨minkowskiForwardCone xMinus ∩ minkowskiBackwardCone xPlus,
    ?subset, ?openV, ?memV⟩
  · -- V ⊆ U: any q in V lies in the ε-ball around x
    rintro q ⟨hqFwd, hqBwd⟩
    apply hball
    simp only [mem_minkowskiForwardCone] at hqFwd
    simp only [mem_minkowskiBackwardCone] at hqBwd
    -- Rewrite the cone inequalities using the explicit coordinates
    rw [xMinus0, xMinus1, xMinus2, xMinus3] at hqFwd
    rw [xPlus0, xPlus1, xPlus2, xPlus3] at hqBwd
    obtain ⟨hLow, hConeFwd⟩ := hqFwd
    obtain ⟨hHigh, hConeBwd⟩ := hqBwd
    -- `dist q x ^ 2` expanded in coordinates.
    have hdist : dist q x ^ 2 =
        (q 0 - x 0) ^ 2 + (q 1 - x 1) ^ 2 + (q 2 - x 2) ^ 2 + (q 3 - x 3) ^ 2 := by
      rw [EuclideanSpace.dist_sq_eq q x, Fin.sum_univ_four]
      simp only [Real.dist_eq, sq_abs]
    -- The time separation is at most `δ`; the two cone inequalities add up to
    -- bound the spatial separation, giving `dist q x ^ 2 < 3 δ ^ 2 ≤ ε ^ 2`.
    have hsq : (q 0 - x 0) ^ 2 < δ ^ 2 := sq_lt_sq' (by linarith) (by linarith)
    rw [Metric.mem_ball]
    refine (abs_lt_of_sq_lt_sq' ?_ hε.le).2
    rw [hdist, hε4]
    linarith [sq_nonneg δ]
  · -- V is open in the Alexandrov topology
    refine TopologicalSpace.isOpen_generateFrom_of_mem ⟨xMinus, xPlus, ?_⟩
    rw [chronologicalFuture_standardMinkowski xMinus,
        chronologicalPast_standardMinkowski xPlus]
    rfl
  · -- x ∈ V
    refine ⟨⟨?_, ?_⟩, ?_, ?_⟩
    · rw [xMinus0]; linarith
    · rw [xMinus0, xMinus1, xMinus2, xMinus3]; linarith [pow_pos hδpos 2]
    · rw [xPlus0]; linarith
    · rw [xPlus0, xPlus1, xPlus2, xPlus3]; linarith [pow_pos hδpos 2]

/-- *Alexandrov = Euclidean on standard Minkowski.* Combining the two
inclusions `euclidean_le_alexandrov_standardMinkowski` and
`alexandrov_le_euclidean_standardMinkowski`, the Alexandrov topology
generated by intersections of chronological futures and pasts coincides
with the standard Euclidean topology on `ℝ⁴`. -/
theorem alexandrov_eq_euclidean_standardMinkowski :
    Spacetime.alexandrovTopology StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation
      = (inferInstance : TopologicalSpace SpacetimeModel) :=
  le_antisymm alexandrov_le_euclidean_standardMinkowski
    euclidean_le_alexandrov_standardMinkowski

/-- A `Type` synonym for the carrier of standard Minkowski spacetime
intended to carry the Alexandrov topology. -/
def MinkowskiSpacetimeCarrier : Type := StandardMinkowskiSpacetime.Carrier

/-- The Alexandrov topology on `MinkowskiSpacetimeCarrier`. -/
noncomputable instance : TopologicalSpace MinkowskiSpacetimeCarrier :=
  Spacetime.alexandrovTopology StandardMinkowskiSpacetime
    standardMinkowskiTimeOrientation

/-- The identity is a homeomorphism from the Euclidean model `SpacetimeModel`
to `MinkowskiSpacetimeCarrier` (which carries the Alexandrov topology),
because the two topologies coincide by
`alexandrov_eq_euclidean_standardMinkowski`. This is the transport device used
to inherit the Hausdorff, connectedness, and smooth-manifold structure. -/
noncomputable def euclideanHomeoMinkowski :
    SpacetimeModel ≃ₜ MinkowskiSpacetimeCarrier where
  toEquiv := Equiv.refl _
  continuous_toFun :=
    continuous_id_of_le (le_of_eq alexandrov_eq_euclidean_standardMinkowski.symm)
  continuous_invFun :=
    continuous_id_of_le (le_of_eq alexandrov_eq_euclidean_standardMinkowski)

/-- The single global chart on `MinkowskiSpacetimeCarrier`, given by the
identity homeomorphism onto the Euclidean model `SpacetimeModel`. -/
noncomputable instance instChartedSpaceMinkowskiCarrier :
    ChartedSpace SpacetimeModel MinkowskiSpacetimeCarrier :=
  euclideanHomeoMinkowski.symm.toOpenPartialHomeomorph.singletonChartedSpace
    (Homeomorph.toOpenPartialHomeomorph_source _)

/-- For the single-chart structure on `MinkowskiSpacetimeCarrier`, the chart at
every point is the same global chart. -/
@[simp] lemma chartAt_minkowskiCarrier (z : MinkowskiSpacetimeCarrier) :
    chartAt SpacetimeModel z =
      euclideanHomeoMinkowski.symm.toOpenPartialHomeomorph :=
  rfl

/-- The singleton-chart structure makes `MinkowskiSpacetimeCarrier` a `C^∞`
manifold over the trivial self-model: the only transition map is the identity. -/
noncomputable instance instIsManifoldMinkowskiCarrier :
    IsManifold (modelWithCornersSelf ℝ SpacetimeModel) ⊤ MinkowskiSpacetimeCarrier :=
  euclideanHomeoMinkowski.symm.toOpenPartialHomeomorph.isManifold_singleton
    (Homeomorph.toOpenPartialHomeomorph_source _)

/-- The chart inverse on `MinkowskiSpacetimeCarrier` has identity manifold
derivative at every point of the chart target. The single chart is constant in
the base point and the self-model has full range, so the inverse-chart
derivative is the identity throughout the target, not just at the base point. -/
lemma mfderiv_extChartAt_symm_minkowski (x₀ : MinkowskiSpacetimeCarrier)
    {y : SpacetimeModel}
    (hy : y ∈ (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀).target) :
    mfderiv (modelWithCornersSelf ℝ SpacetimeModel)
        (modelWithCornersSelf ℝ SpacetimeModel)
        (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀).symm y
      = ContinuousLinearMap.id ℝ SpacetimeModel := by
  set I := modelWithCornersSelf ℝ SpacetimeModel with hI
  have hchart : extChartAt I ((extChartAt I x₀).symm y) = extChartAt I x₀ := by
    simp only [extChartAt, chartAt_minkowskiCarrier]
  have key := mfderivWithin_range_extChartAt_symm (I := I)
    (x := (extChartAt I x₀).symm y)
  rw [hchart, PartialEquiv.right_inv _ hy, I.range_eq_univ,
    mfderivWithin_univ] at key
  exact key

/--
*Minkowski spacetime* is standard Minkowski spacetime re-topologised with
the Alexandrov topology generated by intersections of chronological
futures and pasts.

We return a `Spacetime` whose carrier is `MinkowskiSpacetimeCarrier`,
whose smooth-manifold data is inherited from `StandardMinkowskiSpacetime`,
and whose metric is `minkowskiForm`. The retopologisation of the carrier
to the Alexandrov topology is handled by the `TopologicalSpace` instance
on `MinkowskiSpacetimeCarrier`; the smooth-manifold data is transported
along the homeomorphism `euclideanHomeoMinkowski` via the named instances
`instChartedSpaceMinkowskiCarrier` and `instIsManifoldMinkowskiCarrier`
(the content of section 2.4 of the blueprint).
-/
noncomputable def MinkowskiSpacetime : Spacetime where
  Carrier := MinkowskiSpacetimeCarrier
  topology := inferInstance
  hausdorff := euclideanHomeoMinkowski.t2Space
  connected :=
    (Homeomorph.connectedSpace_iff euclideanHomeoMinkowski).mp inferInstance
  chartedSpace := instChartedSpaceMinkowskiCarrier
  model := modelWithCornersSelf ℝ SpacetimeModel
  isManifold := instIsManifoldMinkowskiCarrier
  tangent_findim := fun _ => by
    -- `TangentSpace (modelWithCornersSelf ℝ SpacetimeModel) _` reduces to
    -- `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`, which is finite-dimensional.
    change FiniteDimensional ℝ SpacetimeModel
    infer_instance
  val := fun _ => minkowskiForm
  symm := by
    intro _ v w
    change minkowskiForm v w = minkowskiForm w v
    simp only [minkowskiForm_apply]
    ring
  nondegenerate := by
    intro _ v hv
    -- `TangentSpace 𝓘(ℝ, SpacetimeModel) _` reduces to `SpacetimeModel`, so
    -- the hypothesis `hv` can be viewed at the model type for the `PiLp` API.
    have hv' : ∀ w : SpacetimeModel, minkowskiForm v w = 0 := hv
    apply PiLp.ext
    intro i
    -- The RHS `WithLp.ofLp 0 i` reduces definitionally to `(0 : ℝ)`.
    change v.ofLp i = (0 : ℝ)
    -- Instantiate `hv'` at the basis vector `EuclideanSpace.single i 1`.
    have hi := hv' (PiLp.single 2 i (1 : ℝ))
    simp only [minkowskiForm_apply] at hi
    -- `(PiLp.single 2 i 1).ofLp j = if j = i then 1 else 0`. Splitting on
    -- `i : Fin 4` and simplifying collapses `hi` to `v.ofLp i = 0`.
    fin_cases i <;> simp_all
  lorentzian := by
    intro x
    -- Witness: the standard orthonormal basis of `EuclideanSpace ℝ (Fin 4)`,
    -- viewed as a `Module.Basis` via `OrthonormalBasis.toBasis`.
    refine ⟨(EuclideanSpace.basisFun (Fin 4) ℝ).toBasis, ?_⟩
    intro i j
    -- Unfold the lambda and the `TangentSpace`/`OrthonormalBasis.toBasis`
    -- machinery so the goal becomes about `minkowskiForm` on
    -- `EuclideanSpace.single _ 1` vectors.
    change minkowskiForm
        ((EuclideanSpace.basisFun (Fin 4) ℝ) i)
        ((EuclideanSpace.basisFun (Fin 4) ℝ) j) =
        lorentzSignature i j
    rw [EuclideanSpace.basisFun_apply, EuclideanSpace.basisFun_apply]
    simp only [minkowskiForm_apply, lorentzSignature, Matrix.diagonal]
    fin_cases i <;> fin_cases j <;> simp [Matrix.of_apply]
  smooth_in_charts := by
    intro x₀ v w
    simp only
    -- The integrand is the constant `minkowskiForm v w` on the chart target,
    -- because the inverse-chart manifold derivative is the identity there.
    apply ContDiffWithinAt.congr_of_eventuallyEq
      (f := fun _ : SpacetimeModel => minkowskiForm v w)
    · exact contDiffWithinAt_const
    · filter_upwards [self_mem_nhdsWithin] with y hy
      rw [mfderiv_extChartAt_symm_minkowski x₀ hy]
      rfl
    · rw [mfderiv_extChartAt_symm_minkowski x₀
        ((extChartAt _ x₀).map_source (mem_extChartAt_source x₀))]
      rfl

/-- **Part (i): existence of a chronological-future point (standard Minkowski).**
Every point `x` of standard Minkowski spacetime has a point strictly to its
chronological future; concretely `x + e₀` lies in the forward Minkowski cone of
`x`, since the connecting vector `e₀` is future-pointing timelike. -/
theorem exists_chronologicalFuture_standardMinkowski (x : SpacetimeModel) :
    ∃ b, b ∈ Spacetime.chronologicalFuture StandardMinkowskiSpacetime
      standardMinkowskiTimeOrientation x := by
  set b := x + EuclideanSpace.single (0 : Fin 4) (1 : ℝ) with hb
  have single0 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) 0 = 1 := by
    rw [PiLp.single_apply]; simp
  have b0 : b 0 = x 0 + 1 := by
    rw [hb, PiLp.add_apply, single0]
  have b1 : b 1 = x 1 := by
    rw [hb, PiLp.add_apply, PiLp.single_apply]; simp
  have b2 : b 2 = x 2 := by
    rw [hb, PiLp.add_apply, PiLp.single_apply]; simp
  have b3 : b 3 = x 3 := by
    rw [hb, PiLp.add_apply, PiLp.single_apply]; simp
  refine ⟨b, ?_⟩
  rw [chronologicalFuture_standardMinkowski]
  have hmem : b ∈ minkowskiForwardCone x := by
    rw [mem_minkowskiForwardCone, b0, b1, b2, b3]
    constructor
    · nlinarith
    · norm_num
  exact hmem

/-- **Part (i), dual: existence of a chronological-past point.**
Every point `x` of standard Minkowski spacetime has a point strictly to its
chronological past; concretely `x - e₀` lies in the backward Minkowski cone. -/
theorem exists_chronologicalPast_standardMinkowski (x : SpacetimeModel) :
    ∃ a, a ∈ Spacetime.chronologicalPast StandardMinkowskiSpacetime
      standardMinkowskiTimeOrientation x := by
  set a := x - EuclideanSpace.single (0 : Fin 4) (1 : ℝ) with ha
  have single0 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) 0 = 1 := by
    rw [PiLp.single_apply]; simp
  have a0 : a 0 = x 0 - 1 := by
    rw [ha, PiLp.sub_apply, single0]
  have a1 : a 1 = x 1 := by
    rw [ha, PiLp.sub_apply, PiLp.single_apply]; simp
  have a2 : a 2 = x 2 := by
    rw [ha, PiLp.sub_apply, PiLp.single_apply]; simp
  have a3 : a 3 = x 3 := by
    rw [ha, PiLp.sub_apply, PiLp.single_apply]; simp
  refine ⟨a, ?_⟩
  rw [chronologicalPast_standardMinkowski]
  have hmem : a ∈ minkowskiBackwardCone x := by
    rw [mem_minkowskiBackwardCone, a0, a1, a2, a3]
    constructor
    · nlinarith
    · norm_num
  exact hmem

/-- **Part (ii): Euclidean openness of the chronological future.**
On standard Minkowski spacetime `I⁺(p)` is open in the Euclidean (manifold)
topology on `ℝ⁴`; via the coordinate cone characterisation it coincides with the
forward Minkowski cone, which is open. -/
theorem isOpen_chronologicalFuture_standardMinkowski (p : SpacetimeModel) :
    IsOpen (Spacetime.chronologicalFuture StandardMinkowskiSpacetime
      standardMinkowskiTimeOrientation p) := by
  rw [chronologicalFuture_standardMinkowski]
  exact isOpen_minkowskiForwardCone p

/-- **Part (ii), dual: Euclidean openness of the chronological past.** -/
theorem isOpen_chronologicalPast_standardMinkowski (q : SpacetimeModel) :
    IsOpen (Spacetime.chronologicalPast StandardMinkowskiSpacetime
      standardMinkowskiTimeOrientation q) := by
  rw [chronologicalPast_standardMinkowski]
  exact isOpen_minkowskiBackwardCone q

/-- **Part (iii): unconditional Alexandrov openness of the chronological future.**
On standard Minkowski spacetime `I⁺(p)` is open in the Alexandrov topology,
unconditionally: the per-point hypothesis of the general lemma
`Spacetime.isOpen_chronologicalFuture` is discharged by part (i). -/
theorem isOpen_alexandrov_chronologicalFuture_standardMinkowski (p : SpacetimeModel) :
    @IsOpen _ (Spacetime.alexandrovTopology StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation)
      (Spacetime.chronologicalFuture StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation p) := by
  refine Spacetime.isOpen_chronologicalFuture StandardMinkowskiSpacetime
    standardMinkowskiTimeOrientation p ?_
  intro x hx
  exact exists_chronologicalFuture_standardMinkowski x

/-- **Part (iii), dual: unconditional Alexandrov openness of the chronological past.** -/
theorem isOpen_alexandrov_chronologicalPast_standardMinkowski (q : SpacetimeModel) :
    @IsOpen _ (Spacetime.alexandrovTopology StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation)
      (Spacetime.chronologicalPast StandardMinkowskiSpacetime
        standardMinkowskiTimeOrientation q) := by
  refine Spacetime.isOpen_chronologicalPast StandardMinkowskiSpacetime
    standardMinkowskiTimeOrientation q ?_
  intro x hx
  exact exists_chronologicalPast_standardMinkowski x

end Physicslib4
