/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.Spacetime.Basic
import Physicslib4.Spacetime.CausalStructure
import Physicslib4.Spacetime.Curves
import Physicslib4.Spacetime.Causality
import Mathlib.Geometry.Manifold.MFDeriv.SpecificFunctions

/-!
# Minkowski spacetime and the Alexandrov topology

This file formalises the last three definitions of section 9.2 of the
AQFT-in-Lean blueprint: standard Minkowski spacetime, the Alexandrov
topology generated by intersections of chronological futures and pasts,
and Minkowski spacetime (= standard Minkowski equipped with the
Alexandrov topology).

## Main definitions

* `Physicslib4.StandardMinkowskiSpacetime`: the unique spacetime whose
  underlying manifold is `ℝ⁴` with its Euclidean topology and whose
  metric is `diag(-1, 1, 1, 1)` in the standard coordinates.
* `Physicslib4.Spacetime.alexandrovTopology`: the topology on a spacetime
  generated by all sets of the form `I^+(p) ∩ I^-(q)`.
* `Physicslib4.MinkowskiSpacetime`: a `Type` synonym for
  `StandardMinkowskiSpacetime.Carrier` carrying the Alexandrov topology
  as the canonical topology instance.

## Modelling notes

* The bilinear form on `T_p ℝ⁴` corresponding to `diag(-1,1,1,1)` is
  constructed pointwise as a continuous bilinear map. We expose the
  underlying function on the model space; the proofs of symmetry,
  non-degeneracy, the Lorentzian condition, and smoothness in charts
  are left as `sorry`, since their formal expansion against Mathlib's
  `mfderiv` / `extChartAt` API for `ℝ⁴` is a substantial separate
  endeavour. The blueprint's *statement* is faithfully captured by the
  shape of `StandardMinkowskiSpacetime`.

* `MinkowskiSpacetime` is defined as a type synonym for the carrier of
  `StandardMinkowskiSpacetime` (i.e. `ℝ⁴`), with a `TopologicalSpace`
  instance given by the Alexandrov topology. The smooth-manifold
  structure is inherited from `StandardMinkowskiSpacetime` if one wishes
  to view the same underlying point set as both.
-/

namespace Physicslib4

open scoped Manifold

/-! ### Standard Minkowski spacetime -/

/-- The underlying bilinear `LinearMap` for the Minkowski metric on
`ℝ⁴`: `(v, w) ↦ -v 0 * w 0 + v 1 * w 1 + v 2 * w 2 + v 3 * w 3`. -/
noncomputable def minkowskiFormₗ :
    SpacetimeModel →ₗ[ℝ] SpacetimeModel →ₗ[ℝ] ℝ :=
  LinearMap.mk₂ ℝ
    (fun v w => -(v 0) * (w 0) + (v 1) * (w 1) + (v 2) * (w 2) + (v 3) * (w 3))
    (fun v₁ v₂ w => by simp; ring)
    (fun c v w => by simp; ring)
    (fun v w₁ w₂ => by simp; ring)
    (fun c v w => by simp; ring)

/-- The Minkowski metric on `T_p ℝ⁴ = ℝ⁴`, viewed as a continuous bilinear
form `ℝ⁴ →L[ℝ] ℝ⁴ →L[ℝ] ℝ` given by `(v, w) ↦ -v 0 * w 0 + v 1 * w 1 +
v 2 * w 2 + v 3 * w 3`. This is the form whose Gram matrix in the standard
basis is `diag(-1, 1, 1, 1) = lorentzSignature`. -/
noncomputable def minkowskiForm :
    SpacetimeModel →L[ℝ] SpacetimeModel →L[ℝ] ℝ :=
  LinearMap.toContinuousLinearMap
    { toFun := fun v => LinearMap.toContinuousLinearMap (minkowskiFormₗ v)
      map_add' := fun v₁ v₂ => by
        ext w
        simp [minkowskiFormₗ]
      map_smul' := fun c v => by
        ext w
        simp [minkowskiFormₗ] }

@[simp] theorem minkowskiForm_apply (v w : SpacetimeModel) :
    minkowskiForm v w =
      -(v 0) * (w 0) + (v 1) * (w 1) + (v 2) * (w 2) + (v 3) * (w 3) := by
  rfl

/--
*Standard Minkowski spacetime* is the spacetime whose underlying real,
four-dimensional, connected, smooth, Hausdorff manifold is `ℝ⁴` (with the
Euclidean topology) and whose metric `g|_p` is `diag(-1, 1, 1, 1)` in the
standard coordinates, for every `p`.

We package the spacetime via the `Spacetime` structure, using the identity
charted space on `EuclideanSpace ℝ (Fin 4)` and the identity model with
corners. The metric is the constant continuous bilinear form
`minkowskiForm`.
-/
noncomputable def StandardMinkowskiSpacetime : Spacetime where
  Carrier := SpacetimeModel
  topology := inferInstance
  hausdorff := inferInstance
  connected := inferInstance
  chartedSpace := chartedSpaceSelf SpacetimeModel
  model := modelWithCornersSelf ℝ SpacetimeModel
  isManifold := by
    -- The identity charted space is a `C^∞` manifold.
    infer_instance
  tangent_findim := fun _ => by
    -- `TangentSpace (modelWithCornersSelf ℝ SpacetimeModel) _` reduces to
    -- `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`, which is finite-dimensional.
    change FiniteDimensional ℝ SpacetimeModel
    infer_instance
  val := fun _ => minkowskiForm
  symm := by
    intro _ v w
    change minkowskiForm v w = minkowskiForm w v
    simp only [minkowskiForm_apply]
    ring
  nondegenerate := by
    intro _ v hv
    -- `TangentSpace 𝓘(ℝ, SpacetimeModel) _` reduces to `SpacetimeModel`, so
    -- the hypothesis `hv` can be viewed at the model type for the `PiLp` API.
    have hv' : ∀ w : SpacetimeModel, minkowskiForm v w = 0 := hv
    apply PiLp.ext
    intro i
    -- The RHS `WithLp.ofLp 0 i` reduces definitionally to `(0 : ℝ)`.
    change v.ofLp i = (0 : ℝ)
    -- Instantiate `hv'` at the basis vector `EuclideanSpace.single i 1`.
    have hi := hv' (PiLp.single 2 i (1 : ℝ))
    simp only [minkowskiForm_apply] at hi
    -- `(PiLp.single 2 i 1).ofLp j = if j = i then 1 else 0`. Splitting on
    -- `i : Fin 4` and simplifying collapses `hi` to `v.ofLp i = 0`.
    fin_cases i <;> simp_all
  lorentzian := by
    intro x
    -- Witness: the standard orthonormal basis of `EuclideanSpace ℝ (Fin 4)`,
    -- viewed as a `Module.Basis` via `OrthonormalBasis.toBasis`.
    refine ⟨(EuclideanSpace.basisFun (Fin 4) ℝ).toBasis, ?_⟩
    intro i j
    -- Unfold the lambda and the `TangentSpace`/`OrthonormalBasis.toBasis`
    -- machinery so the goal becomes about `minkowskiForm` on
    -- `EuclideanSpace.single _ 1` vectors.
    change minkowskiForm
        ((EuclideanSpace.basisFun (Fin 4) ℝ) i)
        ((EuclideanSpace.basisFun (Fin 4) ℝ) j) =
        lorentzSignature i j
    rw [EuclideanSpace.basisFun_apply, EuclideanSpace.basisFun_apply]
    simp only [minkowskiForm_apply, lorentzSignature, Matrix.diagonal]
    fin_cases i <;> fin_cases j <;> simp [Matrix.of_apply]
  smooth_in_charts := by
    intro x₀ v w
    -- Unfold the `let e := extChartAt ... x₀` binding.
    simp only
    -- On the model space, `mfderiv I I (e.symm) y = id`, so the integrand is
    -- the constant `minkowskiForm v w` on `e.target = univ`.
    apply ContDiffWithinAt.congr_of_eventuallyEq
      (f := fun _ : SpacetimeModel => minkowskiForm v w)
    · exact contDiffWithinAt_const
    · -- Pointwise equality of the integrand with the constant `minkowskiForm v w`
      -- on a neighborhood of `e x₀` within `e.target`.
      filter_upwards with y
      have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀).symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, mfderiv_id]
      rfl
    · -- `(fun _ => minkowskiForm v w) (e x₀) = minkowskiForm v w`, and the
      -- function we replaced it with also evaluates to `minkowskiForm v w`
      -- at `y = e x₀` (since `e.symm (e x₀) = x₀` and `mfderiv id = id`).
      have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀).symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, mfderiv_id]
      rfl

/-- Additive-group structure on the Minkowski spacetime carrier,
inherited from `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`. -/
noncomputable instance instAddCommGroupStandardMinkowskiCarrier :
    AddCommGroup StandardMinkowskiSpacetime.Carrier := by
  change AddCommGroup SpacetimeModel
  infer_instance

/-- `ℝ`-module structure on the Minkowski spacetime carrier,
inherited from `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`. -/
noncomputable instance instModuleStandardMinkowskiCarrier :
    Module ℝ StandardMinkowskiSpacetime.Carrier := by
  change Module ℝ SpacetimeModel
  infer_instance

/-! ### The orthochronous Lorentz group SO(1,3)↑ -/

/-- A linear automorphism `L` of the spacetime model preserves the
Minkowski form: `⟨L v, L w⟩ = ⟨v, w⟩` for all `v, w`. -/
def IsLorentz (L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel) : Prop :=
  ∀ v w, minkowskiForm (L v) (L w) = minkowskiForm v w

/-- A linear automorphism `L` is *proper* if its determinant is `1`. -/
def IsProper (L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel) : Prop :=
  LinearMap.det L.toLinearMap = 1

/-- A linear automorphism `L` is *orthochronous* if it preserves the
direction of time: the time component of `L e₀` is positive, where
`e₀ = EuclideanSpace.single 0 1` is the standard timelike basis vector. -/
def IsOrthochronous (L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel) : Prop :=
  0 < (L (EuclideanSpace.single (0 : Fin 4) (1 : ℝ))) 0

/-- The identity preserves the Minkowski form. -/
theorem isLorentz_refl : IsLorentz (LinearEquiv.refl ℝ SpacetimeModel) := by
  intro v w; rfl

/-- The composition of two Lorentz transformations is Lorentz. -/
theorem isLorentz_trans {L₁ L₂ : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h₁ : IsLorentz L₁) (h₂ : IsLorentz L₂) : IsLorentz (L₁.trans L₂) := by
  intro v w
  simp only [LinearEquiv.trans_apply]
  rw [h₂, h₁]

/-- The inverse of a Lorentz transformation is Lorentz. -/
theorem isLorentz_symm {L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h : IsLorentz L) : IsLorentz L.symm := by
  intro v w
  have := h (L.symm v) (L.symm w)
  rw [L.apply_symm_apply, L.apply_symm_apply] at this
  exact this.symm

/-- The identity is proper. -/
theorem isProper_refl : IsProper (LinearEquiv.refl ℝ SpacetimeModel) := by
  unfold IsProper
  rw [LinearEquiv.refl_toLinearMap]
  exact LinearMap.det_id

/-- The composition of two proper transformations is proper. -/
theorem isProper_trans {L₁ L₂ : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h₁ : IsProper L₁) (h₂ : IsProper L₂) : IsProper (L₁.trans L₂) := by
  unfold IsProper at h₁ h₂ ⊢
  show LinearMap.det (L₁.trans L₂).toLinearMap = 1
  -- `(L₁.trans L₂).toLinearMap = L₂.toLinearMap ∘ₗ L₁.toLinearMap`.
  have : (L₁.trans L₂).toLinearMap = L₂.toLinearMap ∘ₗ L₁.toLinearMap := rfl
  rw [this, LinearMap.det_comp, h₁, h₂, mul_one]

/-- The inverse of a proper transformation is proper. -/
theorem isProper_symm {L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (h : IsProper L) : IsProper L.symm := by
  -- Use that `LinearEquiv.det` is a monoid hom to `Rˣ` and
  -- `LinearEquiv.coe_inv_det` relates it to `LinearMap.det _.symm`.
  unfold IsProper at h ⊢
  have h1 : (LinearEquiv.det L : ℝ) = 1 := by
    rw [LinearEquiv.coe_det]; exact h
  -- `LinearMap.det L.symm = ↑(LinearEquiv.det L)⁻¹`.
  rw [← LinearEquiv.coe_inv_det]
  -- `↑(u⁻¹) = (↑u)⁻¹` for units, then use `h1`.
  rw [Units.val_inv_eq_inv_val, h1, inv_one]

/-- The identity is orthochronous. -/
theorem isOrthochronous_refl :
    IsOrthochronous (LinearEquiv.refl ℝ SpacetimeModel) := by
  unfold IsOrthochronous
  simp only [LinearEquiv.refl_apply]
  -- `(EuclideanSpace.single 0 1) 0 = 1 > 0`.
  -- `EuclideanSpace ℝ (Fin 4)` is definitionally `PiLp 2 (fun _ => ℝ)`,
  -- and `(x : EuclideanSpace ℝ ι) i = x.ofLp i` definitionally.
  change (0 : ℝ) < (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0
  have : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 = 1 := by
    rw [PiLp.single_apply]; simp
  rw [this]
  exact one_pos

/-- The composition of two orthochronous Lorentz transformations is
orthochronous. (Requires that both transformations are Lorentz.) -/
theorem isOrthochronous_trans {L₁ L₂ : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (hL₁ : IsLorentz L₁) (hO₁ : IsOrthochronous L₁)
    (hL₂ : IsLorentz L₂) (hO₂ : IsOrthochronous L₂) :
    IsOrthochronous (L₁.trans L₂) := by
  -- TODO: requires reverse Cauchy-Schwarz on a Lorentzian form
  sorry

/-- The inverse of an orthochronous Lorentz transformation is
orthochronous. -/
theorem isOrthochronous_symm {L : SpacetimeModel ≃ₗ[ℝ] SpacetimeModel}
    (hL : IsLorentz L) (hO : IsOrthochronous L) : IsOrthochronous L.symm := by
  -- TODO: requires reverse Cauchy-Schwarz on a Lorentzian form
  sorry

/-! ### Alexandrov topology -/

namespace Spacetime

variable (M : Spacetime)

attribute [instance] Spacetime.topology Spacetime.hausdorff Spacetime.connected
  Spacetime.chartedSpace Spacetime.isManifold Spacetime.tangent_findim

/-- The basis sets generating the Alexandrov topology: all sets of the
form `I^+(p) ∩ I^-(q)` for `p, q ∈ M`. -/
def alexandrovBasis (t : M.TimeOrientation) : Set (Set M.Carrier) :=
  {U | ∃ p q : M.Carrier, U = chronologicalFuture M t p ∩ chronologicalPast M t q}

/--
The *Alexandrov topology* on a spacetime `M`, with respect to a chosen
time orientation `t`: the topology generated by the basis `alexandrovBasis`
consisting of all intersections of chronological futures and pasts.
-/
@[reducible] def alexandrovTopology (t : M.TimeOrientation) :
    TopologicalSpace M.Carrier :=
  TopologicalSpace.generateFrom (alexandrovBasis M t)

end Spacetime

/-! ### Minkowski spacetime -/

/--
*Minkowski spacetime* is the carrier of `StandardMinkowskiSpacetime`
viewed as a topological space under the Alexandrov topology.

We expose `MinkowskiSpacetime` as a `def` returning a `Spacetime`,
following the convention used for `StandardMinkowskiSpacetime`. The
"underlying topology is the Alexandrov topology" character of Minkowski
spacetime is captured at the typeclass level by the alternative
`MinkowskiSpacetimeCarrier` synonym below, which carries the Alexandrov
topology directly.

A time orientation `t` on standard Minkowski spacetime is required to
talk about the Alexandrov topology. We leave its construction as
`sorry`; the canonical choice is the constant timelike vector field
`∂_0` pointing in the `0`-th coordinate direction.
-/
noncomputable def standardMinkowskiTimeOrientation :
    StandardMinkowskiSpacetime.TimeOrientation where
  field := fun _ => EuclideanSpace.single (0 : Fin 4) (1 : ℝ)
  nonvanishing := by
    intro x h
    have h0 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 = 1 := by
      rw [PiLp.single_apply]; simp
    have hzero : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 =
        (0 : SpacetimeModel).ofLp 0 := by rw [h]; rfl
    have hz : (0 : SpacetimeModel).ofLp 0 = (0 : ℝ) := rfl
    rw [h0, hz] at hzero
    exact one_ne_zero hzero
  timelike_at := by
    intro x
    change minkowskiForm (EuclideanSpace.single (0 : Fin 4) (1 : ℝ))
                         (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)) < 0
    simp only [minkowskiForm_apply]
    have h0 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0 = 1 := by
      rw [PiLp.single_apply]; simp
    have h1 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 1 = 0 := by
      rw [PiLp.single_apply]; simp
    have h2 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 2 = 0 := by
      rw [PiLp.single_apply]; simp
    have h3 : (EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 3 = 0 := by
      rw [PiLp.single_apply]; simp
    change -((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 0) +
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 1) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 1) +
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 2) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 2) +
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 3) *
        ((EuclideanSpace.single (0 : Fin 4) (1 : ℝ)).ofLp 3) < 0
    rw [h0, h1, h2, h3]
    norm_num
  smooth := by
    intro x₀
    -- `StandardMinkowskiSpacetime.Carrier = SpacetimeModel` by `rfl`. Cast
    -- `x₀` to `SpacetimeModel` explicitly so the structure projections in
    -- the goal reduce, matching the pattern of `smooth_in_charts`.
    let x₀' : SpacetimeModel := x₀
    change ContDiffWithinAt ℝ ⊤
      (fun y => mfderiv (modelWithCornersSelf ℝ SpacetimeModel)
                        (modelWithCornersSelf ℝ SpacetimeModel)
          (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm y
          (mfderiv (modelWithCornersSelf ℝ SpacetimeModel)
                   (modelWithCornersSelf ℝ SpacetimeModel)
            (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀')
            ((extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm y)
            (EuclideanSpace.single (0 : Fin 4) (1 : ℝ))))
      (extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').target
      ((extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀') x₀')
    apply ContDiffWithinAt.congr_of_eventuallyEq
      (f := fun _ : SpacetimeModel => EuclideanSpace.single (0 : Fin 4) (1 : ℝ))
    · exact contDiffWithinAt_const
    · filter_upwards with y
      have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      have hchart :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀') =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, hchart]
      simp only [mfderiv_id]
      rfl
    · have hsymm :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀').symm =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      have hchart :
          ⇑(extChartAt (modelWithCornersSelf ℝ SpacetimeModel) x₀') =
            (id : SpacetimeModel → SpacetimeModel) := by
        simp
      rw [hsymm, hchart]
      simp only [mfderiv_id]
      rfl

/-- A `Type` synonym for the carrier of standard Minkowski spacetime
intended to carry the Alexandrov topology. -/
def MinkowskiSpacetimeCarrier : Type := StandardMinkowskiSpacetime.Carrier

/-- The Alexandrov topology on `MinkowskiSpacetimeCarrier`. -/
noncomputable instance : TopologicalSpace MinkowskiSpacetimeCarrier :=
  Spacetime.alexandrovTopology StandardMinkowskiSpacetime
    standardMinkowskiTimeOrientation

/--
*Minkowski spacetime* is standard Minkowski spacetime re-topologised with
the Alexandrov topology generated by intersections of chronological
futures and pasts.

We return a `Spacetime` whose carrier is `MinkowskiSpacetimeCarrier`,
whose smooth-manifold data is inherited from `StandardMinkowskiSpacetime`,
and whose metric is `minkowskiForm`. The retopologisation of the carrier
to the Alexandrov topology is handled by the `TopologicalSpace` instance
on `MinkowskiSpacetimeCarrier`; the remaining smooth-manifold data is
re-asserted as `sorry`, since proving that the smooth-manifold structure
on `StandardMinkowskiSpacetime` transports to the Alexandrov topology is
mathematically non-trivial (it is the *content* of section 2.4 of the
blueprint).
-/
noncomputable def MinkowskiSpacetime : Spacetime where
  Carrier := MinkowskiSpacetimeCarrier
  topology := inferInstance
  hausdorff := by sorry
  connected := by sorry
  chartedSpace := by
    -- Carry over the chart structure from `StandardMinkowskiSpacetime` via
    -- the identity on points.
    sorry
  model := StandardMinkowskiSpacetime.model
  isManifold := by sorry
  tangent_findim := by sorry
  val := by sorry
  symm := by sorry
  nondegenerate := by sorry
  lorentzian := by sorry
  smooth_in_charts := by sorry

end Physicslib4
