/-
Copyright (c) 2026 Lean Community. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Community
-/
import Physicslib4.Spacetime.Basic
import Physicslib4.Spacetime.CausalStructure
import Physicslib4.Spacetime.Curves
import Physicslib4.Spacetime.Causality

/-!
# Minkowski spacetime and the Alexandrov topology

This file formalises the last three definitions of section 9.2 of the
AQFT-in-Lean blueprint: standard Minkowski spacetime, the Alexandrov
topology generated by intersections of chronological futures and pasts,
and Minkowski spacetime (= standard Minkowski equipped with the
Alexandrov topology).

## Main definitions

* `Physicslib4.StandardMinkowskiSpacetime`: the unique spacetime whose
  underlying manifold is `ℝ⁴` with its Euclidean topology and whose
  metric is `diag(-1, 1, 1, 1)` in the standard coordinates.
* `Physicslib4.Spacetime.alexandrovTopology`: the topology on a spacetime
  generated by all sets of the form `I^+(p) ∩ I^-(q)`.
* `Physicslib4.MinkowskiSpacetime`: a `Type` synonym for
  `StandardMinkowskiSpacetime.Carrier` carrying the Alexandrov topology
  as the canonical topology instance.

## Modelling notes

* The bilinear form on `T_p ℝ⁴` corresponding to `diag(-1,1,1,1)` is
  constructed pointwise as a continuous bilinear map. We expose the
  underlying function on the model space; the proofs of symmetry,
  non-degeneracy, the Lorentzian condition, and smoothness in charts
  are left as `sorry`, since their formal expansion against Mathlib's
  `mfderiv` / `extChartAt` API for `ℝ⁴` is a substantial separate
  endeavour. The blueprint's *statement* is faithfully captured by the
  shape of `StandardMinkowskiSpacetime`.

* `MinkowskiSpacetime` is defined as a type synonym for the carrier of
  `StandardMinkowskiSpacetime` (i.e. `ℝ⁴`), with a `TopologicalSpace`
  instance given by the Alexandrov topology. The smooth-manifold
  structure is inherited from `StandardMinkowskiSpacetime` if one wishes
  to view the same underlying point set as both.
-/

namespace Physicslib4

open scoped Manifold

/-! ### Standard Minkowski spacetime -/

/-- The Minkowski metric on `T_p ℝ⁴ = ℝ⁴`, viewed as a continuous bilinear
form `ℝ⁴ →L[ℝ] ℝ⁴ →L[ℝ] ℝ` given by `(v, w) ↦ -v 0 * w 0 + v 1 * w 1 +
v 2 * w 2 + v 3 * w 3`. This is the form whose Gram matrix in the standard
basis is `diag(-1, 1, 1, 1) = lorentzSignature`. -/
noncomputable def minkowskiForm :
    SpacetimeModel →L[ℝ] SpacetimeModel →L[ℝ] ℝ :=
  sorry

/--
*Standard Minkowski spacetime* is the spacetime whose underlying real,
four-dimensional, connected, smooth, Hausdorff manifold is `ℝ⁴` (with the
Euclidean topology) and whose metric `g|_p` is `diag(-1, 1, 1, 1)` in the
standard coordinates, for every `p`.

We package the spacetime via the `Spacetime` structure, using the identity
charted space on `EuclideanSpace ℝ (Fin 4)` and the identity model with
corners. The metric is the constant continuous bilinear form
`minkowskiForm`.
-/
noncomputable def StandardMinkowskiSpacetime : Spacetime where
  Carrier := SpacetimeModel
  topology := inferInstance
  hausdorff := inferInstance
  connected := inferInstance
  chartedSpace := chartedSpaceSelf SpacetimeModel
  model := modelWithCornersSelf ℝ SpacetimeModel
  isManifold := by
    -- The identity charted space is a `C^∞` manifold.
    infer_instance
  tangent_findim := fun _ => by
    -- `TangentSpace` at the identity model is the model itself, which is
    -- finite-dimensional.
    sorry
  val := fun _ => minkowskiForm
  symm := by sorry
  nondegenerate := by sorry
  lorentzian := by sorry
  smooth_in_charts := by sorry

/-- Additive-group structure on the Minkowski spacetime carrier,
inherited from `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`. -/
noncomputable instance instAddCommGroupStandardMinkowskiCarrier :
    AddCommGroup StandardMinkowskiSpacetime.Carrier := by
  change AddCommGroup SpacetimeModel
  infer_instance

/-- `ℝ`-module structure on the Minkowski spacetime carrier,
inherited from `SpacetimeModel = EuclideanSpace ℝ (Fin 4)`. -/
noncomputable instance instModuleStandardMinkowskiCarrier :
    Module ℝ StandardMinkowskiSpacetime.Carrier := by
  change Module ℝ SpacetimeModel
  infer_instance

/-! ### Alexandrov topology -/

namespace Spacetime

variable (M : Spacetime)

attribute [instance] Spacetime.topology Spacetime.hausdorff Spacetime.connected
  Spacetime.chartedSpace Spacetime.isManifold Spacetime.tangent_findim

/-- The basis sets generating the Alexandrov topology: all sets of the
form `I^+(p) ∩ I^-(q)` for `p, q ∈ M`. -/
def alexandrovBasis (t : M.TimeOrientation) : Set (Set M.Carrier) :=
  {U | ∃ p q : M.Carrier, U = chronologicalFuture M t p ∩ chronologicalPast M t q}

/--
The *Alexandrov topology* on a spacetime `M`, with respect to a chosen
time orientation `t`: the topology generated by the basis `alexandrovBasis`
consisting of all intersections of chronological futures and pasts.
-/
@[reducible] def alexandrovTopology (t : M.TimeOrientation) :
    TopologicalSpace M.Carrier :=
  TopologicalSpace.generateFrom (alexandrovBasis M t)

end Spacetime

/-! ### Minkowski spacetime -/

/--
*Minkowski spacetime* is the carrier of `StandardMinkowskiSpacetime`
viewed as a topological space under the Alexandrov topology.

We expose `MinkowskiSpacetime` as a `def` returning a `Spacetime`,
following the convention used for `StandardMinkowskiSpacetime`. The
"underlying topology is the Alexandrov topology" character of Minkowski
spacetime is captured at the typeclass level by the alternative
`MinkowskiSpacetimeCarrier` synonym below, which carries the Alexandrov
topology directly.

A time orientation `t` on standard Minkowski spacetime is required to
talk about the Alexandrov topology. We leave its construction as
`sorry`; the canonical choice is the constant timelike vector field
`∂_0` pointing in the `0`-th coordinate direction.
-/
noncomputable def standardMinkowskiTimeOrientation :
    StandardMinkowskiSpacetime.TimeOrientation :=
  sorry

/-- A `Type` synonym for the carrier of standard Minkowski spacetime
intended to carry the Alexandrov topology. -/
def MinkowskiSpacetimeCarrier : Type := StandardMinkowskiSpacetime.Carrier

/-- The Alexandrov topology on `MinkowskiSpacetimeCarrier`. -/
noncomputable instance : TopologicalSpace MinkowskiSpacetimeCarrier :=
  Spacetime.alexandrovTopology StandardMinkowskiSpacetime
    standardMinkowskiTimeOrientation

/--
*Minkowski spacetime* is standard Minkowski spacetime re-topologised with
the Alexandrov topology generated by intersections of chronological
futures and pasts.

We return a `Spacetime` whose carrier is `MinkowskiSpacetimeCarrier`,
whose smooth-manifold data is inherited from `StandardMinkowskiSpacetime`,
and whose metric is `minkowskiForm`. The retopologisation of the carrier
to the Alexandrov topology is handled by the `TopologicalSpace` instance
on `MinkowskiSpacetimeCarrier`; the remaining smooth-manifold data is
re-asserted as `sorry`, since proving that the smooth-manifold structure
on `StandardMinkowskiSpacetime` transports to the Alexandrov topology is
mathematically non-trivial (it is the *content* of section 2.4 of the
blueprint).
-/
noncomputable def MinkowskiSpacetime : Spacetime where
  Carrier := MinkowskiSpacetimeCarrier
  topology := inferInstance
  hausdorff := by sorry
  connected := by sorry
  chartedSpace := by
    -- Carry over the chart structure from `StandardMinkowskiSpacetime` via
    -- the identity on points.
    sorry
  model := StandardMinkowskiSpacetime.model
  isManifold := by sorry
  tangent_findim := by sorry
  val := by sorry
  symm := by sorry
  nondegenerate := by sorry
  lorentzian := by sorry
  smooth_in_charts := by sorry

end Physicslib4
